### ISSUE TITLE
Are there any admin dashborad templates or examples ?

### ISSUE THREAD

**Issue by aero** [qooxdoo/qooxdoo#10009]
Hello,

I'm trying to find admin dashboard template or example for qooxdoo like
* Plain HTML,CSS,JS,bootstrap
   https://adminlte.io/themes/AdminLTE/index2.html
* ExtJS (commecial qooxdoo-like framwork?)
https://examples.sencha.com/extjs/6.0.0/examples/admin-dashboard/

Is it possible to make an admin dashboard like the above with qooxdoo ?

**Comment by cboulanger** [comment]
Hello, thanks for your interest in Qooxdoo. Qooxdoo does not offer something like this out of the box, but please ask this question in our community chat room at https://gitter.im/qooxdoo/qooxdoo - maybe other users of Qooxdoo have already built an admin panel that they are ready to share.
