### ISSUE TITLE
Sorting a table containing empty fields (null, undefined) does not work and produces holes

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10014]
If I try to sort a table contining empty fields (null, undefined) by clicking on the column header, the empty fields appear as holes scattered around and not all in the end or in the beginning.

![image](https://user-images.githubusercontent.com/6432001/88290259-c48fc900-ccf6-11ea-9b65-1cd7daddb348.png)

see playground example:
https://tinyurl.com/y68bob5f

The reason is that the comparison of null,undefined with other values in the default comparator:

https://github.com/qooxdoo/qooxdoo/blob/97418ba9a62fed5eb00efbbac5190fdde66ed24b/framework/source/class/qx/ui/table/model/Simple.js#L74

is not symmetric, so the native sorting algorithm produces garbage:

```js
"abc" > undefined == false     —>   return -1
undefined > "abc" == false     —>   return -1
```

This is similar to #3378 but for non-numeric columns

**Comment by cboulanger** [comment]
@adrelino Thanks for reporting. Can you provide a PR that fixes this?
