### ISSUE TITLE
qx.ui.tree.VirtualTree: method isShowTopLevelOpenCloseIcons always returns true and ignores property showTopLevelOpenCloseIcons

### ISSUE THREAD

**Issue by ofilippov** [qooxdoo/qooxdoo#10018]
**Describe the bug**
Class `qx.ui.tree.VirtualTree` has property:
```
showTopLevelOpenCloseIcons :
{
  check : "Boolean",
  init : false,
  apply : "_applyShowTopLevelOpenCloseIcons"
}
```

And it also has a method:
```
// Interface implementation
isShowTopLevelOpenCloseIcons : function() {
  return true;
}
```

This method should return correct property state.

**Expected behavior**
Method `isShowTopLevelOpenCloseIcons` of class `qx.ui.tree.VirtualTree` should return the same value as a method `getShowTopLevelOpenCloseIcons`

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/10019
