### ISSUE TITLE
Spinner focusout with DateField

### ISSUE THREAD

**Issue by pazalejandro** [qooxdoo/qooxdoo#10012]
If the next object to the Spinner is a DateField the value is not updated. Now if for example the following is a TextField it works correctly.

Here is an example:
https://tinyurl.com/yak4pv42

Edit:
If you focus inside the Spinner and enter a number and then press TAB and the next object is a DateField, the value is not updated (If the next object is a DateField).
If you do the same in the next Spinner, it works fine since the next object is a TextField.
This happens if the value of the Spinner is entered by keyboard.

**Temporal Fix:** If the liveUpdate property of the TextField inside the Spinner works fine.

Here is a clearer example with a Label: https://tinyurl.com/y7vr2kds
Excuse my English, I use Google translate. I speak Spanish.

**Comment by goldim** [comment]
I can't reproduce the issue and didn't get feedback from the author.
