### ISSUE TITLE
Trees grow when expanding nodes instead of showing scrollbarX

### ISSUE THREAD

**Issue by marc-rs** [qooxdoo/qooxdoo#10028]
**Describe the bug**
Using the new qooxdoo 6.0.0 and there is an important change in the Trees that is blocking us.
In the previous version when the content of the tree was wider than its parent container the scrollbarX was displayed, now when you expand one node and the content grows, the tree is taking more space instead of showing the scrollbarX.
Fixing the width of the tree wouldn't be a solution because we want the tree to take all the available space of its parent container but without pushing the rest of the siblings when expanding nodes.

**To Reproduce**
Please take a look at the example [https://tinyurl.com/y5ergph8](https://tinyurl.com/y5ergph8)

**Expected behavior**
In previous versions, using the example, the tree grew taking all the available parent container's space but when its nodes were expanded, the tree did not grow, if the size required by the nodes was greater than the tree's one, the scrollbarX appeared.
With Qooxdoo 6.0.0 the behavior has changed, now the tree is growing taking more space from the parent container.

**Screenshots**
the playground example reproduces the problem

**Desktop (please complete the following information):**
 - Browser : Happens in Firefox & Chrome regardless the version.

**Additional context**

**Comment by cboulanger** [comment]
I can confirm the bug - the behvior is different to when [running the code in the v5.0.2 playground](https://tinyurl.com/y529ohe9).

**Comment by derrell** [comment]
The way to do that, now, is to use a `qx.ui.container.Scroll` to enclose the tree, as shown here:

https://tinyurl.com/y5lcrqva

**Comment by derrell** [comment]
In fact, you don't even need the Scroll container. Just setting `width` and `maxWidth` in the original playground sample, as shown here, works too. https://tinyurl.com/y3tmhapq

**Comment by marc-rs** [comment]
The workaround (setting a fixed width/maxWidth) does not our needs. The previous version of the tree could be used in panels with dynamic size (splitters, etc, ...) and the tree grew according to the available space of the parent panel. The scroll has the same problem, you have to define a width if you want to have a "similar" behavior.
If you compare the example in the playground of both version you can see what I mean.

**Comment by derrell** [comment]
The commit that caused this issue was:
```
commit 3a444339a44f1c72a5fa824cdfe6b5b8c12a8d01 (HEAD, refs/bisect/bad)
Author: Martijn Evers <martijn4evers@gmail.com>
Date:   Mon Aug 14 10:37:17 2017 +0200

    Fixed dimensions (width and height) of AbstractScrollArea (issue 9351) (#9355)
    
    * [Improved] moved practical logic into constructor so it's theme independent
    
    * [Changed] default dimensions of abstract scroll area
    
    * Partly revert jsdoc change and corrected initial scroll area width
    
    I'm trying this changes because I'm to curiuos to see if the scroll related tests stop failing.
    
    * [Fixed] default dimensions of ui.form.List are missing
    
    * [Improved] virtual.core.Scroller and form.List dimensions
```
I haven't yet looked into whether there is something we can do to resolve it, as this is a low-level change...

**Comment by derrell** [comment]
So the significant change there was in the underlying AbstractScrollArea that Tree extends. That change was made to solve another problem (#9351). The commit that changed the behavior removed setting `width: 100, height: 200`. To regain the original behavior in this example's tree, simply defined a `width` property, as done in this example: https://tinyurl.com/y3mpc6gg

**Comment by johnspackman** [comment]
I think this code https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/core/Widget.js#L1218-L1220 is the cause of the effect - what happens is that if no width is provided (ie `width === null`, as opposed to zero) then the widget presents the width of it's children as the desired width.  

When you expand a node in the tree, the content of the tree gets wider because the nodes are wider - and because there isn't an explicit width, that line of code in Widget.js says that it *needs* the width for its widest child.

IMHO anything that has scrollbars needs to set a width and height of zero, indicating that it does not have a preferred width and preventing the Widget code from asking for the width of its children.
