### ISSUE TITLE
Question: how to: Qooxdoo Frontend with .NET Backend

### ISSUE THREAD

**Issue by CanadianHusky** [qooxdoo/qooxdoo#10057]
Hello,

I am impressed by the front end contols that I tested at http://qooxdoo.org/qxl.demobrowser/ and http://qooxdoo.org/qxl.widgetbrowser/

Especially the performance of the table with 10,000 rows proves to me that qx framework is industrial strenght. 
The 'Desktop like' behaviour and UI options of the Windows, Tabs and Forms of the qx controls is exactly what many business users of traditional Winforms Desktops apps appreciate. Well done.
I am a seasoned backend/.NET/Desktop/Winforms Developer, looking for a suitable Web-UI Frontend Framework for a new Project.

I have a massive existing .NET backend that can produce XML, JSON, or plain String responses to incoming HTTP Requests (with parameters in the querystring if needed), returning them as an HTTP Response.

My question is simple, can qx framework be used to interact with and be used as a frontend to the .NET Backend ? If so, can someone point me into the right direction or to a 'hello world' style app. I am willing to make adjustment to the .NET backend if needed to satisfy the communication protocol requirements of qx.

I suspect the documentation at https://qooxdoo.org/documentation/#/communication/ is the primary source of information for server side communication. As far as I can see, Rest, Remote IO, Request IO and JSON RPC calls are all fully supported by qx, even with databinding options to qx widgets and controls. 

Can someone with experience comment if a .NET backend can communicate in a healthy way with a qx frontend and ideally provide a link to a simple 'hello world' app ?

In particular, I want to do standard things like
1- Click a button in the qx webform ( qx.ui.form.Button) and execute a function/method in the .NET backend, display the results in a Label on the Web UI
2- Load Data from the .NET Backend into the qx Web Table, make edits on the Webform and push the changes back to the .NET backend
 
thank you kindly,

**Comment by cboulanger** [comment]
Hi @CanadianHusky, qooxdoo is backend-agnostic, so the technology used on the server does not really matter, as long as it returns data using the protocol the client expects. You are right that https://qooxdoo.org/documentation/#/communication/ is the point of reference. Unfortunately, I don't know anything about .NET, but I am sure you find plenty of JSON server implementations. I suggest you ask in our chat (https://gitter.im/qooxdoo/home) to get in contact with people who are using .NET...

**Comment by CanadianHusky** [comment]
Thank you, that is helpful. 
Dankeschön
