### ISSUE TITLE
TreeVirtual resets selection upon setData()

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo#10064]
There's likely a couple of things here, but they're related so we'll see how the discussion goes. 

In the SimpleTreeDataModel, in the `setValue()` method, there is a call to [`setData()`](https://github.com/qooxdoo/qooxdoo/blob/9cd0b1d89f14f3060b07d0192ed177abc78ae86f/framework/source/class/qx/ui/treevirtual/SimpleTreeDataModel.js#L393) which basically rebuilds the data from the ground up and once complete then attempts to re-select what was previously selected but does not succeed. The failure to reselect can be seen in this [Demo](https://tinyurl.com/y5ntk3pf) if you select multiple rows and hit the refresh button. 

Removing the `setData()` and adding an update to the private `_rowArr` in `setValue()` seems like it should be enough to satisfy that the value has changed.  
I wondered if you knew why the `setData()` call might have been necessary in this position? 

The reason for asking the question is that we have the need to select a range of rows, edit a cell and then propagate the changed value across the selected rows, something we already do for tables. The presence of the `setData()` is resetting the selection when we handle the `dataEdited` event.  
In the meanwhile I have a custom dataModel that omits the `setData()` which seems to be working OK at the moment.

**Comment by derrell** [comment]
That's probably my code (from ancient history). I can try to figure out why it does it the way it does. It might be easiest for me to review if you were to PR your changed version. Then I can try to see exactly what `setData` does that your code does not, and ensure that nothing else is likely broken by it. Are you able to PR that change?

**Comment by rad-pat** [comment]
Yeah, I can make a PR definitely, I don't currently have a fix for the selections being reset upon `setData`,  but I do for making the `setValue` not call `setData`.

**Comment by rad-pat** [comment]
Fixed by #10065
