### ISSUE TITLE
Rename or delete "documentation" folder

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#10081]
As discussed in https://github.com/qooxdoo/qooxdoo/issues/9773 and on Gitter, something needs to be done about the "documentation" folder which sits arkwardly in our code tree. 

Since qooxdoo v5 will support the old generator, there are good reasons to leave it, although in this case it should be renamed to "documentation_v5"

On the other hand, the documentation is in RST-Format, which is hard to read and to navigate. It would make much more sense to simply add  a link to https://archive.qooxdoo.org/5.0.2/  to the readme. If people are interested in the .rst sources, they can go to https://github.com/qooxdoo/qooxdoo/tree/branch_5_0_x/documentation , which we can also link to.

In sum, I argue to remove the folder and update the readme with links to the legacy docs.

**Comment by oetiker** [comment]
yes kick it!

**Comment by oetiker** [comment]
the reason I noticed that it is still here is because recently someone actually patched something in there ...

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo/pull/10082
