### ISSUE TITLE
Semantic Releases

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#10101]
Starting with 6.0.0, we'd like to switch to using [semantic-release](https://github.com/semantic-release/semantic-release) to manage releases to npmjs.  This issue is to describe how that will work and discuss the options.

Semantic-release relies on the commit messages to determine how to increment the version number; for example, a comment with "fix:" will only increase the patch number (ie the third digit).

It requires that we have at least one branch for releases, and we would also create various "N.x.x" or "N.N.x" branches (where "N" is an actual number but "x" is the letter "x") - for example after we have gone live with v6, we could create a "6.0.x" branch to track back ported bug fixes

If `master` is our release branch, then it means that every PR will cause a new release, which has its benefits for some projects but means that if there are a series of breaking changes one after the other, we would have a proliferation of version numbers.  This is something that we are planning, ie the very first PR is likely to be to delete the generator (a breaking change), meaning that we would immediately be pushing 7.0.0 as a release.

Alternatively, `master` can be a beta channel and we would add a new branch called `latest` which is for releases.  If we added this now (ie before we go live with 6.0.0) this would mean that every push to `master` would result in a release called `6.0.0-beta.0`, `6.0.0-beta.1`, etc and then when we are ready to release 6.0.0 we would just merge the `master` branch into the `latest` branch, and semantic-release would create the 6.0.0 release.  Subsequent pushes to `master` would result in `7.0.0-beta.0` etc

If we wanted to make a bugfix and release 6.0.1 we would have the option of just pushing a commit to the `latest` branch - semantic-version would automatically calculate the version and release it to npmjs.  AIUI we do not need to create a branch `6.0.x`, unless we wanted to support the 6.0 as well as 6.1 simultaneously.

This is effectively what we have now, but with a different naming convention for betas, plus the beta releases will be put into a separate "beta" channel on npmjs.

A complication here is that the compiler and framework are heavily tied together but have different repos; in our [qooxdoo/deployment](https://github.com/qooxdoo/deployment) repo, we checkout the compiler and the framework, compile the compiler with itself and the new framework, compile the framework and release it, and then publish the compiler with a dependency on the latest framework.

Every time there is a push to the compiler's `master` *or* the framework's `master`, there is a version bump to the compiler *and* to the framework - but sometimes there are changes that needs be pushed to both compiler and framework before a release is successful.  To avoid polluting the public namespace, we can keep it so that `master` on both repos alway publishes automatically via a semantic-release workflow, but `latest` needs to have the workflow manually triggered.

**Comment by johnspackman** [comment]
Also there is a working example of this in the [qooxdoo/qxl.test1](https://github.com/qooxdoo/qxl.test1) repo, the interesting files are `.releaserc` and `.github/workflows/release.yml`

**Comment by johnspackman** [comment]
Another thought is whether we should synchronise the compiler and framework version numbers - but I don't know that we would be able to get semantic-release to do that

**Comment by hkollmann** [comment]
What's about integrate the compiler into the framework after release of 6.0?

**Comment by johnspackman** [comment]
> What's about integrate the compiler into the framework after release of 6.0?

That would solve a lot of problems in the release.  It's been a bit of a nightmare to get npm to make them work together as separate releases.

The reason we kept them separate was so that the compiler could go through a shorter review/release cycle, that didn't require a full 5+ approvals, especially as many of core team were distanced from the specifics of the code.  But whether that's really appropriate any more I'm not sure - the compiler is a critical component, and once we get to v7 beta the generator will no longer work even if we wanted it to.

**Comment by cboulanger** [comment]
> The reason we kept them separate was so that the compiler could go through a shorter review/release cycle, that didn't require a full 5+ approvals, especially as many of core team were distanced from the specifics of the code.

The shorter release/review cycle can be achieved differently, I think, with a GitHub workflow that assigns different reviewers based on the a label (such as https://github.com/marketplace/actions/auto-assign-action). 

If integrating the codebase would make things easier, I am all for it!

**Comment by cboulanger** [comment]
What about 

- master -> v7.0.0-alpha.XXXXXX on NPM (no breaking changes allowed (since it would increment to 8), only "feat" and "fix" 
- branch_6_0_0 -> v6.0.x (only "fix: ..." commit messages)

Of course, commits to master could contain all kind of breaking changes, but we "breaking" would mean "breaking v6" - whether they break the current state of master wouldn't be of interest as long as we are not in "beta" mode.

**Comment by cboulanger** [comment]
This would be in some way a misuse of the semantic versioning model (since we don't use the breaking feature to automatically upgrade the major version). It is not only that we are attached to ["romantic versioning"](https://github.com/romversioning/romver) 😄 - but being on an "alpha" channel, breaking means something different, I think.

**Comment by johnspackman** [comment]
that's how it would work, but it's just that the naming convention is different with semantic-release - so instead of v7.0.0-alpha.XXXXX it would be 7.0.0-alpha.0, 7.0.0-alpha.1, etc - and instead of branch_6_0_0 it expects 6.0.x

also, when we're on a prerelease channel (eg "alpha" or "beta") then the rules about breaking changes incrementing the semver number do not apply - so if `master` is a "beta" channel, then pushing a minor fix or a major breaking change would only increment the version from 7.0.0-beta.0 to 7.0.0-beta.1.  However, when `master` is merged into `latest`, `latest` would still be on 6.0.0 ... so all of those accumulated changes in master would be analysed and if there is a breaking change then `latest` would be released as 7.0.0

At that point I think we have to merge `latest` back into `master` so that the `package.json` version number is updated, and future changes to `master` would mean that we're issuing 8.0.0-beta.0 etc

**Comment by johnspackman** [comment]
the key concepts in semantic-release are that branches are either "release" (eg `latest`) or prerelease (eg in our case, `master`); and then that there are channels (which are like Google Chrome canary vs dev vs release) which we would just choose "beta" and the default (which is the normal public release channel)

*If* we need to have a separate branch for backporting fixes, then we would create `6.0.x` branch or `6.x.x` branch (and not have a leading "v" or anything after the number)

**Comment by cboulanger** [comment]
Sounds good to me. I think we certainly need a 6.0.x branch to fix stuff, but there won't be any 6.1 branch for sure, since we invest all our energy in v7. 

So if I understand you correctly, we would have

- "master" (we can do whatever we want) -> automatic release of 7.0.0-beta.X, 7.1.0-beta.X, etc. 
- "latest" (we must be very careful what to merge manually from master) -> automatic release based on commit tags, will result in version upgrades , will be 7.0.0 once we release that, 7.0.1, 7.1.0 etc. , will be merged back to master once after releases
- "6.0.x" - we merge cherry-picked bugfixes from master or fix legacy stuff if needed

Did I get this right?

**Comment by cboulanger** [comment]
This would be enforced by a workflow which would reject invalid commit messages (such as breaking changes to the 6.0.x branch)

**Comment by johnspackman** [comment]
> So if I understand you correctly, we would have...Did I get this right?

Yep :)

> This would be enforced by a workflow which would reject invalid commit messages (such as breaking changes to the 6.0.x branch)

Yes; it is up to us whether we have a branch called 6.x.x or 6.0.x (and 6.1.x etc if we needed to), but I think that it would be easiest to stick to 6.x.x because then we would be free to add anything to 6 at any time.  With a name like 6.x.x it will recognise that breaking changes are an error and the workflow will fail; if that happens, the author would have to fix that by amending the commit and the comment, and then pushing the revised commit history with `git push -f`.  IE we can't have one commit that says "breaking change" followed by a second commit which says "undid the breaking change" because semantic-release will simply see the first message and stop.

**Comment by cboulanger** [comment]
Thinking further about the workflow: 

"fix:" commits could always be merged from "master" to "latest", triggering an automatic release

but: when merging "latest" back into "master", what version does it get? master@7.0.0 -> "fix:" -> latest@7.0.1 -> master@7.0.1-beta.0 ? Because normally, "beta" would be appended to the version it leads up to- here it would be the other way round. I don't mind - it makes sense because you *just don't know* whether the next commit will be a fix or a feature.

**Comment by johnspackman** [comment]
that won't work - what if the "fix" is for a bug in a v7 feature or v7 breaking change?  And as the whole of the v7 in master will start with a breaking change, all amends to 6.0.0 would have to be cherry picked

**Comment by cboulanger** [comment]
For posterity, here is the explanation by @johnspackman on Gitter:

> The way it works is that latest is on 6.0.0 and then we merge that back into master; when we commit a breaking change to master, because we have told semantic-release (in the config file) that master is a prerelease branch, it knows that (a) master needs a new major version number and (b) to give it the beta suffix. but also, that means that future breaking changes do not change the major number, because it’s all stil in beta. so when you merge master into latest, it just re-reads all the commit messages and sees that there is a breaking change - this forces an update to a 7.0.0 in latest channel. We then merge latest back into master so that the package.json is nicely up to date, and the next commit means we go onto a version number based on whether we’re making a fix or feature or breaking change, but it will still have the -beta.X suffix
