### ISSUE TITLE
Refining the `centerOnAppear` property of `qx.ui.window.Window` does nothing

### ISSUE THREAD

**Issue by voger** [qooxdoo/qooxdoo#10116]
**Describe the bug**
When we inherit from `qx.ui.window.Window` and refine the property `centerOnAppear` like this

```javascript

properties: {
  centerOnAppear: {
    refine: true,
    init: true
  }
},
```

and then open that window, it doesn't center

**To Reproduce**
Here is the code from a playground example I prepared

```javascript
// Document is the application root
var doc = this.getRoot();

// this centers
const win1 = new qx.ui.window.Window("Win 1");
win1.setCenterOnAppear(true);
doc.add(win1);
win1.open();

// this doesn't center
qx.Class.define("MyWin", {
  extend: qx.ui.window.Window,
  
  properties: {
    centerOnAppear: {
      refine: true,
      init: true
    }
  }
});

const win2 = new MyWin("Win 2");
doc.add(win2);
win2.open();
```
https://tinyurl.com/y2cnw39j

**Expected behavior**
Both windows should be centered

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser: Chrome, Firefox
 - Version: Version 88.0.4324.96 (Official Build) (64-bit), 85.0 (64-bit)

**Additional context**
I added a line in the `qx.ui.window.Window` class constructor

```javascript
    // Initialize centering on appear
    this.initCenterOnAppear();
```
and this solved the problem. 

Is this behavior intentional or is this a bug?

**Comment by derrell** [comment]
This actually points to a somewhat more general issue. Whenever `refine : true` is used, we probably need code that sets the new `init` value. Calling `initCenterOnAppear` (or, the `init*` method in general) is intended for times when you can't initialize in the property definition, e.g., when initializing to a reference type. Shen initializing to a static type, that shouldn't be necessary.

**Comment by goldim** [comment]
@voger as @derrell said it is common issue. And other props behave the same way if there exists special `apply` method.
