### ISSUE TITLE
Slider - wrong PageDown/PageUp behaviour

### ISSUE THREAD

**Issue by grykar** [qooxdoo/qooxdoo#10121]
**Describe the bug**
In class qx.ui.form.Slider PageDown keyboard key increases slider value and PageUp keyboard key decreases slider value

**To Reproduce**
1. just use keyboard keys PageDown/PageUp and look at slider behaviour

**Expected behavior**
PageDown keyboard key decreases slider value and PageUp keyboard key increases slider value

**Additional context**
To fix bug modify function _onKeyPress in file \node_modules\@qooxdoo\compiler\node_modules\@qooxdoo\framework\source\class\qx\ui\form\Slider.js  
traded places 'case "PageDown":'  and  'case PageUp":'

**Comment by rommni** [comment]
Just a link to a playground example : https://tinyurl.com/y5u4rmvd

The behavior seems good for the vertical slider, it seems that only the horizontal one have a problem.
I'll try to have a look to that, during th day.

**Comment by rommni** [comment]
It seems that effectively the advices on this is to increase the value when the slider is horizontal: https://www.w3.org/TR/wai-aria-practices-1.1/#slider

It seems that it is too a good practice to allow up/down button on horizontal slider to increase/decrease the value, it's not the case currently. Will try to do a PR however we can discuss of the solution chosen, I think i'm going to:

- Make PageUp increase value only when horizontal (don't change behavior for vertical)
- Make PageDown decrease value only when horizontal (don't change behavior for vertical)
- Make up arrow increase value when horizontal (don't change behavior for vertical)
- Make down arrow decrease value when horizontal (don't change behavior for vertical)

**Comment by rommni** [comment]
After more research the main problem on my precedent reflexion is that the more logic behavior is not what we currently have, the slider should have greater value when it goes up (once it is sais it seems totally logic) currently when you go down you increase the value. (https://tinyurl.com/y46c7uav)

If we change that it solves all the problem and then the behavior is the same on the 2 orientation, if you page down you go down so you decrease the value, and if you go up you increase the value.

I could do the change however, it changes the current behavior of all the Vertical Sliders, so maybe we will have to be careful with this change.

**Comment by johnspackman** [comment]
Im reopening this because I think that the PR is wrong - please see my comment https://github.com/qooxdoo/qooxdoo/pull/10122#issuecomment-782054875

**Comment by johnspackman** [comment]
reopened in error, sorry for the noise!
