### ISSUE TITLE
Not able to add space on contenteditable

### ISSUE THREAD

**Issue by paragasu** [qooxdoo/qooxdoo#10130]
**Describe the bug**
qooxdoo somehow disable the event for space. Modern js editor for example quill, editorjs make use of contenteditable
in order for it to work. But since qooxdoo currently seems to be blocking user from key in space character. This editor
not able to work properly

**To Reproduce**
Here is a minimal playground code to reproduce this problem https://tinyurl.com/y3xbpckt

**Expected behavior**
Type "Hello", space then "World" should produce "Hello World" but the result is "HelloWorld"

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser : firefox, chrome & safari
 - Version latest version

**Comment by level420** [comment]
@paragasu @romni please check this playground sample where I've integrated the quilljs editor:

https://tinyurl.com/yyda8ptu

In this sample there is no problem typing space in the quills editor. I'm useing ckeditor in a similar way and had never any problems tying spaces there.

**Comment by level420** [comment]
tested to work on windows 10 with current IE 11, chrome, firefox and on macos 11.2 with current safari, chrome and firefox

**Comment by paragasu** [comment]
> @paragasu @romni please check this playground sample where I've integrated the quilljs editor:
> 
> https://tinyurl.com/yyda8ptu
> 
> In this sample there is no problem typing space in the quills editor. I'm useing ckeditor in a similar way and had never any problems tying spaces there.

this is awesome. thank you
