### ISSUE TITLE
COMPILER: move to dart-sass

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#10146]
node sass is not longer supported: https://www.npmjs.com/package/node-sass

**Comment by hkollmann** [comment]
should be backported to 6.0

**Comment by johnspackman** [comment]
I just ported something to it and have to go back - see https://github.com/dart-lang/sdk/issues/27979#issuecomment-704462646 which says that it gets worse with jsdom (which we use)

**Comment by hkollmann** [comment]
I have the same issue as i tried to ported it..
