### ISSUE TITLE
COMPILER: Avoid building of packages not used by main application

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10188]
**Describe the bug**
Even though the `provides.application` entry of the package's Manifest.json is not set, e.g. in https://github.com/adrelino/qxex/blob/8326e3b20fa0533490b53b3e86ae7a33e8c315d3/Manifest.json, the compiler copies the API viewer to the main app using the package.

**To Reproduce**
```
npx qx pkg update
npx qx pkg install adrelino/qxex@1.0.0
npx qx compile
```

**Expected behavior**
`compiled/source/apiviewer` folder is not created

**Comment by hkollmann** [comment]
But it's  set in qxex Manifest.json. So it should be published. We dicussed this here https://github.com/qooxdoo/qooxdoo/issues/10187 and did a change here .
