### ISSUE TITLE
Last item in scroll container not always visible

### ISSUE THREAD

**Issue by sknick** [qooxdoo/qooxdoo#10216]
**Describe the bug**
I believe this is likely a bug in the layout engine in Qooxdoo, but you can see it exhibited in the Qooxdoo API viewer.

**To Reproduce**
1. Go to http://qooxdoo.org/qxl.apiviewer
2. Click the search option on the left and type in a search term like "transition".
3. Scroll to the bottom of the results on the left. Note that the last item cannot be completely scrolled into view.

**Screenshots**
![image](https://user-images.githubusercontent.com/6498506/122046688-76ffcd00-cd9c-11eb-985c-fadfe9361787.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Version: Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by level420** [comment]
could not reproduce with Chrome 91.0.4472.106, Firefox 89, Edge 91.0.864.48, Internet Explorer 11 on Windows 10 2019 LTSC and Safari 14.1.1 on macos Big Sur 11.4

**Comment by sknick** [comment]
![image](https://user-images.githubusercontent.com/6498506/122049868-22f6e780-cda0-11eb-8b7e-889176ea23bb.png)

**Comment by goldim** [comment]
@sknick I can't reproduce it neither Windows 10 nor Ubuntu 22.

**Comment by sknick** [comment]
No longer able to reproduce.
