### ISSUE TITLE
Private member in a mixin can overwrite a private member in class it's mixed into

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#10222]
In my app, I've found that in the build version, the `__Property` member of `qx.core.Object`  is found to be null in the destructor, so when it goes to dereference `$$store`, it crashes.

I have tracked down the cause of this problem to be that qx.core.Object uses mixin qx.core.MObjectId, and in the build version, both `qx.core.Object`'s `__Property` member and `qx.core.MObjectId`'s `__ownedQxObjects` member are assigned private variable name `__P_26_0`. It looks like the order of instantiation in Class would have `qx.core.Object`'s members list initialized first, and then mixins are loaded so their members lists are initialized. What appears to be happening is that `qx.core.Object`'s `__Property` (`this.__P_26_0`) is initially assigned `qx.core.Property` as expected, but when the `qx.core.MObjectId` mixin is loaded, its `__ownedQxObjects` (again, `this.__P_26_0`) is assigned `null`. It looks to me like it's not feasible/allowable to ever assign the same private variable name like `__P_26_0` to a mixin as to a class, since privates are expected to be unique even between mixins and the classes they're mixed in to.

I confirmed this is the cause of the crash problem by manually changing, in `compiled/build/index.js`, all occurrences of `__P_26_0` within the mixin definition to have a different name. The problem then went away.

**Comment by derrell** [comment]
New information. `qx.core.Object` starts out being assigned prefix `__P_14_` by `qx.tool.compiler.Analyser[4-0]` and `qx.core.MObjectId` is given `__P_26_`... but later on, a different analyser, `qx.tool.compiler.Analyser[3-0]` shows prefix `__P_26_` assigned to `qx.core.Object`...

**Comment by derrell** [comment]
Ah ha! There are two analysers running in parallel, because I have two applications being built. If I comment out everything about the second application in compile.json, only one analyser shows up, and unique private variable names are generated. The question becomes, why are both of the two analysers' privates analyser databases getting used to generate one of the applications' index.js?

The problem does not seem to affect the other app. There are separate prefixes for `qx.core.Object` and `qx.core.MObjectId` there. (The overridden prefix in the app that has the problem, `__P_26_`, is in fact used for `qx.core.Object` in both apps.)

**Comment by derrell** [comment]
The problem occurs when I run `npx qx deploy`. To summarize the problem, the node app ends up with the same mangled private name in two classes, in the resulting index.js (qx.core.Object and qx.core.MObjectId). The node app and the browser app end up with the same mangled private prefix for qx.core.Object, but only the node app has that private prefix shared with qx.core.MObjectId in its index.js. 

My compile.json:

```
{
  "$schema": "https://qooxdoo.org/schema/compile-1-0-0.json",
  "targets": [
    {
      "type": "source",
      "outputPath": "output/source",
      "bundle": {
        "include": "qx.*"
      },
      "application-types": [
        "browser"
      ],
      "addCreatedAt": true,
      "environment": {
        "dsrc.target": "source"
      },
      "babelOptions": {
        "targets": {
          "chrome": "91",
          "firefox": "89"
        }
      }
    },
    {
      "type": "build",
      "outputPath": "output/build",
      "addCreatedAt": true,
      "deployPath": "deploy",
      "application-types": [
        "browser"
      ],
      "environment": {
        "dsrc.target": "build"
      }
    },
    {
      "type": "source",
      "outputPath": "output/source",
      "bundle": {
        "include": "qx.*"
      },
      "application-types": [
        "node"
      ],
      "addCreatedAt": true,
      "environment": {
        "dsrc.target": "source"
      },
      "babelOptions": {
        "targets": "node >= 14"
      }
    },
    {
      "type": "build",
      "outputPath": "output/build",
      "addCreatedAt": true,
      "deployPath": "deploy",
      "application-types": [
        "node"
      ],
      "minify": "off",
      "environment": {
        "dsrc.target": "deploy"
      },
      "babelOptions": {
        "targets": "node >= 14"
      }
    }
  ],
  "defaultTarget": "source",
  "locales": [
    "en"
  ],
  "locales": [
    "en"
  ],
  "environment": {
    "qx.icontheme": "Tango"
  },
  "applications": [
    {
      "class": "dsrc.vided.Application",
      "theme": "dsrc.vided.theme.Theme",
      "name": "dsrc.vided",
      "bootPath": "source/boot"
    },
    {
      "class": "dsrc.coproc.Application",
      "theme": "",
      "name": "dsrc.coproc",
      "type": "node",
      "include": [
        "qx.core.BaseInit"
      ],
      "exclude": [
        "qx.bom.Selector",
        "qx.bom.client.Html",
        "qx.event.handler.Pointer",
        "qx.event.handler.Gesture",
        "qx.event.handler.PointerCore"
      ]
    }
  ]
}
```

**Comment by johnspackman** [comment]
The problem is that there are two source and two build targets, and they share the same output directory.  This means that the two separate target compilations will overwrite each other's output.

The PR in the fix detects this and outputs a warning.

The solution is to change the targets in `compile.json` so that `outputPath` is (eg) `output/source-node` and `output/source-browser`

**Comment by derrell** [comment]
Thanks @johnspackman. I guess that makes sense.
