### ISSUE TITLE
Move qx.io.remote into package

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#10306]
`qx.io.remote` is an older implementation of communication protocols. It has been superseded by `qx.io.request` which is a more systematic re-implementation (see https://qooxdoo.org/documentation/6.0/#/communication/) and on which new development will be based. In v7, `qx.io.remote` will be removed from the core framework and published as a package. This allows easy re-installation via `qx pkg install deprecated.qx.io.remote` for applications that rely on `qx.io.remote`. 

- [x] Publish `qx.io.remote` as package `deprecated.qx.io.remote`
- [ ] Add deprecation warning to compiler (#10309)
- [x] Remove `qx.io.remote` from framework

**Comment by cboulanger** [comment]
see also #10305

**Comment by cboulanger** [comment]
https://github.com/qooxdoo/deprecated.qx.io.remote

**Comment by hkollmann** [comment]
what's about qx.io.request? Should'nt we move this to deprecated too?

**Comment by cboulanger** [comment]
No, that's the current API for HTTP requests - we need that, it's the basis of any HTTP i/O in the framework 😄

**Comment by cboulanger** [comment]
Done: https://github.com/qooxdoo/deprecated.qx.io.remote - closing

**Comment by hkollmann** [comment]
It's not ready. qx.io.remote has to be removed

**Comment by hkollmann** [comment]
Now it's removed
