### ISSUE TITLE
`qx lint` does not honour the `-f` format flag

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo#10371]
With Qooxdoo v7 Beta 10
When running command `qx lint -f=checkstyle`, the output is not the XML checkstyle format as expected.

This was running fine with Qooxdoo 6
Looking at the code, it's likely that the cause it that it is forced to compact mode in the case when there are many errors. However, we are expecting to parse the checkstyle format in our Jenkins build to give us a lovely chart.
https://github.com/qooxdoo/qooxdoo/blob/master/source/class/qx/tool/cli/commands/Lint.js#L162..L164

**Comment by hkollmann** [comment]
Could you check if this is true with current version: 
// If there are too many errors, the pretty formatter is appallingly slow

**Comment by rad-pat** [comment]
When the comment was made, it looks like it was reporting 51,000 `Errors` in the Qooxdoo codebase (with --warnAsError flag set https://github.com/qooxdoo/qooxdoo/pull/10123). Running on the Qooxdoo codebase currently, there are 1234 errors found. This takes ~25s to run locally for me with any of the output formats selected (and those lines of code removed to prevent forcing to compact mode).

**Comment by hkollmann** [comment]
What's about a PR to change?

**Comment by rad-pat** [comment]
Yep, will do
