### ISSUE TITLE
Silence warnings that modules are automatically `require()`d

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#10404]
From @johnspackman on gitter:

> Currently, when building apps for the browser and the server out of one code base, it is possible to accidentally trigger a class to be referenced which drags in code from qx.ui.* - this typically breaks the server apps at runtime (because defers do things that expect DOM etc)

> It’s also possible to it the other way around
so there is a very crude dxependency anaylsis tool (very crude) because it’s difficult to figfure out which class is dragging in the wrong dependencies

> so we would take the same approach with require -

> ie allow the code to require what it likes (silently) and provide the toolds to figure out which class is causing things to go wrong, if it goes wrong

**Comment by hkollmann** [comment]
done wih #10493
