### ISSUE TITLE
Mobile theming

### ISSUE THREAD

**Issue by eda2z** [qooxdoo/qooxdoo#10422]
Is mobile theming still under development in Qooxdoo v7.1.1? If I browse to the mobileshowcase url I don't see any difference between the Indigo and Flat themes. If I try using qx.Mobile Flat theme as documented in Qoocdoo Mobile I see no difference after compilation.

**Comment by goldim** [comment]
@eda2z there are no new themes for mobile theming in v7.1.1 and higher. All chagnes you may check in this [article](https://qooxdoo.org/documentation/v7.5/#/release-notes.7.0?id=new-features-in-v74)

**Comment by goldim** [comment]
but maybe new packages were published as third party in [package system](https://qooxdoo.org/qxl.packagebrowser/)

**Comment by eda2z** [comment]
I am not looking for a new theme. According to the qooxdoo documentation there should be a flat theme and an indigo theme for mobile apps. If I go to the mobile showcase http://www.qooxdoo.org/qxl.mobileshowcase/ from github and I click on the flat theme I see no difference. If I follow the instructions from the qooxdoo docs about Using qx.Mobile Flat Theme on a mobile app I see no difference from the Indigo theme.

**Comment by goldim** [comment]
I've got your point, check it later, thanks.

**Comment by goldim** [comment]
@eda2z bug confirmed, already did PR. Thanks a lot. Noticed this issue was made half year ago. You could write on gitter if  no response here.

**Comment by eda2z** [comment]
Thanks. I know it is a bug but I did not consider it "major". I just wanted to try and make my several mobile apps look different.

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qxl.mobileshowcase/commit/8ddee292fdad79909a8ab7e1435b8766ab16c088
