### ISSUE TITLE
DateChooser tests duplicate DateField tests

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10463]
**Is your feature request related to a problem? Please describe.**
I checked DateChooser tests and noticed that something is wrong with them.
There are `testRequiredDateChooser `and `testValidDateChooser `tests. They just duplicate `DateField `tests.
I changed `DateField `class on DateChooser and they were failed. I investigated that `DateChooser `doesn't have "invalid" decorator but asserts require it for `DateChooser`.
I suppose the code duplication were on purpose because it is only one difference between `DateField `and `DateChooser `and an author didn't want to write different test code for this case.

**Describe the solution you'd like**
Simple just remove these tests.

**Describe alternatives you've considered**
Or somehow do not apply these asserts for `DateChooser`.

**Additional context**
I am not sure maybe `DateChooser `should have invalid decorator and how it supposed to look like.

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/10475
