### ISSUE TITLE
Tests with getInvalidMessages asserts

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10464]
**Is your feature request related to a problem? Please describe.**
The method `getInvalidMessages` of `qx.ui.form.validation.Manager` returns extra message after validate method call.
For example, if the manager has 3 input widgets then test asserts expect 3 invalid messages but actually there is 4 after the validate call.

**Describe the solution you'd like**
Change expected count of messages in asserts.

**Describe alternatives you've considered**
Or change logic of `getInvalidMessages` to not count extra message of manager.

**Comment by goldim** [comment]
@hkollmann There are tests which fail:

> not ok 374 - qx.test.ui.form.FormValidator:testSyncSelfContained3NotNull - [6.60 ms] - Expected '3' but found '4'!
> not ok 375 - qx.test.ui.form.FormValidator:testSyncSelfContained3NotNullError - [7.60 ms] - Expected '3' but found '4'!
> not ok 378 - qx.test.ui.form.FormValidator:testSyncRelatedWithIndividual - [7.50 ms] - Expected '1' but found '2'!

**Comment by goldim** [comment]
I get these "not ok" tests when run locally `npx qx test` too

**Comment by hkollmann** [comment]
I just try this

**Comment by goldim** [comment]
@hkollmann also you can see them on each PR for example

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/10475
