### ISSUE TITLE
qxWeb.js unintentionally brings all material icons into the build

### ISSUE THREAD

**Issue by gnikolaidis** [qooxdoo/qooxdoo#10478]
**Describe the bug**
qxWeb.js, line 40:

```
 * @asset(qx/iconfont/MaterialIcons/*)
```

**To Reproduce**
Build a new, empty project, look at the resources directory. Material icons are all there.

**Expected behavior**
Just the icons mentioned by user-given `@asset` to be brought in

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/10488
