### ISSUE TITLE
Compile times are becoming excessive

### ISSUE THREAD

**Issue by sknick** [qooxdoo/qooxdoo#10479]
I'm seeing compile times increasing as my Qooxdoo desktop web application grows. It's now about 10 seconds per application, and I have two, so I see compile times of 20 seconds or more.

**Comment by hkollmann** [comment]
Do you use npm modules?

**Comment by sknick** [comment]
In what way?

**Comment by hkollmann** [comment]
using require() and the loaded npm module in your webapp.

**Comment by sknick** [comment]
Not directly, but I do use a forked version of `protoc-gen-qx`, and its use seemed to appreciably increase compile times.

https://github.com/sknick/protoc-gen-qx

If it's useful to you, I'd be happy to temporarily give you access to the RaceDay.watch repo. Just let me know.

**Comment by hkollmann** [comment]
Do you have some browserify messages in you compile log?Von meinem iPad gesendetAm 20.11.2022 um 16:54 schrieb Scott Knick ***@***.***>:﻿
Not directly, but I do use a forked version of protoc-gen-qx, and its use seemed to appreciably increase compile times.
https://github.com/sknick/protoc-gen-qx
If it's useful to you, I'd be happy to temporarily give you access to the RaceDay.watch repo. Just let me know.

**Comment by sknick** [comment]
Nothing in logging.

```
Making applications...
>>> Making the applications...
Writing application raceday
Writing application admin
>>> Compiled 0 classes in 23.597s
Applications are made
```

**Comment by hkollmann** [comment]
Then there is another Problem Any idea wich Part is Slow?Von meinem iPhone gesendetAm 20.11.2022 um 19:03 schrieb Scott Knick ***@***.***>:﻿
Nothing in logging.
Making applications...
>>> Making the applications...
Writing application raceday
Writing application admin
>>> Compiled 0 classes in 23.597s
Applications are made

**Comment by sknick** [comment]
Unfortunately, no. Is there any way to get metrics out?

**Comment by sknick** [comment]
Doesn't appear I have that argument.

```
Unknown argument: browserify
developer@tuf:~/Source/github.com/raceday-watch/raceday/Client/UI/Source$ npx qx --version
7.3.3
```

**Comment by sknick** [comment]
(Note that I specified `--no-browserify`.)

**Comment by hkollmann** [comment]
could you try with version 7.4.0?

**Comment by sknick** [comment]
Wow! That's quite a difference. Compile times are back down to 4 seconds are less now. Good work!

**Comment by hkollmann** [comment]
Then you are using npm packages in some form.

Can we close the issue?

**Comment by sknick** [comment]
Ya, I'm not sure what bearing my use of npm packages has... I'm not explicitly using any that I know of aside from qooxdoo. Regardless, I think the issue can be closed based on my testing so far.
