### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#10494]
There are a couple of minor issues with webfonts which make it confusing to reliably use and load them without having unnecessarily large compiler output

(This issue is in response to a recent question on Gitter and is largely from memory, so there might be some mistakes)

## The problem
Webfonts for icons are specified in `Manifest.json` in the `provides/webfonts` key; eg:

```
  "provides": {
    "webfonts": [
      {
        "name": "MaterialIcons",
        "defaultSize": 32,
        "comparisonString": "e1feef39",
        "resources": [
          "qx/iconfont/MaterialIcons/materialicons-v126.eot",
          "qx/iconfont/MaterialIcons/materialicons-v126.woff2",
          "qx/iconfont/MaterialIcons/materialicons-v126.woff",
          "qx/iconfont/MaterialIcons/materialicons-v126.ttf"
        ]
      },
```

There is a similar process for adding a font in the theme, eg:

```
/**
 * @asset(qx/font/Roboto/*.woff)
 * @asset(qx/font/Roboto/*.woff2)
 * @asset(qx/font/Roboto/*.eot)
 * @asset(qx/font/Roboto/*.ttf)
 * @asset(qx/iconfont/MaterialIcons/*)
 */
qx.Theme.define("qx.theme.tangible.Font", {
  fonts: {
    default: {
      size: 14,
      family: ["sans-serif"],
      color: "text-primary-on-surface",
      sources: [
        {
          family: "Roboto",
          source: [
            "qx/font/Roboto/roboto-v18-latin_latin-ext-regular.eot",
            "qx/font/Roboto/roboto-v18-latin_latin-ext-regular.woff2",
            "qx/font/Roboto/roboto-v18-latin_latin-ext-regular.woff",
            "qx/font/Roboto/roboto-v18-latin_latin-ext-regular.ttf"
          ]
        }
      ]
    },
```

The font filenames have to be specified in both places.  The examples above come from the Qooxdoo framework itself, and they are for different fonts because Roboto is used for regular fonts and MaterialIcons is used for icon fonts.

In order for webfonts to be included as a resource, they also need to be referenced as an `@asset` tag (the second code snippet does that for Roboto and for MaterialIcons)

Webfonts often have version numbering in their filename, and so it is tempting for code outside the Font definition to add `@asset` tags for specific font files to optimise/minimise dependencies; but this leads to `@asset` tags being added which stop working when there is a minor upgrade.  EG `qx.theme.tangible.Image` refers to v50 when the current version is now v126.

```
/**
 * Mapping class for all images used in the tangible theme.
 *
 * @asset(qx/iconfont/MaterialIcons/materialicons-v50.ttf)
 * @asset(qx/iconfont/MaterialIcons/materialicons-v50.woff2)
 * @asset(qx/iconfont/MaterialIcons/materialicons-v50.woff)
 * @asset(qx/iconfont/MaterialIcons/materialicons-v50.eot)
 * @asset(qx/static/blank.png)
 */

qx.Class.define("qx.theme.tangible.Image", {
```

In all, this leads to fonts being specified twice, and sometimes 2 different places - this is confusing and leads to problems where the font might not load for no apparent reason.  The compiler tries to detect this and outputs messages like:

```
Assets required for webfont MaterialIcons are not available in application testtapper, consider using @asset to include qx/iconfont/MaterialIcons/materialicons-v126.eot,qx/iconfont/MaterialIcons/materialicons-v126.woff2,qx/iconfont/MaterialIcons/materialicons-v126.woff,qx/iconfont/MaterialIcons/materialicons-v126.ttf
Assets required for webfont MaterialIconsOutlined are not available in application testtapper, consider using @asset to include qx/iconfont/MaterialIcons/materialiconsoutlined-v101.eot,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.woff2,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.woff,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.otf
Assets required for webfont MaterialIconsRound are not available in application testtapper, consider using @asset to include qx/iconfont/MaterialIcons/materialiconsround-v100.eot,qx/iconfont/MaterialIcons/materialiconsround-v100.woff2,qx/iconfont/MaterialIcons/materialiconsround-v100.woff,qx/iconfont/MaterialIcons/materialiconsround-v100.otf
Assets required for webfont MaterialIconsSharp are not available in application testtapper, consider using @asset to include qx/iconfont/MaterialIcons/materialiconssharp-v101.eot,qx/iconfont/MaterialIcons/materialiconssharp-v101.woff2,qx/iconfont/MaterialIcons/materialiconssharp-v101.woff,qx/iconfont/MaterialIcons/materialiconssharp-v101.otf
Assets required for webfont MaterialIconsDuoTone are not available in application testtapper, consider using @asset to include qx/iconfont/MaterialIcons/materialiconstwotone-v104.eot,qx/iconfont/MaterialIcons/materialiconstwotone-v104.woff2,qx/iconfont/MaterialIcons/materialiconstwotone-v104.woff,qx/iconfont/MaterialIcons/materialiconstwotone-v104.otf
```

An easy fix is to use asset wildcards but this can lead to bloat in the compiler output; if we avoid bloat by not including the `@asset` this leaves the user to find that something does not work out of the box and ask why they are having to add `@asset` tags manually for something that is an entirely internal requirement of the qooxdoo framework.

### Manifest.json only?
IMHO it would be good if webfonts were defined in one place - eg in the `Manifest.json` with a well-known name, and then when a font is used the theme font class simply refers to the font by name (ie definitely no filenames in the code).

When the filenames are *not* in the Manifest.json (eg just the theme's Font class file0 then the compiler cannot see them and it makes it hard for the compiler to automate the dependency tracking.

Defining fonts in Manifest.json with a name could be used for ordinary fonts too - eg `qx.theme.classic.Font` repeats the same `family` array for every single font size, and it could be kind of nice to be able to define this in the `Manifest.json`

### Compiling on demand
`@asset` is the only way that the compiler knows that it needs to include that webfont in the output - but `@asset` only supports filenames, so you can't reliably/easily add a dependency on a webfont.

There could be a new jsdoc tag which refers to the name of the font as published in `Manifest.json` eg `@usefont(MaterialIcons)`

### Online or compiled webfonts?
Some users will prefer to host the webfont on their server with the application, some users will prefer that the app pulls it from a CDN.  

We could recommend that the framework (or a contrib/package author) always use the CDN version, and then make sure that if the app overrides the font definition in `Manifest.json`, then that can be used to instruct the compiler to use local files and include those files in the dependencies which need to be copied into `resources/`

Being able to override where the fonts come from by name means that we don't have to include icon fonts in our distributions, and that it is easy & documented to switch to a commercial version of a font

**Comment by johnspackman** [comment]
Another thought about using `@usefont(MaterialIcons)` is that the compiler can then figure out at compile time whether to include those variants like .woff, .svg, etc that are only needed for certain / old browsers, and this could be controlled by `compile.js`

**Comment by oetiker** [comment]
interestingly enough, as long as the fonts are ina separate qx package things work nicely ... I think https://github.com/oposs/qx-iconfont-tabler

**Comment by johnspackman** [comment]
> interestingly enough, as long as the fonts are ina separate qx package things work nicely ... I think https://github.com/oposs/qx-iconfont-tabler

No sorry, that's the same - in 
[tabler/Load.js](https://github.com/oposs/qx-iconfont-tabler/blob/main/source/class/iconfont/tabler/Load.js#L5-L6) they are included in the compile with an `@asset` and your reference to the Load class causes them to be copied into `resources/`.  It looks like you then access the font by hand

> Couldn't the compiler only complain about the icon font once an icon it is referenced ?

not easy, because that means interpreting the string and deciding that it is a icon reference (unreliable), and then analysing the runtime execution path (impossible in a dynamic language)

> It could also check if the relevant fontfile has been included via an asset call ... if not it could also complain about that.

It does, and that was what @goldim was reporting on gitter earlier, that the compiler detects that the font is not available in the generated `resources/` but is declared as being required.

**Comment by goldim** [comment]
The warnings raise up also when have dependency (external local theme project) and there is web fonts used.
I tried to fix it but unfortunetely, proly I don't know how to handle it. This warning was before 7.4.0:
```
Making applications...
Assets required for webfont FontAwesome are not available in application scada.app, consider using @asset to include resource/bernstein/fonts/fa-solid-900.ttf
```

**Comment by oetiker** [comment]
@johnspackman could we change the aproach for icon fonts to work more along the ways we use normal fonts as fahr as including them into the compile process ? if the iconfont was completely declared in a class, then it could be easily included by mentioning the class ... (as I am already doing in my contrib, except that I can not declare the actual font there, just have the @asset lines).

**Comment by johnspackman** [comment]
Not as it stands - the problem is that in order that we can write code which uses image sources like "@MaterialIcons/rocket_launch/16" or "@FontAwesomeSolid/thumbs-up/16", the compiler must have read the font files to get the symbol mappings
"rocket_launch" or "thumbs-up" and insert them into the resources table during compilation.

This means that the compiler has to be able to reliably identify and read the font files, and if we put that in code we cannot easily (or reliably) identify those font files.

This is why they are listed in Manifest.json and not in a font theme file.

IMHO it is a good optimisation for the compiler to decide, at compile time, which files need to be used based on current target - EG just we can specify that the target only supports modern browsers when transpiling, the compiler should be able to decide to only delivert .ttf and ignore .woff, .svg, .eot etc.  This would require that the code does not specify filenames.

**Comment by oetiker** [comment]
So in a way using @asset lines for iconfonts should not be necessary? Rather some method to tell the compiler which of the available fonts I am going to actually use in my app ?

**Comment by johnspackman** [comment]
> So in a way using @asset lines for iconfonts should not be necessary?

Kind of - but instead of `@asset(path/to/file.ttf)` you would use `@usefont(MaterialIcons)` and then the compiler decide at compile time, which files (or URLs from the font authors CDN)

**Comment by oetiker** [comment]
how about @useIconFont

**Comment by johnspackman** [comment]
> how about @useIconFont

I was thinking about making it so that all fonts are specified - when webfonts are used in themes then there is the same requirement for `@asset` (ie duplicating the filenames) and they would also benefit from compile-time decisions on whether to use URLs or what files to include.

Ultimately, why specify fonts in two places (manifest and theme Font class) and specify dependencies in two different ways (`@asset` and `@useIconFont`), especially when the theme font class doesn't get to benefit from optimisation

**Comment by oetiker** [comment]
@johnspackman normal fonts are specified in the themes fonts.js and work fine, as long as you do not use the theme they don't get included

**Comment by johnspackman** [comment]
> @johnspackman normal fonts are specified in the themes fonts.js and work fine, as long as you do not use the theme they don't get included

I'm not saying that normal fonts do not work?  Also icon fonts work just fine by the same standard?  

The issue is that webfonts (theme fonts *and* icon fonts) make the target output large, and we cannot solve that without making it so that the compiler can be smarter about how it incorporates fonts in the output.  

I'm also saying that it does not make sense to me to only improve the icon fonts handling (essentially creating a new mechanism *just* for icon fonts) when that exact same handling would be really useful for theme fonts also (and simplify the use of fonts in general)

**Comment by oetiker** [comment]
As far as I understand it, a web font, configured in a theme, already work as expected, because the web font only gets loaded and copied if the theme is referenced.

For icon fonts it is different, because, if we have them in the `Manifest.json`, they will get looked at compile time regardless of use in the actual application, because the compiler needs to figure out which symbols are contained. And then later if they are not present in the final application the compiler also complains about their absence.

So if there was a specific clue for the compiler which icon font is actually being used in a particular source file, it could then add only those to toe final application. But maybe I am missing something.

**Comment by johnspackman** [comment]
> So if there was a specific clue for the compiler which icon font is actually being used in a particular source file, it could then add only those to toe final application. But maybe I am missing something.

The source code still has to use `@asset(qx/iconfont/MaterialIcons/*)` which is what adds those files into the resources, ie exactly the same as theme fonts.

but 

(a) when the path changes (eg to a different version, as happens with MaterialIcons) all source files need to be updated with the new paths

(b) the application author may be able to upgrade the font version in the application, but you will still get duplicated files in the resources (eg v50 and v126 in the same app, or because the app author wants to use the commercially licensed version); to avoid duplication of files, all packages, the framework, and the application have to use the same version (and be upgraded simultaneously)

(c) there is no way for the compiler to reduce the number of files based on hints by the application author (eg only support modern browsers and ignore IE11)

(d) there is no way for the user to elect for the online versions delivered by a CDN instead of adding the font files

The above 4 points relate to icon fonts as well as 

> For icon fonts it is different,

icon fonts and theme fonts are exactly the same type of technology, all i'm suggesting is that we make the compiler smarter at optimising the build and do not treat them as different things.  

What's the problem?  I do not understand the objection to making improvements in icon fonts also apply to theme fonts?

**Comment by oetiker** [comment]
Ok, so here is my understanding:

WebFonts: Configured as part of a theme. The compiler generates a bit of css and copies the files. It does not need to understand the content of the font files. If I do not use the theme, the associated webfonts do not end up in my build.

IconFonts: Configured in the Manifest.json because the compiler need to actually read the font to get access to the symbol names (unless a map is provided). To get the fonts into the Build, they have to be copied via @asset lines. If I do NOT put in the @asset lines, the compiler complains since it does not see the fonts (this is what triggered the whole discussion).

So if a new @usefont thing existed which was useable for both webfonts and iconfonts, then the webfonts probably also would have to be configured in the Manifest.json, and then the @usefont would have to be added to the theme.

Correct?

**Comment by johnspackman** [comment]
> So if a new @usefont thing existed which was useable for both webfonts and iconfonts, then the webfonts probably also would have to be configured in the Manifest.json, 

Would **only** be specified in manifest.json

> and then the @usefont would have to be added to the theme.

@usefont would be *instead of* @asset for all fonts

**Comment by sknick** [comment]
Would love a resolution to this so I can start using the newer versions which dramatically increase compilation speeds.
