### ISSUE TITLE
After zooming a checkbox looks blurried

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10506]
**Is your feature request related to a problem? Please describe.**
Checkboxes look blurried after zooming in. It doens't look great imo. 

**Describe the solution you'd like**
In standard themes replace images for checkbox by font-images or vector images.

**Additional context**
![Снимок экрана от 2022-12-15 12-31-10](https://user-images.githubusercontent.com/22189134/207823894-cb8a2897-af83-4b7c-9337-c42f40880e19.png)

**Comment by oetiker** [comment]
yes, this is because this theme does not use iconfonts try the new tangible theme!

**Comment by goldim** [comment]
@oetiker checkboxes couldn't be changed because of backward compatibility, they could?

**Comment by oetiker** [comment]
I think they could be changed, I don't think this would break anything ... note though, that all icons in this theme suffer from the problem of being bitmap icons
