### ISSUE TITLE
native scrollbar in current edge leads to freeze in virtual list scrolling

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#10569]
**Describe the bug**
It seems that for current edge versions (maybe other browsers too) native scrollbars used in qooxdoo emits decimal values for scrollbar positions.
The issue was observed when scrolling a virtual list using the scrollbar arrows or by dragging the bar with the mouse.
Shortly after scrolling this way, the browser window freezes and seems to run into an endless loop. The browser offers then after some time to stop the script/close the window.

**To Reproduce**
1. Set browser zoom to 110%
2. Run this playground script in current edge browser on windows: https://tinyurl.com/4wxybrcr and open the log window
3. Try to scroll down the list by dragging the scrollbar
4. Watch the scrollbar emitting the decimal values in the log window
5. Watch the app freezing after a while

**Desktop (please complete the following information):**
 - OS: windows 10 2021 ltsc
 - Browser edge, version 111.0.1661.54

**Observations/Cause**
Within the virtual list the items get their position based on the scrollbar position where especially the property top is set accordingly, in the case of edge sometimes with decimal values.
Later on when the layout queue is flushed, the decimal value reaches method renderLayout of qx.ui.core.LayoutItem where, in the source version, the decimal value for top is caught by assert statements (https://github.com/qooxdoo/qooxdoo/blob/master/source/class/qx/ui/core/LayoutItem.js#L389-L395) and a strack trace is generated.
In the build version there is no trace in the console.
I suppose that because of the decimal values of the top position, the same widget is re-added to the layout queue over and over, leading to the endless loop.

**Fix**
To avoid this, the scrollbar position emitted by the scrollbar should be converted from decimal to an integer value, using e.g. Math.round or Math.floor in, maybe in here: https://github.com/qooxdoo/qooxdoo/blob/master/source/class/qx/ui/core/scroll/AbstractScrollArea.js#L444-L455

**Comment by level420** [comment]
Additional Information: while testing my playground sample, an update for edge to version 111.0.1661.62 came in which does not show the issue anymore for 100% zoom, but when zooming in to 110% the scroll position event delivers decimal values again.

**Comment by hkollmann** [comment]
Could you create a PR please?

**Comment by level420** [comment]
@hkollmann it would be nice if you could verify the issue to be sure this is not some special behavior in my environment. thank you!

**Comment by hkollmann** [comment]
I can!

**Comment by level420** [comment]
I'll create a PR only fixing this for `qx.ui.virtual.core.Scroller` which is used in virtual widgets, but not in `qx.ui.core.scroll.AbstractScrollArea`, where  `qx.ui.virtual.core.Scroller` is derived from, as I don't know if this has implications to other non virtual widget which may work with decimal scroll values.
