### ISSUE TITLE
Jumping to top on touch event using safari / chrome on iphone

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#10565]
**Describe the bug**
This bug only occurs on iPhones with ios on safari and chrome with default mobile mode, not on other browsers and operating systems. There is also no bug if you activate the desktop website mode on safari / chrome on iphone!

Tapping with one finger somethere on the page, the page jumps to the top.

It does not happen every time, but mostly. Maybe it has something to do with focusing or the iphone safari highlighting.

**Screenshots**
![demo-browser-mobile](https://user-images.githubusercontent.com/6726821/227182639-f44d2184-4b4d-4413-9d28-e69a5bd320a2.png)

**To Reproduce**
1. Open the [demo page](https://qooxdoo.org/qxl.demobrowser/#) on iphone safari
2. Tap on animation and then again on animation 3d to start the demo
3. Scroll down on the right demo side
4. Look at the screenshot above. You should see something like on the picture.
5. Just tap anywhere with your finger, maybe on the text on the right side or on an item of the left list.
6. The demo page on the right side jumps to the top.

**Expected behavior**
Holding the scroll position. Do not jump to the top.

**Smartphone (please complete the following information):**
 - Device: iPhone (8,12 mini, xs)
 - OS:  iOS16.2 / iOS16.3
 - Browser: safari / chrome
 - Version don't know / current

Maybe there is a connection to [this unsolved issue](https://github.com/qooxdoo/qooxdoo/issues/9023).

**Update 15:15**
The bug exists in Qooxdoo 6 too.

**Comment by goldim** [comment]
@stahl-riesa I confirm this error on some devices (iphone 13). Not sure will have time for fixing it. Could you support the PR for the problem?

**Comment by stahl-riesa** [comment]
@goldim I'll try it. I just don't understand what's going on there. Although I use the event system from qooxdoo, I have never dealt with the internal things.

**Comment by stahl-riesa** [comment]
enviroment of ios 16.3 safari AND chrome
qx.bom.client.Browser.getName(): mobile safari
qx.bom.client.Engine.getName(): webkit
qx.bom.client.OperatingSystem.getName(): ios

Does Qooxdoo handle mobile safari like safari?

**Comment by stahl-riesa** [comment]
Maybe this [bug](https://bugs.webkit.org/show_bug.cgi?id=238497) is relatet to my requested one.

**Comment by goldim** [comment]
@hkollmann there is another PR for it - #10573

**Comment by hkollmann** [comment]
fixed with https://github.com/qooxdoo/qooxdoo/pull/10573
