### ISSUE TITLE
Setting modal to false on window creation adds the "modal" state incorrectly.

### ISSUE THREAD

**Issue by lucapivato** [qooxdoo/qooxdoo#10596]
Create a window and set modal to false, then check the "modal" state, it returns true. This is caused by the lack if this.initModal() and the _applyModal() method adding the state incorrectly.

https://tinyurl.com/2gp5qob7

**Comment by lucapivato** [comment]
Looks like window._applyActive() has the same mistake. 

```
      if (old) {
        this.removeState("active");
      } else {
        this.addState("active");
      }
```

Adds "active" when value is false and old is false, which happens without the init call. IMO it should be the opposite:

```
      if (value) {
        this.addState("active");
      } else {
        this.removeState("active");
      }
```

**Comment by goldim** [comment]
Merged PR
