### ISSUE TITLE
Intl instead of cldr

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10660]
In qooxdoo we use a node package  "CLDR" for internalization. This package requires cldr-data which weights around 250 MG. And so dependencies are duplicated twice because of known-good folder this size will be 500 MB.

I've checked there is [Internalization API](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl) already exists for this purposes.

I think about moving to this API. What do you think? I checked it has introduced in 2011-2014 maybe there already was discussion about it.

**Comment by johnspackman** [comment]
So long as it can provide all of the values that we need, including to NodeJS then that sounds like good idea.

We copy a lot of data out of CLDR, but it looks like (a) not much of it is used and (b) it's all abstracted into `qx.locale.*` classes anyway - I've only done a really simple search for "cldr_", but it seems that `qx.locale.Date` has eg `getMonthNames` and `getDateFormat`,  `qx.locale.Number` has eg `getDecimalSeparator`, and `qx.locale.String` has methods for quotes.

**Comment by goldim** [comment]
@johnspackman agree, I did some searches too and if `cldr` is not used somehow in compiler files and only in qx.locale package then it could be simply moved on new standard API.

**Comment by goldim** [comment]
@johnspackman opened [a discussion](https://github.com/qooxdoo/qooxdoo/discussions/10663) about problems of migrating.
