### ISSUE TITLE
Double Slash in Resource Path Causing Invalid Links

### ISSUE THREAD

**Issue by regexti** [qooxdoo/qooxdoo#10698]
I'm encountering an issue with the resource paths in Qooxdoo. The generated resource URLs contain double slashes, which result in invalid links when deployed to a domain. This problem occurs both in a newly created project and in an existing project.

Examples:
/resource//myapp/test.png (new project)
http://url/resource//separacao/logo-regex.png (this causes the link to be invalid)

@qooxdoo/framework": "^7.7.1

**Comment by goldim** [comment]
Confirm this. I thought I had made a mistake somewhere.
