### ISSUE TITLE
Placeholder text does not get correct theme color

### ISSUE THREAD

**Issue by rijckrocket** [qooxdoo/qooxdoo#10694]
**Placeholder text does not get correct theme color.**

Code in ui/form/AbstractField.js looks broken for some time to me (11th March 2013).
__stylesheet was replaced on most places by using "global stylesheet" code.

But the _onChangeTheme() function still contains this if statement:
if (!this.__useQxPlaceholder && qx.ui.form.AbstractField.**__stylesheet**) (which is not used any more)
So the color from the loaded theme is never applied.

I made changes locally where I verify if the theme name changed, re-creating the style only when needed.

Hope my explanation is clear :-)

**Comment by rijckrocket** [comment]
Will do so shortly

**Comment by hkollmann** [comment]
Thanks
