### ISSUE TITLE
qx.bom.Input - missing input types

### ISSUE THREAD

**Issue by WillsterJohnson** [qooxdoo/qooxdoo#10703]
**Describe the bug**
According to [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types), there are 22 valid input types, however `qx.bom.Input` only supports 13, of which 2 are not valid input types (`textarea` and `select` are their own html elements distinct from `<input>`).

**To Reproduce**

```js
<input type="number" />; // or any other missing type
```

**Expected behavior**
An instance of `qx.html.Element` with `tagName="input"` and `attributes={type:"number"}` should be created via `qx.html.Jsx.createElement`

**Screenshots**
![Screenshot](https://github.com/qooxdoo/qooxdoo/assets/85991558/1cd19c40-05a4-4fb5-ba84-9e740a266c57)

**Desktop (please complete the following information):**
- OS, Browser: any
- Version: 7.7.1

**Additional context**
This issue makes it **impossible** to use half of the available input types in jsx, importantly the `number` type.

**Proposed Solution:**
- On `qx.bom.Input`, expose the static `__types` field publicly as `types`
- In `qx.html.Factory` constructor at `this.registerFactory("input",...)`, check that the given type exists as a key of `qx.bom.Input.types`. If so, then continue with the current behavior. Otherwise, fallback to creating a plain `qx.html.Element`

This would only change the behavior of code which would otherwise throw an error and crash the application, so is shouldn't have any impact on existing code.

**Comment by goldim** [comment]
@WillsterJohnson I also don't see any problem just adding the support for new types. As you said old apps will work as before and if they use new types they get some crash. Maybe there are ways to handle an error. Could you support a PR please?
