### ISSUE TITLE
The qx.util.Serializer.toJson fail on NaN integer

### ISSUE THREAD

**Issue by nwgroup** [qooxdoo/qooxdoo#10712]
When av value have an NaN value, the JSOn structure fails.

**To Reproduce**
1. Create an array with NaN value

**Comment by goldim** [comment]
@nwgroup Hello, could you describe the issue in more details please? What version of environment/qooxdoo/nodejs/etc do you use? Some code example also be wanted.
What I've tried is:
```javascript
const serer = qx.util.Serializer;
const res = serer.toJson([1, NaN]);
console.log(res);
```
qx v7.7.2 and there is no any errors. The output is fine.

**Comment by nwgroup** [comment]
Well, finally we found the problem on an RPC call with NaN values. For that reason our fix was:

`   toJson(object, qxSerializer, dateFormat) {
      var result = "";

      // null or undefined
      if (object == null) {
        return "null";
      }
      
      if (Number.isNaN(object)) {
        return "null";
      }` and the RPC call got fine. Thanks for the help!
