### ISSUE TITLE
Safari not loading nor using webfonts

### ISSUE THREAD

**Issue by wthie** [qooxdoo/qooxdoo#10725]
**Describe the bug**
Safari Desktop does not load webfont files, subsequent use of the font renders with fall back font.
Strange enough, Safari Mobile on iPad and iPhone loads the font file.

**To Reproduce**
```
mkdir qooxdoo.safari
cd qooxdoo.safari

# create a minimal desktop app
mkdir myapp

# test the app with
npx qx serve

# adding the font files on path myapp/source/resource/myapp/fonts like
ls -als myapp/source/resource/myapp/fonts
-rwxrwxr-x 1 xxxx xxxx  387400 Sep 22 12:00 SourceSansPro-Regular.otf
-rwxrwxr-x 1 xxxx xxxx 1220563 Sep 22 12:00 SourceSansPro-Regular.svg
-rwxrwxr-x 1 xxxx xxxx  274256 Sep 22 12:00 SourceSansPro-Regular.ttf
-rwxrwxr-x 1 xxxx xxxx  124500 Sep 22 12:00 SourceSansPro-Regular.woff
-rwxrwxr-x 1 xxxx xxxx   84808 Sep 22 12:00 SourceSansPro-Regular.woff2

# modifying the app in directory myapp by applying the following diffs

# for Manifest.json
myapp/Manifest.json 
20c20,37
<     "translation" : "source/translation"
---
>     "translation" : "source/translation",
>     "fonts"       : {
>       "SourceSansPro" : {
>         "fontFaces" : [
>           {
>             "fontFamily": "SourceSansPro",
>             "fontStyle": "normal",
>             "fontWeight": "1 1000",
>             "paths": [
>               "myapp/fonts/SourceSansPro-Regular.eot",
>               "myapp/fonts/SourceSansPro-Regular.ttf",
>               "myapp/fonts/SourceSansPro-Regular.woff",
>               "myapp/fonts/SourceSansPro-Regular.woff2"
>             ]
>           }
>         ]
>       }
>     }    

# for Application.js
class/myapp/Application.js 
1a2
> 
56a58,59
>       
>       button1.setFont(qx.bom.Font.fromString("bold 100px SourceSansPro,Courier New"))

# for Font.js
myapp/source/class/myapp/theme/Font.js 
10a11,15
> /**
>  * @usefont(SourceSansPro)
>  */
```
**Expected behavior**
The app in the myapp directory shows a massively bigger button (font size 100px) with the text rendered in the font SourceSansPro as specified on all major browsers except for Safari Desktop which makes not even an attempt to load the webfont File and falls back to Courier.

From testing I only ever saw the .woff file being loaded, whereas technically .woff2 should be preferred. 

**Screenshots**
![Bildschirmfoto 2024-09-23 um 08 26 34](https://github.com/user-attachments/assets/17325f7d-fdb6-4399-a756-59f62cce07c3)

**Error occurs only on**
 - OSX sequoia and previous
 - Browser Safari Desktop
 - Versions 17.3 and 17.6

**Comment by goldim** [comment]
@wthie Hello, could you share your compile.json file too please? Also if you use fonts locally not from CDN then you have to set next options for targets:
```json
"targets": [
    {
      "type": "source",
      "outputPath": "compiled/source",
      "fonts": {
        "local": true,
        "fontTypes": [
          "ttf"
        ]
      },
      "bundle": {
        "include": "qx.*"
      }
    },
```
P.S. I can't check it on Safari so far unfortunately but gonna do it.

**Comment by wthie** [comment]
Here is the requested compile.json used in the example
```
{
  "$schema": "https://qooxdoo.org/schema/compile-1-0-0.json",
  "targets": [
    {
      "type": "source",
      "outputPath": "compiled/source",
      "bundle": {
        "include": "qx.*"
      }
    },
    {
      "type": "build",
      "outputPath": "compiled/build"
    }
  ],
  "defaultTarget": "source",
  "locales": ["en"],
  "environment": {
      "qx.icontheme": "Tango"
  },
  "applications": [
    {
      "class": "myapp.Application",
      "theme": "myapp.theme.Theme",
      "name": "myapp",
      "bootPath": "source/boot"
    }
  ]
}
```
Concerning the fonts section in target I didn't find anything about that in the docs. Did I miss something? Where would I look up this configuration change? Why is ttf specifically mentioned in the fonts section?

Will change the app and test on Safari.
Mahalo

**Comment by goldim** [comment]
@wthie Check it out https://github.com/qooxdoo/qooxdoo/issues/10658 . I had the same problem with that and this moment in other part of docs.  But in my situation fonts don't work at all without changes in compile.json. Maybe your fonts already somewhere or loaded via CDN, cached etc.

**Comment by wthie** [comment]
Indeed the change you proposed triggers Safari to load the .ttf Font File just ok. With that we can relegate the problem to fixing the docs. Good examples  would be worth their weight in gold, even only listing the possible section names in the JSON files would be very illuminating. I hate googling such stuff for hours no end

**Comment by goldim** [comment]
@wthie any suggestion how to do it properly is highly appreciated. I may move just cdn/local section to the font article. I am gonna close the issue. Are you fine with it? About doc could be separate issue or just PR.

**Comment by wthie** [comment]
Sure, close this issue please and thank you for shining light on those pesky JSON config files.

I'll look into having the different font file types being loaded appropriately by enhancing the font section in compile.json. Maybe this provides enough meat to do an example.
