### ISSUE TITLE
Chrome v 50 deprecation of SVGElement.offset(Parent|Top|Left|Width|Height)

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#195]
Chrome ist dropping support of SVGElement.offset(Parent|Top|Left|Width|Height) with upcoming version 50:

See https://www.chromestatus.com/features/5724912467574784

This means that trying e.g. to retreive the width and height of a inline svg element within qooxdoo does not work anymore, if this is done via elem.offsetWidth and elem.offsetHeight.

Playground example created by Alexander Kirsanov which shows the problem: http://tinyurl.com/h89s2pk

See discussion on the qooxdoo-devel mailing list:

http://qooxdoo.678.n2.nabble.com/Upgrade-for-offsetWidth-td7588186.html

**Comment by level420** [comment]
See discussion on the qooxdoo-devel mailing list:

http://qooxdoo.678.n2.nabble.com/Upgrade-for-offsetWidth-td7588186.html

**Comment by level420** [comment]
There is also an issue for jQuery: https://github.com/jquery/jquery/issues/2895

**Comment by cajus** [comment]
What is needed to reproduce the deprecation warning or the bug at all? I'm running the code in Chrome 50+ and I can't see any problem.

This is the application code:
```
var size = 100;
var center = size* 0.5;
var min = 5;
var max = size - min;
var data = ['<svg width="', size, '" height="', size, '"><path d="',
            "M" , center, " ", min, " ",
            "L", center, " ", max, " ",
            "M", min, " ", center, " ",
             "L", max, " ", center,
             '" stroke="#ff00ff" stroke-width="2" fill="none"/></svg>'
           ];
      
var html = new qx.ui.embed.Html(data.join(''));
html.set({
   width: size,
   height: size
});

html.addListener('click', function(){
    var el = html.getContentElement().getDomElement().firstChild;
    console.log(qx.bom.element.Location.get(el, "margin"))
}, this);
                      
var doc = this.getRoot();
doc.add(html);
```

**Comment by level420** [comment]
@cajus what do you get as result in the console for
```javascript
html.addListener('click', function(){
    var el = html.getContentElement().getDomElement().firstChild;
    console.log(qx.bom.element.Location.get(el, "margin"))
}, this);
```
?
I'm getting:
```
Object {left: 987, top: 139, right: NaN, bottom: NaN}
```
This is for Chrome "Version 51.0.2704.54 beta-m (64-bit)" and "Version 50.0.2661.102 m (64-bit)"

**Comment by level420** [comment]
As a result of the deprecation, you don't get the dimensions anymore.

**Comment by cajus** [comment]
With chrome 50, I'm still getting valid values there. That's why I was asking. Additionally, there's no warning about a deprecation, so I was a bit confused about it.

I've no beta versions installed. Just the stuff that google is delivering thru the apt/rpm update URLs.

**Comment by level420** [comment]
@cajus here on my machine with windows 7 and chrome 50 the playground example fails.
