### ISSUE TITLE
Methods from superinterface not recognized by API generator as inherited

### ISSUE THREAD

**Issue by dteleguin** [qooxdoo/qooxdoo#210]
If there is more than one interface in the inheritance chain, API generator fails to recognize inherited  methods as such. For example:

* interface `IFoo` defines+documents method `foo(x)`
* interface `IBar` extends `IFoo` and defines+documents method `bar(x)`
* class `Clazz` implements `IBar` and both methods

Invoking `generate.py api-data` results in a warning (line 10 is exactly where `foo(x)` is implemented):
```
- Warning: foo.Clazz (10,14): Parameter is not documented: 'x'
- Warning: foo.Clazz (10,14): Documentation is missing.
```
In the API viewer, `Clazz#foo` will be shown as broken.

As a workaround, one can explicitly list all the interfaces implemented by the class; in our case, that would be `implement: [ IFoo, IBar ]`. This will make the warning go away, and will fix method display in the API viewer.

**Comment by level420** [comment]
@thron7 would please be so kind to have a look into this? I think big parts of the generator are written by you. Thank you.

**Comment by thron7** [comment]
@level420 Will have a look, but might take some time.

**Comment by level420** [comment]
@thron7 thank you!

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/commit/72388c7cdbcc6390a3ade19b41ba33eaf1525061
