### ISSUE TITLE
Add standard upload widget

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#212]
The framework miss a widget to upload files.

**Comment by johnspackman** [comment]
+1 I vote to incorporate my UploadMgr contrib

**Comment by derrell** [comment]
I second that.

John, I have a few minor bug fixes that I made to it a couple of years, I
think. When I get a chance, I'll diff what I have with yours and see what
the issues were.

Derrell

**Comment by oetiker** [comment]
it would be great if the 'standard' upload widget was capable of using some tricks from https://github.com/23/resumable.js

**Comment by johnspackman** [comment]
@oetiker yes it would - i might have a use case to add that into my app soon (users uploading very large files)

@derrell brill, thank you - ill try and sort out a PR sometime for it, but only the namespace will change so it should be easy to compare

**Comment by level420** [comment]
I vote to incorporate, for simple use cases, https://github.com/qooxdoo-contrib/catalog/tree/master/contributions/UploadWidget

**Comment by dteleguin** [comment]
I vote for UploadMgr. We've been using it for a while, and it works perfectly. Good job @johnspackman :)

**Comment by johnspackman** [comment]
Obviously Im biased :) but IMHO UploadMgr's preferable because it can handle multiple uploads, in the background via the File API, provide upload progress feedback, and falls back all the way to IE6 support.  I based it on the work you & Tobias did so I was able to take advantage of the new (at the time) browser support, so I guess I see it as the next version?

**Comment by level420** [comment]
OK, then let's go with UploadMgr! It should be simple to migrate my simple use case to UploadMgr (i hope). If not, I'll bug @johnspackman with my problems ;-)

**Comment by oetiker** [comment]
I have not used upload manager yet ... :blush: so I can't really say much ... but since @johnspackman expects to be spending more time on his widget soon, this would certainly be a worthier candidate than our simple one ...

**Comment by cajus** [comment]
+1 for @johnspackman 's UploadMgr, too. Using it in various projects currently. We've basic File API support done for that just two weeks ago. Let me check the state of it tomorrow.

**Comment by mbgonicus** [comment]
Here is the [basic FileApi support](https://github.com/mbgonicus/UploadMgr/commit/1718efa4fb7d7c7c569676569008a455b11dd5f3)  @cajus. I'm in contact with @johnspackman about if and how to integrate it to the UploadMgr as it currently is just the basic single file upload and pretty dirty. Features like multi file upload, cancellation and progress information are missing and it is not integrated to well with the given class structure.

Anyway - it works and might help somehow.

**Comment by derrell** [comment]
I added a line note, but that doesn't seem to get distributed. This should probably use qx.bom.FileReader rather than directly accessing the FileReader object.

**Comment by johnspackman** [comment]
thanks for the votes :)

@mbgonicus Markus I must be missing an email because I don't think we've talked about this before?  Also, Im not clear about the purpose of the commit, for example how does the `com.zenesis.qx.upload.FileReader` get instantiated?  

Please can we continue the discussion of changes as a PR or issue at https://github.com/johnspackman/UploadMgr ?

**Comment by mbgonicus** [comment]
@derrell Good point; I will fix that.

@johnspackman I wrote via gitter.im. I'll make a PR for it and we can discuss it there.

**Comment by derrell** [comment]
@mbgonicus, @johnspackman: I added comments to @mbgonicus' repository.
There is already a FileReader in qooxdoo: qx.bom.FileReader. If we're going
to use a FileReader object, we should probably use that one.

Derrell

**Comment by mbgonicus** [comment]
PR created: https://github.com/johnspackman/UploadMgr/pull/3

**Comment by cajus** [comment]
Even though the browser support isn't that wide, that would be nice, too:

http://stackoverflow.com/questions/181214/file-input-accept-attribute-is-it-useful

**Comment by oetiker** [comment]
since browser support seems to be spotty, we might want to provide a stable interface that can be updated as browser support grows ...

**Comment by johnspackman** [comment]
sounds reasonable https://github.com/johnspackman/UploadMgr/issues/4

**Comment by paragasu** [comment]
I use UploadMgr recently too. +1 for UploadMgr

**Comment by adrelino** [comment]
does it support uploading files clientside, previewing (and possibly manipulating them (e.g rotating if it is an image)) and only then uploading it to the server?  Or does it directly upload the files to the server?
