### ISSUE TITLE
fix setter APIs consistency 

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#213]
Currently, there are 3 ways to use setter : 
- `obj.setFoo('bar')` -> return 'bar'
- `obj.set('foo', 'bar')` -> return 'bar'
- `obj.set({foo: 'bar'})` -> return obj

The 3 ways should return the obj instance (to chain) : 
`myLayout.add(new Object().setFoo('bar'));`

**Comment by johnspackman** [comment]
Personally I use the third form all the time so I want to +1 this because I can see myself using the first two also (I didn't know they existed)

IMHO returning the value set is of limited use, but this would be a breaking change

**Comment by oetiker** [comment]
These are API breaking changes, I would strongly advise AGAINST doing that. I would rather add new methods with different names if you desire different behaviour AND for all future developments debate long and  hard how a new core method should operate

**Comment by woprandi** [comment]
For me it's concevable for a major version

**Comment by schnepe2** [comment]
I would also vote for this.

- I don't think anybody uses one of the first two idioms to "get" the result value
- As @woprandi said in his comment before: in a major version update anything is allowed ;)
- One could think of a 'legacy-setter-mode' config switch that allows user side scripts that really used set() as mentioned in 1st point until they migrate their code.

On the other hand: I think most users are aware of the fact that only obj.set({...}) returns the object reference and therfore use it like this:
```
var obj = new Foo(1).set({ bar: "baz" });
var obj2 = new Foo(2);
obj2.setBar("baz");
```

**Comment by qx-bug-importer** [comment]
I think the reason for `setProp(k)`  to return `k` is consistency since its sister method `getProp()` returns a value too.

Let's refrain from breaking any API's where there is no overwhelming benefit from doing so.

**Comment by woprandi** [comment]
It's not a volontary behavior. I already reported this issue few weeks ago and the documentation was been updated

**Comment by woprandi** [comment]
I just checked and the documentation is up-to-date only since 5.0.1
Previously, the documentation specified that it return the instance

**Comment by oetiker** [comment]
`object.setProp(value)` has been returning the input value in since qooxdoo 1.0 at least: https://github.com/qooxdoo/qooxdoo/blob/release_1_0/qooxdoo/framework/source/class/qx/core/Property.js#L798 or are you talking about something else ?

**Comment by woprandi** [comment]
I mean the API viewer has always indicated until 5.0.1 that `set(...) ` return the instance 
http://demo.qooxdoo.org/current/apiviewer/#qx.core.MProperty
http://demo.qooxdoo.org/5.0/apiviewer/#qx.core.MProperty

**Comment by oetiker** [comment]
@woprandi yes sure, `set({...})` returns the object, that is fine, and I use it a lot ... but in your isseu you request for `setProperty(...)` to alter its behaviour and start returning the object instead of the value just set ... that is what I aimed my comments at.

**Comment by woprandi** [comment]
There is a 3rd way : set("property", value) which return also value instead of the instance

**Comment by oetiker** [comment]
yes that is equivalent to setProp because it also sets one property ... seems pretty consistent to me

**Comment by woprandi** [comment]
For or Against this enhancement for the 6.0 ?

**Comment by oetiker** [comment]
breaking the API requires very good arguments ... ! I have not seen any yet. Don't break the API ...

**Comment by oetiker** [comment]
we have thousands upon thousands of lines of qooxdoo code ... if one of the methods changes its behavior, this is very expensive to fix as we have to hunt down all occurrences of this method in our code. If a method is 'bad' create a new one with a different name and deprecate the old one ...

**Comment by johnspackman** [comment]
Although I would like this personally, I agree with @oetiker - for example if my code routinely used the result of `setXxxxx`, it would be impossible to find and fix the code without reviewing the code line by line, and in even moderately sized applications that kind of work is just not possible.  It would absolutely cause me to not upgrade, or I'd be forced to have my own branch whether I wanted one or not.

This would affect contribs also, many of which are not actively maintained any more so the negative side effects could be huge.

IMHO the only way we could even consider implementing this would be if the generator was able to accurately detect and provide migration warnings, but that still means there could be a dauntingly large amount of work to undertake when upgrading.  A babel plugin could edit the code effectively but then we're talking a big undertaking for a minor feature
