### ISSUE TITLE
Promises for Qooxdoo

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#214]
Adding a Promises implementation to Qooxdoo would be beneficial because:
- it enables events to be chained in a structured, application specific order;
- there is pressure to switch to using async I/O when communicating and promises encourage async coding;
- it is a popular and well understood pattern

At the least, the implementation should use a short namespace (eg qx.Promise) and support binding "this" to the entire promise.

Also proposed is this [StackOverflow question](http://stackoverflow.com/questions/35156009/controlled-event-handling-flow-in-qooxdoo) which proposes that by returning Promises from event handlers, asynchronous event handlers can be implemented

Similarly, property apply methods could return a Promise to indicate when the apply has completed (effectively delaying the changeXxxx event for the property until applyXxxx has completed)

As well as that SO question, this would be useful for server I/O - as volumes of data increase, browsers time out the connection _unless_ it is asynchronous (especially Safari); for example, an apply method which performs an asynchronous operation, causes the caller to think the apply has completed it's work (which might include loading other objects from the server) - the caller then tries to use these objects but fails milliseconds before the data arrives.

It is reasonable for an apply method to take an unspecified amount of time, and when it comes to server I/O it is increasingly important that this is allowed to be asynchronous. Technically, the powers that be have decided that synchronous I/O is deprecated, and Safari is already adding a fixed, very short timeout to synchronous I/O operations that cannot be overcome.

**Comment by derrell** [comment]
We are using the Promise package from https://github.com/kriskowal/q in our
server apps. It works well for us, and may provide either a starting point,
or some ideas for a native qooxdoo implementation.

Derrell

**Comment by dteleguin** [comment]
We've been using native promises for a while in our qooxdoo project. There are several moments to pay attention to:

1. Most modern browsers [do support Promises, but some still lack it](http://kangax.github.io/compat-table/es6/), most importantly PhantomJS (see this [issue](https://github.com/ariya/phantomjs/issues/12401)). PhantomJS remains a de facto standard in headless testing, and it's unlikely that it gets Promise support until they migrate to [CEF](https://bitbucket.org/chromiumembedded/cef).
    That said, we'll have to provide a fallback implementation. In our project, we used [babel-polyfill](https://github.com/babel/babel/tree/master/packages/babel-polyfill), and it worked perfectly. Considering that there were plans to integrate babel-polyfill into [QxCompiler](https://github.com/johnspackman/qxcompiler), this might be the way to go.

2. There is another qooxdoo+Promise [StackOverflow question](http://stackoverflow.com/questions/28756928/using-promises-in-a-qooxdoo-application), and we've been facing exactly the same issue. By default, the code executed from Promise constructor and `then()`/`catch()` blocks has its `this` bound to `window`. Thus, an attempt to use qooxdoo instance methods in Promise()/then()/catch() contexts will result in a number of explicit binds to `this`. Thoughtfully designed `qx.Promise` could help us get rid of that.

**Comment by level420** [comment]
As indicated in http://kangax.github.io/compat-table/es6/ currently IE11 does not support Promises. IE11 is and will be for the next years a major platform which qooxdoo should support.

**Comment by johnspackman** [comment]
When it comes to using the babel polyfill, we could rely on babel (via qxcompiler) to do it but we’d have to complete the switch to qxcompiler and officially abandon generate.py for compilation (which is do-able) and we’d have to educate users to run continuous compilation mode (also do-able, but yet to be written).

Im not sure we have to worry about it if we are talking about providing our own qx.Promise which has some useful upgrades because that frees our qx.Promise to use whatever implementation it wants, and then there are no external requirements or other timescales to consider

**Comment by johnspackman** [comment]
Reading from that StackOverflow question, [this one](http://stackoverflow.com/questions/21315817/chained-promises-and-preserving-this) is all about binding `this` to the Promise and how [Bluebird](http://bluebirdjs.com/docs/features.html) solves that problem.

Bluebird is a cross platform Promise library with some very nice extra features: a `bind()` method to tying this to the whole promise, improved debugging and error logging, warnings, automatic conversion of async methods to Promise methods (really useful for server based node.js usage).

It uses the MIT license so there's no problem embedding it

**Comment by oetiker** [comment]
So we could create a qx wrapper and integrate the bluebird library ?

**Comment by johnspackman** [comment]
Yep. Instant reliable promises, then there's just the events and apply integration to do

**Comment by zmughal** [comment]
Should this be closed with the merge of <https://github.com/qooxdoo/qooxdoo/pull/9232>?

**Comment by level420** [comment]
@zmughal yes, thank you. 
Fixed via #9232
