### ISSUE TITLE
Automatic Memory Management

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#215]
Memory management in Qooxdoo is currently done manually - it is essential to track and `.dispose()` objects properly to avoid leaks.  This is a big hindrance to writing large, complex applications which are long running.  

I originally suggested this in [a proposal on the mailing list](http://qooxdoo.678.n2.nabble.com/Qooxdoo-Automatic-Memory-Management-a-proposal-td7587901.html) 3 or 4 months ago, and since then I've been using my patch to deprecate .dispose() on live applications.

My observations are that this is a good thing, does not introduce any problems that I've noticed, and has allowed me to quickly fix some tricky bugs just by getting rid of calls to `.dispose()`.

As demonstration that this is a good thing, the Qooxdoo framework test suite (in Jan 2016) had only 413 objects that were not disposed when using this patch, compared to 4,500 objects unpatched.  (OK it’s fair to say that unit tests are not required to free up resources that they consume, but it is striking how easy it is to have significant resource leaks that can be so easily countered by garbage collection)

The key points of the proposal are that:

(1) it is impossible to know if you should free up an object that you pass in to a property, for example `qx.ui.form.SelectBox.setSelected` will copy the array that you give it, while other objects might take it over and keep it

(2) Methods often allocate objects that cause hard to spot leaks, for example `qx.data.Array` methods such as splice and slice return an array of the removed items, but the returned object is an instance of `qx.data.Array` so you *must* dispose it.  This is counter intuitive (and error prone) partly because `qx.data.Array` goes to some lengths to act like a native array, but native array methods don't need their side effects to be disposed

(3) These memory issues are only there because every `qx.core.Object` is registered with `qx.core.ObjectRegistry` and this is not necessary in almost all cases.  We can remove this registry with almost no backward compatibility issues, and in doing so make it much easier to code Qooxdoo apps.

(4) The only parts of the Qooxdoo framework that depend on `qx.core.ObjectRegistry.fromHashCode` are `qx.ui.core.Widget` and `qx.data.controller.Tree`; Widget uses the hash code to avoid having DOM objects that refer to Javascript objects, which was to avoid IE6 bugs - so this can be dropped.  Tree can implement its own lookup if necessary

The backwards compatibility issues that this will introduce are:

(A) `qx.core.ObjectRegistry.fromHashCode()` will no longer work, unless the object is manually registered with `qx.core.ObjectRegistry.register()`.

(B) By discouraging the use of .dispose(), we are implicitly discouraging the use of destructors; destructors are not as useful as they appear in garbage collected environments because garbage collection does not imply any kind of ordering and references outside of the object being destructed are often a mistake

(C) Objects will not be disposed during shutdown (but actually this can break an application because in many cases objects have to be disposed in the correct sequence, and ObjectRegistry does them in its own order)

**Comment by petitben** [comment]
Hi,

I'm rather OK with the main idea but are you certain we can remove completely the dispose method and that it will cover all cases ? Sometimes people want to free mem explicitly. Having the dispose method was "a nice place" to let developer free resources. 

I didn't dig it at very deep level but I wonder if it would be interesting to leave the opportunity to a devevelopper (or the framework itself) to free resources by him/it-self in some specific (or critical) cases...

**Comment by derrell** [comment]
I love this idea. I do, however, use fromHashCode for some objects. I
should be able to explicitly register those, or come up with some other
mechanism for getting unique IDs for objects... I hope. If I'm using
fromHashCode, though, I wonder if others are too? Maybe have a run-time
switch that allows turning on (or off, if the default remains as it
currently is?) the current behavior?

Derrell

**Comment by johnspackman** [comment]
@petitben By deprecate, what I really meant was that I've chosen to not call it in my own apps, relying on garbage collection (and the patch) to do the work for me.  This isn't ideal in that, as you point out, some objects do need to have an explicit destruction so that resources can be freed, which leads to a situation where we're saying that `.dispose()` is unnecessary *except* where explicitly documented otherwise.

@derrell that's not a problem, you simply need to call `qx.core.ObjectRegistry.register()` with the object and `fromHashCode()` will list that object - `.register` is all that `qx.core.Object` did.  Also, toHashCode() will still work *without* calling `register()`, so every object still has a unique ID and the only change is that the object not listed in a monolithic list.

This change will be a breaking change for people who use fromHashCode because they will need to either manage their own lookup or call `.register()` but OTOH its for a very beneficial result.

We could turn it on/off globally but I think that this could be confusing - if it was turned on before a new object, any objects created by that constructor would be tracked too, and changes to apparently unrelated classes could cause leaks as libraries are updated.

**Comment by johnspackman** [comment]
PR https://github.com/qooxdoo/qooxdoo/pull/8986

**Comment by cajus** [comment]
A bit off topic - but maybe not really: I'd like to see something that automatically maintains listeners if the target is destroyed. Currently this only works for bindings.

If you've a model for example which is there all the time, and you bind some property to a widget which is disposed, the listener is still there. It should be dropped automatically.

**Comment by johnspackman** [comment]
@petitben I've just pushed another commit that clears up the distinction between explicit and automatic disposal; there's a large comment in that PR that describes how it works.

@cajus Its interesting that SingleValueBinding uses a global list of bindings (and their reverse) so that this can be implemented; IMHO there's a good argument to move those lists into the actual object, possibly to be part of the existing listeners.  As this would require the reverse bindings to be stored in order to maintain backwards compatibility for `.removeBindingFromObject` and `.getAllBindingsForObject`, then what you're asking for would become pretty easy to implement.

**Comment by cajus** [comment]
@johnspackman I'm currently doing this by an "addAutomaticListener" method which stores the  target object reference and the binding id. That stuff gets cleaned up on object dispose. But as you said, it would be nice to get rid of these hacks and let qx maintain this directly.

**Comment by oetiker** [comment]
#8986 has been merged
