### ISSUE TITLE
Migrate Bugzilla to Github

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#218]
I have written code to migrate the existing bug database from Bugzilla to Github issues. A 'test migration' can be found here:

https://github.com/qx-bug-importer/qooxdoo-old-bugs

* The migration will convert the usernames of the most active bugzilla users to their github usernames
* only framework and contrib bug will be migrated (not next and website)
* attachments get uploaded to imgur and linked into the bug reports
* versions information gets migrated into milestones ... although that may be a bit misleading since milestones are normally used as targets for which the bugs should be resolved while here it would be bugs that were detected in a particular version of qooxdoo

I propose to run my converter and integrate the bugs into the qooxdoo repo proper.

**Comment by cajus** [comment]
Cool ;-) No way to check everything, but a few random samples looked good. So +1 from me.

**Comment by level420** [comment]
Looks good for me as well. Thank you @oetiker

**Comment by oetiker** [comment]
migration is complete
