### ISSUE TITLE
Tab no longer works when modal window looses the focus (BZ#8074)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8104]
_Jeroen (Jeroen.Smit) wrote:_

I encountered a bug in the combination of focus handling and the blocker of a modal window.

Below I included a small piece of code that shows the bug when running the code in e.g. Chrome on the playground. When the window is shown and you click in the first textfield you can use TAB to go from one textfield to the other and SHIFT + TAB to go back. As soon as you click outside of the window and click back in the textfield you can edit but TAB no longer works. Other special keys like Escape and Enter are no longer propagated to the window too.

Debugging the Qooxdoo code I found that
- Initially TAB is handled by the FocusHandler (method __onKeyPress)
- After clicking out of the window and back in the TAB is caught by method __stopTabEvent in Blocker.js

I think that the order of registered events changes at runtime by the focus loss.

------ Code example for playground ------

var win = new qx.ui.window.Window(&quot;First Window&quot;);
win.setWidth(300);
win.setHeight(200);
win.setShowMinimize(false);

win.setLayout(new qx.ui.layout.Canvas());

var tf1 = new qx.ui.form.TextField(&quot;test1&quot;);
win.add(tf1, {left:10, top:10});

var tf2 = new qx.ui.form.TextField(&quot;test2&quot;);
win.add(tf2, {left:10, top:40});

this.getRoot().add(win, {left:20, top:20});

win.setModal(true);

win.open();

**Comment by adrelino** [comment]
Is this finally fixed now? Took me and @marcelr a lot of time to trace this loosing tabbing issue down to a bug in qooxdoo. Or is the suggestion to not use modal windows when tabbing is desired?

**Comment by level420** [comment]
Reopening this issue

**Comment by level420** [comment]
@adrelino @marcelr please have a look into PR https://github.com/qooxdoo/qooxdoo/pull/9466 and report back if it solves the issue for you. Thank you.

**Comment by level420** [comment]
Fixed via #9466
