### ISSUE TITLE
Wrong dragged item indication on virtual widgets (BZ#8284)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8310]
_Mustafa Sak (@msak) wrote:_

Mind you have a virtual list with many items. Drag first one and move the mouse to the bottom. The list begins to scroll down. After a few items scrolled an item will be shown which has the same indicator like dragged item.

Recommended to only indicate the dragged item.

**Comment by RemiHeugue** [comment]
This bug still exists.

On this demo : http://demo.qooxdoo.org/current/demobrowser/#virtual~List.html
Start dragging an item of the center list (Labeled "One as selection mode") and scroll, you'll see that the dragged widget cycle in the list.

**Comment by cboulanger** [comment]
I cannot reproduce it in http://www.qooxdoo.org/qxl.demobrowser/#virtual~List.html

Can this be closed?
