### ISSUE TITLE
qx.event.message.Bus.dispatchByName() does not dispose its message (BZ#9166)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8896]
_George Nikolaidis (gnikolaidis) wrote:_

It seems that while qx.event.message.Bus.dispatchByName() creates a new qx.event.message.Message object, it does not trouble itself with disposing it after usage.

Since qx.event.message.Message extends qx.core.Object and calls the base constructor which registers every instance in the registry, I believe this leads to memory leaks.

_assigned to Christian Boulanger (@swernerx)_

**Comment by gnikolaidis** [comment]
Please consider reopening

**Comment by oetiker** [comment]
hmmm I seem to remember that something like this was fixed recently

**Comment by oetiker** [comment]
#9038
