### ISSUE TITLE
Source map generation (script.js.map) (BZ#9207)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8935]
_George Nikolaidis (gnikolaidis) wrote:_

Source maps are useful for debugging production builds.

In our case, client-side warnings and errors are automatically reported to our server thanks to a custom qx.log.appender. These reports contain qx.core.Environment information and stack traces; they are the most important tool we have to resolve post-release errors and improve overall quality. Since the stack traces have references to the minified JS, a source map will help us pinpoint the exact location of reported errors.

I am adding some pointers in case a QX developer decides to work on this:

Discussion in QX mailing list (2013)
http://qooxdoo.678.n2.nabble.com/Source-maps-td7583572.html

Source map v3 specification https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k

Useful info on source map generation
http://qfox.nl/weblog/281

About VLQ encoding
https://en.wikipedia.org/wiki/Variable-length_quantity

**Comment by gnikolaidis** [comment]
Please consider reopening this bug, thanks

**Comment by cajus** [comment]
Makes sense.

**Comment by gnikolaidis** [comment]
Related bug: https://github.com/qooxdoo/qooxdoo-compiler/issues/18

**Comment by cboulanger** [comment]
I think this can be closed because the generator will be deprecated in qx6.0 and not further developed.

**Comment by cboulanger** [comment]
See also #9487
