### ISSUE TITLE
Encoding problem related to the path in which the Qooxdoo SDK resides (BZ#9232)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8959]
_Julie BOURBEILLON (julie.bourbeillon) wrote:_

When the path under which the Qooxdoo SDK has been installed contains non-ASCII characters, attempts to re-encode it in create-application.py fails with a UnicodeDecodeError.

Example scenario on a linux system:

mkdir héhé
cd héhé
unzip qooxdoo-5.0.1-sdk.zip
./qooxdoo-5.0.1-sdk/create-application.py --name=test

Will cause the following error:

Traceback (most recent call last):
  File &quot;../qooxdoo-5.0.1-sdk/tool/bin/create-application.py&quot;, line 37, in &lt;module&gt;
    SKELETON_DIR  = unicode(os.path.normpath(os.path.join(FRAMEWORK_DIR, &quot;component&quot;, &quot;skeleton&quot;)))
UnicodeDecodeError: &#39;ascii&#39; codec can&#39;t decode byte 0xc3 in position 20: ordinal not in range(128)

It is specifically the path to the qooxdoo SDK which causes the problem and not the path to the application (both cases have been tested).

OS : Debian linux
Python : 2.7

**Comment by thron7** [comment]
I haven't checked myself, but this is fairly new and well-documented, so probably still valid.

**Comment by cajus** [comment]
Just checked. Need to find a central place where to do a *.decode('utf-8')*. Looks like the paths that go to the tree parsing need to be "fixed", too.

**Comment by level420** [comment]
I've sent an email to the original issue submitter with references to the issue and PR on github.
