### ISSUE TITLE
VirtualDropDownList internal list selection keeps receiving bubbling events after being disposed

### ISSUE THREAD

**Issue by RemiHeugue** [qooxdoo/qooxdoo#8990]
I found a bug in the `qx.ui.form.core.VirtualDropDownList` class.

If you use a Widget with a `VirtualDropDownList` (like `VirtualSelectBox`) with items that include `qx.data.marshal.MEventBubbling` then dispose it while any element other than the first is selected and then change a property, the bubblingEvent will be fired and use the `VirtualDropDownList` internal `List` selection as context, which is now disposed.

This is due to the `__synchronizeSelection` method in [VirtualDropDownList.js](https://github.com/qooxdoo/qooxdoo/blob/dbd14ab643bd7fafc2a88e928f9e649567322ccc/framework/source/class/qx/ui/form/core/VirtualDropDownList.js#L385) that changes the native array of the selection directly which prevent removal of the bubbling event listeners.

Here is a [playground example of the bug](http://tinyurl.com/zodlqov).

1. Open the log panel
2. Select the second item
3. Click the "Destroy" Button
4. Click the "Change Item2 value" Button

You will get something like

    154941 qx.event.dispatch.Direct: The context object '' for the event 'changeBubble' of 'crash.Item[548-0]'is already disposed.
    154946 Assertion error! Trying to call a bound function with a disposed object as context: :: crash.Item.prototype.__mb(): Called assertFalse with 'true' Stack trace: qx.core.AssertionError.constructor://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.core.Assert.__bP://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.core.Assert.assertFalse://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:50202,qx.event.dispatch.Direct.dispatchEvent://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,.bP://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.event.Manager.dispatchEvent://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.event.Registration.fireNonBubblingEvent://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.core.Object.fireDataEvent://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,crash.Item._applyEventPropagation://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,crash.Item.setValue://demo.qooxdoo.org/5.0.1/playground/script/playground.js line 210 > Function:1,qx.core.Property.__y://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,qx.core.Property.executeOptimizedSetter://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:80833,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js line 210 > Function:44:1,...://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:99908,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:156885,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:161650,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:163523,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:641519,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:99908,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:658124,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:581803,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:401181,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:156885,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:161650,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:448582,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:439531,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:437855,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:448833,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:447902,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:51095,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:175029,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:99908,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:156885,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:161650,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:433186,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:333984,http://demo.qooxdoo.org/5.0.1/playground/script/playground.js:210:51095
    154952 playground.Application[18-0]: qx.core.AssertionError: Called assertFalse with 'true' 

I have a fix that seems to work so I'm making a PR. :smile:

**Comment by oetiker** [comment]
way to go!

**Comment by level420** [comment]
Fixed with e54d9737fcab73ffeeb6f35c528a21a95e1b1a79
