### ISSUE TITLE
qx.ui.form.VirtualSelectBox does not respond well to changeLocale

### ISSUE THREAD

**Issue by kreimer** [qooxdoo/qooxdoo#9002]
given the following (tested in current playground, chrome and ff):

`
var localeManager = qx.locale.Manager.getInstance();
localeManager.setLocale("en");
var locale = localeManager.getLocale();
this.debug("locale: " + locale);

// Create a button
var button1 = new qx.ui.form.Button(localeManager.getLocale());

// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(button1,
{
  left : 100,
  top  : 50
});

// Add an event listener
button1.addListener("execute", function(e) {
  if(localeManager.getLocale()==="en") {
    localeManager.setLocale("de");
  } else {
    localeManager.setLocale("en");
  }
  e.getCurrentTarget().setLabel(localeManager.getLocale());
}, this);

var translations_en = {
  "PUBLISHED_DESC" : "published (newest first)",
  "RENTAL_PRICE_ASC" : "rental price (cheaper first)",
  "RENTAL_PRICE_DESC" : "rental price (more expesive first)",
  "BUILT_AREA_ASC" : "built area (smaller first)",
  "BUILT_AREA_DESC" : "built area (bigger first)"
};

var translations_de = {
  "PUBLISHED_DESC" : "fecha de publicacion (nuevos primero)",
  "RENTAL_PRICE_ASC" : "precio de alquiler (mas baratos primero)",
  "RENTAL_PRICE_DESC" : "precio de alquiler (mas caros primero)",
  "BUILT_AREA_ASC" : "m2 (mas pequeños primero)",
  "BUILT_AREA_DESC" : "m2 (mas grandes primero)"
};

localeManager.addTranslation("en", translations_en);
localeManager.addTranslation("de", translations_de);

var items = new qx.data.Array();
items.push(this.tr("PUBLISHED_DESC"));
items.push(this.tr("RENTAL_PRICE_ASC"));
items.push(this.tr("RENTAL_PRICE_DESC"));
items.push(this.tr("BUILT_AREA_ASC"));
items.push(this.tr("BUILT_AREA_DESC"));

var selectBox = new qx.ui.form.VirtualSelectBox(items);

selectBox.getSelection().addListener("change", function(e) {
  this.debug(e.getData().added[0]+"");
  this.debug(e.getData().added[0].getMessageId());
}, this);

doc.add(selectBox, {
  left : 100,
  top  : 150
});
`

the button is for alternating the locale ["en", "de"]
the dropdown responds to the changeLocale... but the virtualSelectBox button seems not to..
the button of the virtualSelectBox translates ok on changeLocale, but as soon as you change selection, if backs to the previous lang

**Comment by kreimer** [comment]
horror-show-semi-workaround:
adding this converter to labelOptions just after creating the selectBox:

var selectBox = new qx.ui.form.VirtualSelectBox(items);
selectBox.setLabelOptions({  
  converter: function (data, model, source, target) {
    var tr = data.translate ? data.translate() : data;
    qx.log.Logger.debug("translated: " + tr);
    return tr;
  }
});


I consider this as half a workaround because in the getSelection()->"change" event I still receive the non-translated string (not that important to me as I am interested in the messageId, but still, suspicious)

**Comment by cajus** [comment]
I'm not able to reproduce the problem in playground - or I don't understand the Problem ;-)

Please check http://tinyurl.com/zolpsye

**Comment by kreimer** [comment]
steps to reproduce (once loaded in playground):
0) the example initializes the locale to "en" (ok)
1) the 'atom' child control and the dropdown items are shown in english (ok)
2) click the button, wich is intended to alternate between 'en' and 'de' locales. (is not relevant that I don't speak german, the entries are translated into spanish)
2.1) you can see that both 'atom' childcontrol and dropdown items are translated to 'german'. (ok)
3) you pick a different entry from the dropdown list, also known as, getSelection().addListener("change"...) event
3.1) then you see the dropdown items well translated to 'german' but the 'atom' control translated back to 'en'


this behavior I had it first in my app, and then I wrote the playground example to reproduce.

the following snippet is a workaround:
selectBox.setLabelOptions({

converter: function (data, model, source, target) {
var tr = data.translate ? data.translate() : data;
qx.log.Logger.debug("translated: " + tr);
return tr;
}
});

don't know exactly why.... but it works... both in the example, and back in my app.
I've tested this with chrome 50.0.2661.86 (64-bit)
and firefox 45.0.2

**Comment by cajus** [comment]
This is the real problem:

http://tinyurl.com/zsu4tmx

Will add a test and a fix.
