### ISSUE TITLE
Gestures stop working after some time in iOS

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9008]
If you do multiple gestures in a row, qx stops to react on them after multiple tries. To reproduce, open the mobile showcase on an iPad and go to the gesture demo where you can do some gestures on the HTML5 logo.

Pinch and rotate the logo multiple times. After some tries, the circles that visualize the touch are not cleaned up and the logo stops reacting on the gestures.

The following patch resolves the problem, but I don't know why exactly.

```
diff --git a/framework/source/class/qx/event/handler/PointerCore.js b/framework/source/class/qx/event/handler/PointerCore.js
index 0defb3a..a11b5e1 100644
--- a/framework/source/class/qx/event/handler/PointerCore.js
+++ b/framework/source/class/qx/event/handler/PointerCore.js
@@ -209,10 +209,10 @@ qx.Bootstrap.define("qx.event.handler.PointerCore", {
         // Firing pointer cancel for previously active touches.
         for (var i = this.__activeTouches.length - 1; i >= 0; i--) {
           var cancelEvent = new qx.event.type.dom.Pointer("pointercancel", domEvent, {
-            identifier: this.__activeTouches[i].identifier,
+            identifier: qx.core.Environment.get("os.name") === "ios" ? changedTouches[0].identifier : this.__activeTouches[i].identifier,
             target: domEvent.target,
             pointerType: "touch",
-            pointerId: this.__activeTouches[i].identifier + 2
+            pointerId: (qx.core.Environment.get("os.name") === "ios" ? changedTouches[0].identifier : this.__activeTouches[i].identifier) + 2
           });

           this._fireEvent(cancelEvent, "pointercancel", domEvent.target);
```

This should be inspected by someone who knows what is happening in there.

**Comment by level420** [comment]
@cajus verified on iPhone 6 with iOs 9.3.2

**Comment by level420** [comment]
There are no error messages on the console while bug occus when connected to safari running on OSX 10.11

**Comment by level420** [comment]
@cajus can you still reproduce this with iOs 10?
I've tried on an iPhone 6 with iOs 10.1.1 and could not reproduce this anymore.

**Comment by derrell** [comment]
I don't have any i-devices, nor know anything about gestures. Someone else please to take this on.
