### ISSUE TITLE
QxDyGraphs : first graph is not displayed

### ISSUE THREAD

**Issue by EricBourdin** [qooxdoo/qooxdoo#9011]
Dear Qooxdoo developpers,

I noticed a problem with the QxDyGraphs plugin.

When I create (and display) several qxdygraphs.Plot objects, the first one is never displayed.
Actually, you can see this problem on the demo page : http://demo.qooxdoo.org/contrib/demobrowser/#QxDyGraphs~trunk%2Fdefault%2F3.5%2Findex.html

For clarity, here is an annoted snapshot of the problem.

![image](https://cloud.githubusercontent.com/assets/19275295/15198632/db81e026-17d8-11e6-8071-5da920016fb5.png)

I tried to made some investigations on this problem.
First remark : where is the repo for QxDyGraphs ? The github reo at  https://github.com/qooxdoo-contrib/catalog/tree/master/contributions/QxDyGraphs looks empty to me.
However, the code source at sf.net seems to be the latest version (https://svn.code.sf.net/p/qooxdoo-contrib/code/trunk/qooxdoo-contrib/QxDyGraphs/trunk/)

Second remark. In my understanding the problem lies in the qxdygraphs.Plot.__loadScriptArr function.

This function calls addListenerOnce(scriptLoaded) to be notified of the loading of the dygraph script : 
```
            if (script){
                if (qxdygraphs.Plot.LOADING[script]){
                    qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){
                        this.__loadScriptArr(codeArr,handler);
                    },this);
                }
```
But at the first call the qxdygraphs.Plot.LOADING[script] will be evaluated to false and it doesn't subscribe to the event. Hence the notification never happens.

Here is a patch that fixes the problem 

```
Index: Plot.js
===================================================================
--- Plot.js     (révision 21902)
+++ Plot.js     (copie de travail)
@@ -113,13 +114,14 @@
          */
         __loadScriptArr: function(codeArr,handler){
             var script = codeArr.shift();
-            if (script){
-                if (qxdygraphs.Plot.LOADING[script]){
-                    qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){
+                       this.debug("__loadScriptArr");
+
+                       this.addListenerOnce('scriptLoaded',function(){
                         this.__loadScriptArr(codeArr,handler);
                     },this);
-                }
-                else if ( qxdygraphs.Plot.LOADED[script]){
+
+            if (script){
+                               if ( qxdygraphs.Plot.LOADED[script]){
                      this.__loadScriptArr(codeArr,handler);
                 }
                 else {
```

Thank you for this nice library.

**Comment by oetiker** [comment]
The repo for qxdygraphs actually is still on SF ... the  github thing is just the catalog for contributions ... not the actual repo ... handling contribs is yet another thing we have to clean up. 

Regarding your patch ... it nugged me in the right direction. I would say it should be like this:

```patch
         __loadScriptArr: function(codeArr,handler){
             var script = codeArr.shift();
-            if (script){
-                if (qxdygraphs.Plot.LOADING[script]){
-                    qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){
+            if (!script){
+                handler();
+                return;
+            }
+            if ( qxdygraphs.Plot.LOADED[script]){
+                /* got this script, go for the next in the array */
+                this.__loadScriptArr(codeArr,handler);
+                return;
+            }
+
+            if (qxdygraphs.Plot.LOADING[script]){
+                /* but it is already loading, so lets listen for it to arrive */
+                qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){
+                    this.__loadScriptArr(codeArr,handler);
+                },this);
+                return;
+            }
+
+            /* the script is not loaded nor loading, so we are going to */
+            qxdygraphs.Plot.LOADING[script] = this;
+            this.addListenerOnce('scriptLoaded',function(){
+                this.__loadScriptArr(codeArr,handler);
+            },this);
+
+            var src = qx.util.ResourceManager.getInstance().toUri("dygraphs/"+script);
+
+            if (qx.io.ScriptLoader){
+                var sl = new qx.io.ScriptLoader();
+                sl.load(src, function(status){
+                    if (status == 'success'){
+                        // this.debug("Dynamically loaded "+src+": "+status);
                         this.__loadScriptArr(codeArr,handler);
-                    },this);
-                }
-                else if ( qxdygraphs.Plot.LOADED[script]){
-                     this.__loadScriptArr(codeArr,handler);
-                }
-                else {
-                    qxdygraphs.Plot.LOADING[script] = this;
-                    var src = qx.util.ResourceManager.getInstance().toUri("dygraphs/"+script);
-                    if (qx.io.ScriptLoader){
-                        var sl = new qx.io.ScriptLoader();
-                        sl.load(src, function(status){
-                            if (status == 'success'){
-                                // this.debug("Dynamically loaded "+src+": "+status);
-                                this.__loadScriptArr(codeArr,handler);
-                                qxdygraphs.Plot.LOADED[script] = true;
-                            }
-                            qxdygraphs.Plot.LOADING[script] = null;
-                            this.fireDataEvent('scriptLoaded',script);
-                        },this);
+                        qxdygraphs.Plot.LOADED[script] = true;
                     }
-                    else {
-                        var req = new qx.bom.request.Script();
-                        req.on('load',function() {
-                            qxdygraphs.Plot.LOADED[script] = true;
-                            qxdygraphs.Plot.LOADING[script] = null;   
-                            this.fireDataEvent('scriptLoaded',script);
-                        },this); 
-                        req.open("GET", src);
-                        req.send();
-                    }
-                }
-            } else {
-                handler();
+                    delete qxdygraphs.Plot.LOADING[script];
+                    this.fireDataEvent('scriptLoaded',script);
+                },this);
             }
+            else {
+                var req = new qx.bom.request.Script();
+                req.on('load',function() {
+                    qxdygraphs.Plot.LOADED[script] = true;
+                    delete qxdygraphs.Plot.LOADING[script];
+                    this.fireDataEvent('scriptLoaded',script);
+                },this);
+                req.open("GET", src);
+                req.send();
+            }
         },
````

new version is comited to trunk ... oh and btw, also jqplot got the same update

**Comment by EricBourdin** [comment]
Thank you very much Tobias.

I am glad to help on this project.

I will checkout your patch and test it tonight.

Have fun

Eric

2016-05-12 9:02 GMT+02:00 Tobias Oetiker <notifications@github.com>:

> The repo for qxdygraphs actually is still on SF ... the github thing is
> just the catalog for contributions ... not the actual repo ... handling
> contribs is yet another thing we have to clean up.
>
> Regarding your patch ... it nugged me in the right direction. I would say
> it should be like this:
>
>          __loadScriptArr: function(codeArr,handler){
>              var script = codeArr.shift();-            if (script){-                if (qxdygraphs.Plot.LOADING[script]){-                    qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){+            if (!script){+                handler();+                return;+            }+            if ( qxdygraphs.Plot.LOADED[script]){+                /* got this script, go for the next in the array */+                this.__loadScriptArr(codeArr,handler);+                return;+            }++            if (qxdygraphs.Plot.LOADING[script]){+                /* but it is already loading, so lets listen for it to arrive */+                qxdygraphs.Plot.LOADING[script].addListenerOnce('scriptLoaded',function(){+                    this.__loadScriptArr(codeArr,handler);+                },this);+                return;+            }++            /* the script is not loaded nor loading, so we are going to */+            qxdygraphs.Plot.LOADING[script] = this;+            this.addListenerOnce('scriptLoaded',function(){+                this.__loadScriptArr(codeArr,handler);+            },this);++            var src = qx.util.ResourceManager.getInstance().toUri("dygraphs/"+script);++            if (qx.io.ScriptLoader){+                var sl = new qx.io.ScriptLoader();+                sl.load(src, function(status){+                    if (status == 'success'){+                        // this.debug("Dynamically loaded "+src+": "+status);
>                          this.__loadScriptArr(codeArr,handler);-                    },this);-                }-                else if ( qxdygraphs.Plot.LOADED[script]){-                     this.__loadScriptArr(codeArr,handler);-                }-                else {-                    qxdygraphs.Plot.LOADING[script] = this;-                    var src = qx.util.ResourceManager.getInstance().toUri("dygraphs/"+script);-                    if (qx.io.ScriptLoader){-                        var sl = new qx.io.ScriptLoader();-                        sl.load(src, function(status){-                            if (status == 'success'){-                                // this.debug("Dynamically loaded "+src+": "+status);-                                this.__loadScriptArr(codeArr,handler);-                                qxdygraphs.Plot.LOADED[script] = true;-                            }-                            qxdygraphs.Plot.LOADING[script] = null;-                            this.fireDataEvent('scriptLoaded',script);-                        },this);+                        qxdygraphs.Plot.LOADED[script] = true;
>                      }-                    else {-                        var req = new qx.bom.request.Script();-                        req.on('load',function() {-                            qxdygraphs.Plot.LOADED[script] = true;-                            qxdygraphs.Plot.LOADING[script] = null;   -                            this.fireDataEvent('scriptLoaded',script);-                        },this); -                        req.open("GET", src);-                        req.send();-                    }-                }-            } else {-                handler();+                    delete qxdygraphs.Plot.LOADING[script];+                    this.fireDataEvent('scriptLoaded',script);+                },this);
>              }+            else {+                var req = new qx.bom.request.Script();+                req.on('load',function() {+                    qxdygraphs.Plot.LOADED[script] = true;+                    delete qxdygraphs.Plot.LOADING[script];+                    this.fireDataEvent('scriptLoaded',script);+                },this);+                req.open("GET", src);+                req.send();+            }
>          },
>
> new version is comited to trunk ... oh and btw, also jqplot got the same
> update
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/qooxdoo/qooxdoo/issues/9011#issuecomment-218676288>
>



-- 
Eric Bourdin
