### ISSUE TITLE
karma documentation

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9019]
add notes on how to use karma for running the test suit to

https://github.com/qooxdoo/qooxdoo/blob/master/documentation/manual/source/pages/development/frame_apps_testrunner.rst

**Comment by cboulanger** [comment]
Do we need to do this or will we move away from remote testing to local headless browsers?

**Comment by derrell** [comment]
There are two very different types of testing. Server apps need testing, and those should be tested using the same NodeJS that those servers will run as during use. A browser, headless or not, can't test NodeJS apps, when those apps use things like `Buffer`s.

**Comment by oetiker** [comment]
I have unfortunately no idea about karma :) but from my pov this can be closed since we have other means of testing now
