### ISSUE TITLE
Decorator styles applied inconsistently

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9034]
When several mixins apply styles that overlap, the generated CSS needs to be applied in a suitable order; for example, the MBackgroundImage mixin applies the `background` style and MBackgroundColor applies the `background-color` style.

I've found that in recent versions of Qx on Chrome 50/Mac, the CSS string has `background-color` *before* `background` and Chrome compiles this into rules where `background-color` is completely ignored.  This can be seen by debugging the code and inspecting the CSSRule immediately after it has been added to the Stylesheet.

The same version of Chrome running an app with an older version of Qx 5.0.1 does not exhibit this behaviour, because it sets the `background` style before the `background-color`.

AIUI Chrome is working correctly, but Qx is not enforcing an order so is unpredictable in its results.

There is a quick fix by enforcing the ordering of style keys, please see this commit https://github.com/johnspackman/qooxdoo/commit/b9a5ed2ed4d66387b49e367a39b9979114f603a9 for a working example

It could be argued that the correct implementation is to merge MBackgroundImage and MBackgroundColor into a single mixin that understands how to completely and accurately generate a single `background` style.

As this is a fundamental change, we should consider which is the safest approach - is there a situation where simplistic alphabetical ordering of CSS style names could simply cause a different problem?

**Comment by oetiker** [comment]
that does look like a neat solution to me. especially since it solves the problem in a rather generic way.

**Comment by level420** [comment]
Fixed with https://github.com/qooxdoo/qooxdoo/commit/1ddf54d11b8c66bb1ba363cac532bd1cddac0c2f
