### ISSUE TITLE
qx.lang.Type.isNumber(NaN) returns true

### ISSUE THREAD

**Issue by voger** [qooxdoo/qooxdoo#9041]
If we check if NaN is a Number with qx.lang.Type.isNumber it returns true because `typeof NaN` is number. Still, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) 

> The global NaN property is a value representing Not-A-Number.

So intuitively when someone checks qx.lang.Type.isNumber(NaN) expects false.

[Here is the relevant playground example](http://tinyurl.com/hlx35wl)

**Comment by voger** [comment]
The behavior is intended. NaN is of type number so it is a number who is not a number.

**Comment by derrell** [comment]
I still think this is a valid and useful change.

**Comment by derrell** [comment]
This PR creates, from my perspective, the correct behavior, but it changes behavior that the tests test for. We should therefore change this at a major version bump.

**Comment by oetiker** [comment]
In my understanding isNumber refers to something being NOT a string ... so it is about the Type of the variable not about its content ... and NaN is a legal value for floating point variables, same as INF and -INF ... so unless you would exclude them as well, I don't see that this is actually wrong.
