### ISSUE TITLE
grid layout for mobile

### ISSUE THREAD

**Issue by oxiao** [qooxdoo/qooxdoo#9047]
has it stopped for mobile sdk? it's poor of mobile layouts, components and themes  to be choosed in app's development. yes, there are more morden frameworks for mobile developing, but i think qooxdoo is better for me.

**Comment by oetiker** [comment]
Note that you can use regular qooxdoo to build mobile applications too ! It currently just does not have any specialized mobile optimized widgets ...

**Comment by oxiao** [comment]
so...! it seems there is a long time to waiting for mobile update. i'll try my best to go on. :(

**Comment by level420** [comment]
@oxiao please report here what you find on your way, positive or negative. And of course you can take the chance to help us improve qooxdoo towards your needs by participating, especially by contributing code using pull requests.

**Comment by oxiao** [comment]
@level420 ok, my pleasure! thanks much!
