### ISSUE TITLE
shift do not work in table editor

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9050]
In the current version you can not enter Shift Char, e.g. A. Only with caps lock on this works.
This is confirmed for Windows, OSX and Linux for all browsers.

See gitter talk from 14.06.2016 22:05

Code to reproduce from playground example:

function createRandomRows(rowCount) {
  var rowData = [];
  var now = new Date().getTime();
  var dateRange = 400 * 24 * 60 * 60 * 1000; // 400 days
  var nextId = 0;
  for (var row = 0; row < rowCount; row++) {
    var date = new Date(now + Math.random() * dateRange - dateRange / 2);
    rowData.push([ nextId++, Math.random() * 10000, date, (Math.random() > 0.5) ]);
  }
  return rowData;
}

// window
var win = new qx.ui.window.Window("Table").set({
  layout : new qx.ui.layout.Grow(),
  allowClose: false,
  allowMinimize: false,
  contentPadding: 0
});
this.getRoot().add(win);
win.moveTo(30, 40);
win.open();

// table model
var tableModel = new qx.ui.table.model.Simple();
tableModel.setColumns([ "ID", "A number", "A date", "Boolean" ]);
tableModel.setData(createRandomRows(1000));

// make second column editable
tableModel.setColumnEditable(1, true);

// table
var table = new qx.ui.table.Table(tableModel).set({
  decorator: null
});
win.add(table);

var tcm = table.getTableColumnModel();

// Display a checkbox in column 3
tcm.setDataCellRenderer(3, new qx.ui.table.cellrenderer.Boolean());

// use a different header renderer
tcm.setHeaderCellRenderer(2, new qx.ui.table.headerrenderer.Icon("icon/16/apps/office-calendar.png", "A date"));

**Comment by hkollmann** [comment]
I try to debug down to browser events.
 The key down event is not generated with shift pressed.

**Comment by level420** [comment]
@hkollmann you could use current master playground at http://qooxdoo.github.io/devel/playground/

**Comment by level420** [comment]
but confirmed by @derrell

**Comment by level420** [comment]
also confirmed on windows 7 with chrome 52, IE 1, FF 48beta

example by @hkollmann in current master playground: http://tinyurl.com/h3sblg3

**Comment by hkollmann** [comment]
This is just the table demo in the playground!
http://qooxdoo.github.io/devel/playground/#Table-ria

**Comment by hkollmann** [comment]
Just played a round with git bisect - This is the result:

$ git bisect good
c1883d4fd14b2d12393cc0ebbd7e8148f2dea74f is the first bad commit
commit c1883d4fd14b2d12393cc0ebbd7e8148f2dea74f
Author: petitben <b.collignon@mastriasoft.eu>
Date:   Sat Apr 30 21:17:12 2016 +0200

    Fix BZ#9213 - use keydown rather than keyup

    keydown is more suitable globally (regarding arrows navigation for instance)

:040000 040000 0ef3995ebdf4164feb67050149def96ffbdee6da 0785f7f16fe1c98b93d306a9417bfe2fe4c78786 M      framework

**Comment by hkollmann** [comment]
It's merged! Thank you.
