### ISSUE TITLE
Cannot override a setter function like setWidth

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9053]
A question on SO http://stackoverflow.com/questions/37832341/cannot-override-a-setter-function-like-setwidth asks why setter functions cannot be overridden; this issue is to discuss the pros and cons of whether this is a bug or a feature.

My perspective is that any non-private function in a base class can be overridden by a derived class, and this should include auto generated functions which are created to implement properties.  The justification for this is that 

(1) although most properties are implemented via the ```properties``` section of a class, many Qooxdoo classes implement properties themselves - i.e. they have accessors and events, but there is no formal property defined.  They do this because sometimes they do not want the property value changed, ever, so they implement the property manually so that the setXxx method manipulates a value instead of replacing it.  For example `qx.ui.core.MSingleSelectionHandling` and `MultiSelectionHandling` have setSelection, which change the array behind the selection pseudo property rather than replacing it (this is a really cool and useful feature)

(2) when binding to properties, Qooxdoo judges whether a property is a bindable property by a kind of feature detection, rather than whether there is a formal property defined - EG is there a setXxx, getXxx, and a changeXxx event.

(3) given that it is perfectly valid to manually implement setXxx/getXxx/changeXxxx in order to have a property, it is valid to override those methods in derived classes.  If the implementation of the property changes (to be formally defined via properties) then derived code is broken, despite zero visible changes.  *How* the property is defined is not part of the specification - the “how” is effectively a private implementation detail, and the consumer of that class should not be broken by changes in private implementation.

(4) it is impossible to reliably distinguish functions which are property accessors from those which are explicitly defined - just because a function starts “set”, “get”, or “is” should not mean that it has special meaning to the OO concept of classes, e.g. it should definitely not mean that it cannot be overridden.

(5) what is the nature of an auto-generated function and what makes it special?  For example, If someone writes a babel plugin that generates methods to implement new features, are they overridable?  And how would the user, or the framework, know that they cannot be overridden?  What if that generated method overrides some other base class method that was previously manually defined?

I did a search of the Qooxdoo code for setXxx methods that are manually defined (reg ex of ```^\s*set[\w]+\s*:```) and found 591 instances; that reg ex might need improving but at a quick glance thats a lot of properties accessors that can be legitimately overridden.

I understand that overridding accessors suggests that there is a design flaw, but IMHO that doesn't mean it's always invalid - overriding a property accessor could generate a warning (definitely a lint message!).

**Comment by oetiker** [comment]
you are listing here why you think it should work ... and it sounds plausible to me ... I can't see why it should 'not' work

**Comment by johnspackman** [comment]
in that SO example, the functions are never called (so it's a bug in the example rather than a qooxdoo issue) but it is perfectly possible to override methods in the base class which happen to be property accessors.

But - the playground has qx.debug==false and this means that qx.Class.define will not check whether methods are overriding base class methods which are property accessors; in a source build, an exception is raised.

**Comment by hkollmann** [comment]
Could we remove this exception?

**Comment by johnspackman** [comment]
I think it's valid to do so, yes.

**Comment by level420** [comment]
Basically I would like to be able to override all those autogenerated methods (setXxx, getXxx,...) but without loosing functionality currently offered by the property system.

If someone desires to override setWidth and forgets to call the superclasses setWidth, then the upstream class hierarchy functionality is broken, but this also may be by intention.

**Comment by kreimer** [comment]
I'm with Dietrich on that. You may have the freedom to subclass and override and, as it go for any overriding, you must call to superclass if you mean to inherit the behaviour. What I'm not sure.. is what happens in the same class.. you define a propery P in class X but want  to override 'this' autogenerated setP, you cannot call this.base(arguments) because P is in this class.

**Comment by johnspackman** [comment]
@level420 yes, just like any other function.  They could override the setter and getter and not pass up to the superclass at all, but whether that is *actually* valid depends on the class and its implementation

@kreimer you can't override setWidth in the class where you define the "width" property, it would be the same as manually defining a setWidth twice.  In that case, you'd be forced to manually code the whole setWidth, getWidth, changeWidth etc and not define a proper property

**Comment by kreimer** [comment]
exactly! I meant what it would or must be desirable. But still.. I'm not sure at all

**Comment by johnspackman** [comment]
I think there is an argument for property definitions to optionally have a set and get method explicitly defined, ie a way for the implementation of set/get to be completely controlled; i.e. at the moment, all 591 of those manually defined properties are not "real" properties, because the get/set cannot be completely controlled.

If we *were* able to control get/set and change those "pseudo" properties into "real" properties, then we could make reflection work properly and there would be the possibility of using Object.defineProperty, which could be really useful and cool.

**Comment by hkollmann** [comment]
I played a Little bit with the source and removed the throwing the exception in Class.js, line 1333.
Then i start a tittle test:
'qx.Class.define("test.Label",
{
  extend : qx.ui.basic.Label,
  members : {
      setValue: function(val) {
          qx.log.Logger.info("setValue")
          return this.base(arguments, val + "99");
      }
  }
});
'

and test application:
'
qx.Class.define("test.Application",
{
  extend : qx.application.Standalone,
  members : {
    main : function()
    {
      this.base(arguments);
      var label = new test.Label();
      var application_root = this.getRoot();
      application_root.add(label);
      label.setValue("test");
  }
  }
});
'
Starting the application with source-all in the browser gives an endless rekursive call of test.Label.setValue from Property.js, __unwrapFunctionFromCode, line 742:
' else if (qx.core.Environment.get("qx.debug")) {
        return instance[store].apply(instance, args);
'
Starting with build applications work as expected.

So simple removing the exeption will not work. Any ideas why?

**Comment by johnspackman** [comment]
it's because property accessors are created on demand, and this.base refers to the accessor - and if the accessor has not get been created yet, you get infinite loops.

This PR will fix it https://github.com/qooxdoo/qooxdoo/pull/9060

**Comment by hkollmann** [comment]
Puh - much more work than i expected. Great stuff 👏👏👏👏

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/commit/13c4c4f231158db967c54edf76edd526d3d23308
