### ISSUE TITLE
[Table] Cannot filter if target is not a column

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9066]
Hi,

We have qx.ui.table.model.Filtered class which allow to filter table rows by several ways. But it is not possible to filter if the target is not a column.

For example, look this example :  http://tinyurl.com/z5a4uvy

**Comment by slachtar** [comment]
Hello,
as far as I know, id has to be a column and could be set invisible,
otherwise you cannot filter by id.
Regards

On Tue, Jun 21, 2016 at 7:47 AM, William Oprandi <notifications@github.com>
wrote:

> Hi,
>
> We have qx.ui.table.model.Filtered class which allow to filter table rows
> by several ways. But it is not possible to filter if the target is not a
> column.
>
> For example, look this example : http://tinyurl.com/zr7xu98
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qooxdoo/qooxdoo/issues/9066>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACaj6ma48l5ZMJts4Wj-jK8A7_dcDnhvks5qN4jsgaJpZM4I6aMP>
> .
>



-- 
Slah Lachtar
Tel. (+216) 98 221 575

**Comment by level420** [comment]
I'm here with @slachter : the filtered table model filters on columns, not on models. The solution is to create an invisible column for the questionable attribute in the model.

**Comment by woprandi** [comment]
Didn't know the `setColumnInvisible` method. Lack of documentation of this subject I think.

**Comment by oetiker** [comment]
@woprandi so please, provide a patch for the documentation !

**Comment by level420** [comment]
@woprandi it is documented at http://qooxdoo.github.io/devel/api/#qx.ui.table.columnmodel.Basic~setColumnVisible!method_public

**Comment by hkollmann** [comment]
It's not do simple as described. The table do not have setColumnVisible method. You Need the tablecolumn model:
var tcm = table.getTableColumnModel();
tcm.setColumnVisible(colNr, false);

**Comment by woprandi** [comment]
@level420 @oetiker After searching I found the method in the API (but hard to find) and it lacks maybe a example in the demo browser. I use Table for 2 years and I didn't know the method before. I'll write an demo and post a PR !

**Comment by oetiker** [comment]
@woprandi often in the header of a class description in the api browser there is some sample code ... you may want to add to that ...

**Comment by woprandi** [comment]
@oetiker Do you prefer this rather than a demo in the demo browser ?

**Comment by oetiker** [comment]
I personally like the api docu a lot and would love to see many more examples in there ... 
this is not to say that an example in the demo browser would be bad ... they are both great ...  do both ! :-)

**Comment by woprandi** [comment]
I opened a PR https://github.com/qooxdoo/qooxdoo/pull/9067
