### ISSUE TITLE
Poor filter performance on Table

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9068]
The `qx.ui.table.model.Filtered` offers some methods to filter table rows (`addRegex`, `addNotRegex`, `addNumericFilter`, ...) but performances are poor. Basically, value are tested row by row instead of use `Array.filter()` method (which is very efficient).
You can have an idea of the difference with this example : http://tinyurl.com/jubueha

**Comment by schnepe2** [comment]
Nice find!
I would love to see these kind of information(s) on the qooxdoo main page if it isn't fixed.
Those "tricks" or "do's & dont's" need to be accessed more centralized, I think.

**Comment by woprandi** [comment]
I don't know which is the best strategy to adopt but my opinion is to make deprecated methods which add filter (to avoid API break) and advise to use `Array.filter` instead. We could maybe add a wrapper in the class for that. I'd like to have another opinions

**Comment by oetiker** [comment]
why can't the implementation be fixed ?

**Comment by woprandi** [comment]
It would need time to identify what take so much time in the `applyFilters` method.
But the idea of adding filters to a array and apply them is for me a bad idea because it is limited (in addition to poor performance). Each filter is limited to an unique column, you cannot filter based on several columns. It's like do a SQL request without `AND` keyword.
It's much powerful (and easier) to let user write his own filter method (like the `IListDelegate` interface does).

**Comment by oetiker** [comment]
so maybe you would like to amend the API docu ?

**Comment by woprandi** [comment]
After some analyse, the performance issue seems to be the [`hideRows`](https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/table/model/Filtered.js#L410) method. I'll continue my analyse later

**Comment by woprandi** [comment]
The main problem is the `hideRows` method is called too many times (in my example, more than 20k times  !)
https://github.com/qooxdoo/qooxdoo/blob/release_5_0_1/framework/source/class/qx/ui/table/model/Filtered.js#L330

**Comment by oetiker** [comment]
also having the 'case' inside the loop does not make much sense ... after all the comparison operation does not change while looping

**Comment by woprandi** [comment]
I'll offer a PR with my current change, it seems ok but I need to see if I didn't break something

**Comment by woprandi** [comment]
https://github.com/qooxdoo/qooxdoo/pull/9087

**Comment by woprandi** [comment]
We shoud maybe deprecated the `Filtered` class since performance remains bad despite https://github.com/qooxdoo/qooxdoo/pull/9088 and promote to just use `filter` method on the array

**Comment by oetiker** [comment]
you could create a PR adding deprecation and a sample to the documentation of the class

**Comment by level420** [comment]
@woprandi how is the state of this issue? Could we close this as PR #9088 was merged?

**Comment by woprandi** [comment]
@level42 Sorry I forgot to close this issue ! Closing...
