### ISSUE TITLE
"change" event fired too much on VirtualSelectBox

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9071]
Hi,

Check this example : http://tinyurl.com/hjol7rx
The event "change" is fired 3 times instead of once

**Comment by zaucker** [comment]
The three change events happen upon the call to setModel(). Once all is
setup, there is only on event per selection change.

If you add the listener after the setModel() call, the three initial events
are ignored (obviously).

I guess the setModel() generates an event for each element added to the
model. I am not sure if this is useful or not or a bug.

On Mon, 27 Jun 2016, William Oprandi wrote:

> Check this example : http://tinyurl.com/hjol7rx
> The event "change" is fired 3 times instead of once

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by slachtar** [comment]
I did a lot of hacking to avoid such problem (event being generated with
every element in the model).
The change event should be generated only once.

On Mon, Jun 27, 2016 at 4:19 PM, Fritz Zaucker <notifications@github.com>
wrote:

> The three change events happen upon the call to setModel(). Once all is
> setup, there is only on event per selection change.
>
> If you add the listener after the setModel() call, the three initial events
> are ignored (obviously).
>
> I guess the setModel() generates an event for each element added to the
> model. I am not sure if this is useful or not or a bug.
>
> On Mon, 27 Jun 2016, William Oprandi wrote:
>
> > Check this example : http://tinyurl.com/hjol7rx
> > The event "change" is fired 3 times instead of once
>
> --
> Oetiker+Partner AG tel: +41 62 775 9903 (direct)
> Fritz Zaucker +41 62 775 9900 (switch board)
> Aarweg 15 +41 79 675 0630 (mobile)
> CH-4600 Olten fax: +41 62 775 9905
> Schweiz web: www.oetiker.ch
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qooxdoo/qooxdoo/issues/9071#issuecomment-228778081>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACaj6iHJY0odlnJkEmV0OaezWfdpLC6kks5qP-oUgaJpZM4I_MkA>
> .
>



-- 
Slah Lachtar
Tel. (+216) 98 221 575

**Comment by woprandi** [comment]
@zaucker Yeah I could do that but it's not very conceivable since I need a fired event for the default selection.

**Comment by johnspackman** [comment]
IMHO this is a bug because the selection property is a `qx.data.Array` (according to the API docs anyway), and yet the first two `change` events which are fired do not confirm to the specs for `qx.data.Array`'s `change` event.  For example, in this slightly modified version of Williams example http://tinyurl.com/gpow5tg the log output shows that the event's Data property is empty:

```
324314 qx.application.Standalone[510-0]: selection changed: {}
2621370 qx.application.Standalone[510-0]: selection changed: {}
2623352 qx.application.Standalone[510-0]: selection changed: {"start":0,"end":0,"type":"remove","removed":[{"$$hash":"760-0","__bb":"760-0","$$initialized":true,"$$user_label":"a"}],"added":[]}
```

**Comment by johnspackman** [comment]
it looks like this is fixed in the current master - prior to https://github.com/qooxdoo/qooxdoo/commit/43d7e9172340d51a67c7743962ea6693cad8d942 the VirtualDropDown was firing the events manually

**Comment by woprandi** [comment]
@johnspackman Looks nice, but I can't find the master playground URL to check

**Comment by johnspackman** [comment]
Hi,

Thank you for your email - please note that I am on annual holiday from Thursday June 30th until July 6th inclusive  
 If you have a an emergency support issue, please describe your issue in detail in email and then send a text message to my mobile number.

Regards
John Spackman

**Comment by johnspackman** [comment]
I'd forgotten that there is one, cajus set one up on http://qooxdoo.github.io/devel/playground

I've just checked though with http://tinyurl.com/hm7p8qa and while it's an improvement it's still wrong.  Here's the output:

```
021947 qx.application.Standalone[493-0]: selection changed: {"start":0,"end":1,"type":"add","added":[{"$$hash":"636-0","__bR":"636-0","$$initialized":true,"$$user_label":"a"}],"removed":[]}
021950 qx.application.Standalone[493-0]: selection changed: {"start":0,"end":1,"type":"add","added":[{"$$hash":"636-0","__bR":"636-0","$$initialized":true,"$$user_label":"a"}],"removed":[]}
021950 qx.application.Standalone[493-0]: selection changed: {"start":0,"end":0,"type":"remove","removed":[{"$$hash":"636-0","__bR":"636-0","$$initialized":true,"$$user_label":"a"}],"added":[]}
```

it shows that "a" was added twice and then removed, when there should be one added for "a" and that's it.

**Comment by woprandi** [comment]
Strange, I applied the patch for my app and event fires only once now.

**Comment by johnspackman** [comment]
I found that sample app triggers the problem on master

**Comment by woprandi** [comment]
Thanks for your help

**Comment by level420** [comment]
Fixed with https://github.com/qooxdoo/qooxdoo/commit/3bc6ebe608bbe4270a467d8fc1d1f8c13ee3b6b4
