### ISSUE TITLE
can't create webjar

### ISSUE THREAD

**Issue by AlexanderRay** [qooxdoo/qooxdoo#9072]
Hi,

it is not possible to create a [npm webjar](http://www.webjars.org/npm), because of wrong license info:

*Failed! No valid licenses found. Detected licenses: LGPL / EPL  The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.*

I think that license property in [package.json](https://github.com/qooxdoo/qooxdoo/blob/master/package.json)

```
"license": "LGPL/EPL",
```

should be an array

```
"licenses": ["LGPL", "EPL"],
```

**Comment by johnspackman** [comment]
Thanks for the report; please could you create a pull request and we'll include the fix in the next release?

**Comment by AlexanderRay** [comment]
Done

**Comment by level420** [comment]
Fixed with https://github.com/qooxdoo/qooxdoo/commit/d813659d3a40e78ca492335ef306137ac86e0e31
