### ISSUE TITLE
STZ-IDA / Andreas Junghans (@lucidcake)

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9080]
get permission for MIT license change from 2006 STZ-IDA, Germany, http://www.stz-ida.de / Andreas Junghans (@lucidcake)

**Comment by oetiker** [comment]
contact: webmaster@lucid-cake.net

**Comment by level420** [comment]
Contacted Andreas Junghans via xing and asked him for assistence

**Comment by level420** [comment]
Answer form Andreas Junghans via xing (originally in german, translated poorly to english):

_Hello Dietrich,

from my side there is nothink speaks against the license change .

regarding STZ-IDA I can not say much. We (Til and I) had not contact the them for longer time. The STZ-IDA-homepage does now forward to a small partner page at:

http://www.steinbeis.de/de/experten/steinbeis-unternehmen-und-partner/detail.html?tx_z7suprofiles_detail%5bprofile%5d=1187&cHash=ec02e2be1cd27f2f3ef350251646ee84%23legalnote

It would be best to contact Prof. Gremminger (for contact see the link above).

Regards,
Andreas_

**Comment by level420** [comment]
Sent an email to Steinbeis ( SU0060@stw.de ) to ask for the license change agreement.

**Comment by level420** [comment]
Sent another email to the personal email address of Prof. Gremminger

**Comment by level420** [comment]
No reaction till now

**Comment by zaucker** [comment]
Called +49 721 9683220, no answer.

**Comment by level420** [comment]
What about the phone numbers in http://www.steinbeis.de/de/footer/impressum.html ?

**Comment by zaucker** [comment]
No answer on either number ...

**Comment by zaucker** [comment]
As we don't seem to be able to reach this organization, can anybody tell how
much of the original code from lucidcake is left in this file?

On Wed, 20 Jul 2016, Dietrich Streifert wrote:

> What about the phone numbers in http://www.steinbeis.de/de/footer/impressum.html ?

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by cajus** [comment]
Maybe the domain owner knows something on how to contact anyone there?

> [Tech-C]
> Type: PERSON
> Name: Frank Roessler
> Organisation: indas internet- und netzwerkdienstleistungen
> Address: Supperstr. 3
> PostalCode: 70565
> City: Stuttgart
> CountryCode: DE
> Phone: +497111618969
> Fax: +497111618965
> Email: info@indas.de
> Changed: 2006-06-01T14:46:47+02:00

**Comment by zaucker** [comment]
The domain stz-ida.de is registered through 1blu.de. Their support person
confirmed that the WHOIS-entry for the domain owner ist correct. The owner
is Jan Gremminger (presumably a son of Prof Klaus Gremminger?) under the
same postal address as listed on the stw.de page.

There is not much info to be found about Jan Gremminger through Google.  The
most promising could be him being mentioned for getting a stipend to study
at http://mi.hs-offenburg.de/ ...  I will try to find out about him through
their secretary tomorrow (German privacy laws might make this difficult).

I have sent an eMail to another professor at Hochschule Karlsruhe who is
listed as contact of Prof Gremminger in XING.

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by zaucker** [comment]
Got the direct eMail-adress (though @stz-ida.de) of the domain owner and sent an eMail.

**Comment by hkollmann** [comment]
Done with #9399
