### ISSUE TITLE
2008 Dihedrals.com, http://www.dihedrals.com / Chris Banford (zermattchris)

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9082]
Get Permission from 2008 Dihedrals.com, http://www.dihedrals.com / Chris Banford (zermattchris)
for MIT License Change

**Comment by oetiker** [comment]
@ZermattChris

**Comment by level420** [comment]
contacted Chris Banford via linkedin

**Comment by level420** [comment]
@ZermattChris Thank you!
If you like, you're invited to participate!
See our chat at https://gitter.im/qooxdoo/qooxdoo
