### ISSUE TITLE
OpenHex SPRL, http://www.openhex.org / Dirk Wellmann (dw(at)piponline.net)

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9083]
Get permission from 2007 OpenHex SPRL, http://www.openhex.org / Dirk Wellmann (dw(at)piponline.net) for MIT license change

**Comment by oetiker** [comment]
is this @OpenHex ?

**Comment by level420** [comment]
Failed to contact Dirk Wellman by the named email address

**Comment by level420** [comment]
Contacted Dirk Wellmann via xing

**Comment by dwellmann** [comment]
Hi there, sorry for comming back to you so late!

Yes I will give my permission to Change to MIT-Licence.

**Comment by level420** [comment]
@dwellmann Thank you!
