### ISSUE TITLE
Tartan Solutions, Inc, http://www.tartansolutions.com, Dan Hummon

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9084]
Get permission from 2007 by Tartan Solutions, Inc, http://www.tartansolutions.com, Dan Hummon for license change.

**Comment by oetiker** [comment]
contact info@tartansolutions.com

**Comment by level420** [comment]
@inviscid , @rea725 Please have a look at this issue.

qooxdoo needs to undergo a license change from EPL/LGPL to MIT license.

It would be very kind if someone at Tartan Solutions will give us the permission to move from EPL/LGPL to MIT while the copyright notice will stay as is.

Thank you

**Comment by swernerx** [comment]
You can try to contact Michael directly: Michael Rea <michael.rea@tartansolutions.com>

**Comment by inviscid** [comment]
Dietrich,

Yes.  Happy to accept MIT license change.  We love Qooxdoo by the way!

Best,

Paul

On Mon, Jul 11, 2016 at 9:48 AM, Dietrich Streifert <
notifications@github.com> wrote:

> @inviscid <https://github.com/inviscid> , @rea725
> <https://github.com/rea725> Please have a look at this issue.
>
> qooxdoo needs to undergo a license change from EPL/LGPL to MIT license.
>
> It would be very kind if someone at Tartan Solutions will give us the
> permission to move from EPL/LGPL to MIT while the copyright notice will
> stay as is.
>
> Thank you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/qooxdoo/qooxdoo/issues/9084#issuecomment-231757081>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKFQtHZ9gj_KbRm3JCoTTzk_-t2_nmlks5qUle6gaJpZM4JE3qK>
> .
>



-- 
_____________________
*Paul Morel*
Managing Director
Tartan Solutions, Inc

*M*  +1 414.232.1787
*E*  paul.morel@tartansolutions.com
<https://tartansolutions.com>

**Comment by level420** [comment]
Hey Paul!

Great! Thank you!

If you like, please participate in our qooxdoo chat https://gitter.im/qooxdoo/qooxdoo
