### ISSUE TITLE
«escape» and «unescape» Js function are deprecated

### ISSUE THREAD

**Issue by yybalam** [qooxdoo/qooxdoo#9090]
Actually `qx.bom.Cookie` class use `escape` and `unescape` but those functions are deprecated: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features

I don't know if is better to be changed by `encodeURI` and `decodeUIR` JS function or by analog methods of `qx.bom.String`.

**Comment by oetiker** [comment]
I would just use encodeURI and decodeURI ... can you create a PR ?
