### ISSUE TITLE
the apiviewer down

### ISSUE THREAD

**Issue by regexti** [qooxdoo/qooxdoo#9105]

**Comment by cajus** [comment]
Qooxdoo has moved away from the 1&1 servers and the DNS was just passed over to us. Looks like the DNS changes are not 100% propagated yet.

Maybe one of these are working for you:

http://qooxdoo.github.io/devel/api
http://www.qooxdoo.org/devel/api

api.qooxdoo.org is not restored yet, but we're working on it.

If you need the API *now*, you can use the local framework API. Point your shell to the qooxdoo/framework directory and call `./generate.py api`. Move the created *api* directory to your local webserver or run something like `python -mSimpleHTTPServer` in it.

Sorry for the inconvenience.

**Comment by regexti** [comment]
thank you Caju!

**Comment by oetiker** [comment]
http://api.qooxdoo.org will now also send you to the api viewer
