### ISSUE TITLE
permissive binding

### ISSUE THREAD

**Issue by slachtar** [qooxdoo/qooxdoo#9126]
I've noticied that if a controller is missing a property from the model, it generates an error and won't continue binding the next properties.

Is it possible to configure it for "permissive binding" so if a property is absent, no binding is done, but still can generate ui and modify other properties.

use case:
This happens for example when we remove fields from DB and we forget to remove binding from object controller.

**Comment by zaucker** [comment]
Isn't it better to notice that you didn't cleanup your frontend code?
A few months later you will start wondering why the bound fields don't show
up in the UI ...

On Wed, 17 Aug 2016, slachtar wrote:

> I've noticied that if a controller is missing a property from the model,
> it generates an error and won't continue binding the next properties.
>
> Is it possible to configure it for "permissive binding" so if a property
> is absent, no binding is done, but still can generate ui and modify other
> properties.
>
> use case:
> This happens for example when we remove fields from DB and we forget to remove binding from object controller.

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by stahl-riesa** [comment]
I know this could be very annoying, but I understand both sides. In the end I straightened my model data.

**Comment by slachtar** [comment]
Yes, one needs to clean frontend code,
we're a team of experienced and new developers and sometimes, we change db structure and with customer pressure due to some bug, we put version in production without alot of testings and oops, new bugs appear, so I thought permissive binding may help here :)
I'll close the issue.
Thank you all
