### ISSUE TITLE
IVirtualTreeDelegate / qx.ui.tree.VirtualTree should support sorter

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9127]
The IVirtualTreeDelegate / qx.ui.tree.VirtualTree should support sorter like qx.ui.list.core.IListDelegate does. So it will be much earsier to sort and change sorting of tree parent children.

**Comment by RemiHeugue** [comment]
It's already the case, isn't it ?
http://www.qooxdoo.org/devel/api/#qx.ui.tree.core.IVirtualTreeDelegate~sorter!method_public

**Comment by level420** [comment]
@stahl-riesa could you please revisit this issue and report back how we should continue? Thank you!
If you need the sorter functionality: It would be nice to have a PR for this.

**Comment by stahl-riesa** [comment]
Oh. Never noticed that and so never used! Close this topic please.

**Comment by level420** [comment]
Closing as per user demand.
@stahl-riesa you could also have closed this issue, as you are the author.
