### ISSUE TITLE
qx.ui.tree.VirtualTree doesn't suppress '+' sign

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9128]
http://www.qooxdoo.org/current/demobrowser/#virtual~Tree.html

Click the checkbox to hide the leafs. As you can see, the '+' sign doesn't disappear. If you open "workspace" and then click on hide leafs the '+' and the leafe are gone.

**Comment by oetiker** [comment]
I guess buildLookupTable should probably be a bit more aggressive https://github.com/qooxdoo/qooxdoo/blob/8f49c5e/framework/source/class/qx/ui/tree/VirtualTree.js#L891

**Comment by level420** [comment]
@stahl-riesa @oetiker
please have a look into this gist https://gist.github.com/level420/bb054f9f1bf06addf0ed68c1f18e3804 and paste it to the playground.

The fix forces a full rebuild of the tree if the properties showLeafs and showTopLevelOpenCloseIcons change.

Please note the class ```qx.ui.tree.MyVirtualTree``` there.

If appropriate I'll create a PR for this (or @stahl-riesa ;-)

**Comment by stahl-riesa** [comment]
@level420 Just do it!

**Comment by oetiker** [comment]
looks good

**Comment by level420** [comment]
done: PR #9244
