### ISSUE TITLE
Sizzle - remove, update or do nothing

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9130]
Does Qooxdoo really need Sizzle in 2016? Isn't browsers querySelector methods good enough?

Should Sizzle get an upgrade?

What do you think?

**Comment by level420** [comment]
In master sizzle was updated with https://github.com/qooxdoo/qooxdoo/commit/977e4a75ba3acaf3800f0cd25da965673387e33a#diff-46e915eb112c16f02a38e9d918af7ebb to version 2.3.0 by @cajus 

Current version of sizzle is 2.3.3, so we are not so far away.

@stahl-riesa Do you miss anything what as added from 2.3.0 to 2.3.3?

**Comment by stahl-riesa** [comment]
Ah... Ok. I used Q 5.0.1 with Sizzle 1.10 - 2,5 years old.

**Comment by level420** [comment]
@johnspackman should the update to sizzle be cherry picked for the upcoming 5.0.2 release?

**Comment by johnspackman** [comment]
yes, i'd say so

**Comment by level420** [comment]
milestone 5.0.2 was added to PR #9007 
closing this.
