### ISSUE TITLE
qx.bom.element.Class - get css classes list as array

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9131]
Because of native classList isnt supported by every browser, there should be a method for retrieving all element class names as array. Maybe the [qx.bom.element.Class](https://github.com/qooxdoo/qooxdoo/blob/release_5_0_1/framework/source/class/qx/bom/element/Class.js) get method coukd be extended wth a second parameter.

**Comment by level420** [comment]
@stahl-riesa could you please point to the qx source where classList is used? Thank you.

**Comment by stahl-riesa** [comment]
Edited!

**Comment by level420** [comment]
Ah OK! Now I understand.

Mabe to stay in the naming convention similar to ```qx.bom.element.Class.add``` and ```qx.bom.element.Class.addClasses``` there should be a ```qx.bom.element.Class.getClasses``` method which should do exactly what you need, retrieve all classes of an element.

As allways pull request are welcome, best equiped with tests for automated testing :-)

**Comment by level420** [comment]
The non native version should be as simple as
```javascript
return qx.bom.element.Class.get(element).trim().split(/\s+/);
```

**Comment by stahl-riesa** [comment]
I have no time in the next 10 days for creating the PR and writing tests. Work, family trip and kids... maybe next week on weekend.

**Comment by level420** [comment]
OK. Thank you.

**Comment by level420** [comment]
@stahl-riesa could you please review this issue? would be nice to have a PR for this.
Please report back here. Thank you.
