### ISSUE TITLE
NPM Package qooxdoo-sdk

### ISSUE THREAD

**Issue by pcdummy** [qooxdoo/qooxdoo#9137]
What speaks against a npm package `qooxdoo-sdk` ?

I'm asking for it as it would eliminate the requirement to define QOOXDOO_PATH in `grunt-qxcompiler` and let **npm handle the depencies of contribs and the sdk**. 

See #9129 for more about dependency handling in `grunt-qxcompiler`.

**Comment by johnspackman** [comment]
Seems reasonable, it would make "getting started" guides simpler.  

The only issues I can think of is that you often need to run under a web server rather than file://, and if you're doing more than one app you'll presumably install the qooxdoo-sdk module globally.  It would be cool if it also included a simple http server that took care of configuring the paths, and this would be a good excuse to run the grunt-watch also.

**Comment by qx-bug-importer** [comment]
there is already a qooxdoo npm package

**Comment by pcdummy** [comment]
There is `qooxdoo` but not `qooxdoo-sdk`.

**Comment by johnspackman** [comment]
The `qooxdoo` npm package is a precompiled bundle of just server stuff that is only 700K uncompressed whereas qooxdoo/framework/source is 36M uncompressed (as opposed to ~150M for the whole distribution)

I guess that one of the goals of the original npm package was to not require any tooling (especially as that would have meant python), but that also means that node.js apps you write have to take care of their own load order which in turn means that the size of app you can realistically write is limited.

To support ES6 development and/or apps with any significant number of classes it is arguable that a tooling step would be beneficial (although node.js is getting great ES6 support these days it's not complete).

Is there a reason to *not* include the whole of qooxdoo/framework/source in the `qooxdoo` npm package?

**Comment by oetiker** [comment]
I think we should have the source included better than having multiple packages ...

**Comment by oetiker** [comment]
I do have access to the qooxdoo npm account

**Comment by pcdummy** [comment]
Sounds good for me! Yeha!

**Comment by adrelino** [comment]
Currently, a search for qooxdoo on npm https://www.npmjs.com/search?q=qooxdoo
gives 12 results, out of which 3 look as if they should contain the whole source code / sdk:

1. https://www.npmjs.com/package/qooxdoo (still only contains qx.Server!!)
2. https://www.npmjs.com/package/@pcdummy/qx
3. https://www.npmjs.com/package/qooxdoo-sdk

To gain more new users that are used to manage their project dependencies with npm, we should state clearly which one of these is the official one and make sure that each release on github triggers an update of the official qooxdoo npm package.

**Comment by hkollmann** [comment]
discussend here: https://github.com/qooxdoo/qooxdoo/issues/9369
