### ISSUE TITLE
Traits for Qooxdoo

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9141]
Mixins are very useful when building applications, and Qooxdoo relies on them to implement many features, most notably in the qx.ui.\* components, but in OO terms they have their flaws; an alternative is Traits, which is like Mixins in that methods are defined separately to the class and added into the Class definition but differs in that Traits do not have state (ie member variables) and there is more control in how methods are included (for example, the Class can choose to rename or exclude methods during the import)

https://en.wikipedia.org/wiki/Trait_(computer_programming)
http://scg.unibe.ch/archive/papers/Scha02bTraits.pdf
http://scg.unibe.ch/archive/papers/Scha02cTraitsModel.pdf
http://cocktailjs.github.io/guides/exploring-traits-and-talents.html

**Comment by zaucker** [comment]
You might want to look at the Perl6 implementation of traits to steal some
ideas from it. One especially important aspects to me seems that it should
be checked if a method already exists when a trait/role is being added to it
to make sure that conflicts are caught automatically (otherwise it might be
hard to debug).

On Tue, 30 Aug 2016, John Spackman wrote:

> Mixins are very useful when building applications, and Qooxdoo relies on them to implement many features, most notably in the qx.ui.* components, but in OO terms they have their flaws; an alternative is Traits, which is like Mixins in that methods are defined separately to the class and added into the Class definition but differs in that Traits do not have state (ie member variables) and there is more control in how methods are included (for example, the Class can choose to rename or exclude methods during the import)
>
> https://en.wikipedia.org/wiki/Trait_(computer_programming)
> http://scg.unibe.ch/archive/papers/Scha02bTraits.pdf

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by level420** [comment]
My worries are that having something named mixins AND something named traits which give similar functionality to the qx oop ecosystem could be very confusing.
I'm in favour of extending the current mixin implementation

**Comment by level420** [comment]
I like simple examples: http://cocktailjs.github.io/
Traits example: http://cocktailjs.github.io/guides/exploring-traits-and-talents.html

**Comment by johnspackman** [comment]
Curtis Ovid Poe @OvidPerl_twitter 14:53
If you want to really understand traits/roles, this is the paper everyone reads: http://scg.unibe.ch/archive/papers/Scha02bTraits.pdf
However, you really want to read this one, also: http://scg.unibe.ch/archive/papers/Scha02cTraitsModel.pdf
The latter clarifies a few things, including the fact that traits are supposed to be commutative and associative, something which method modifiers violates.
And this paper explains some of the work trying to implement state in traits, though I recall the author telling me he wasn't completely happy with it (that was a conversation from a long time ago, so my memory is fuzzy): http://scg.unibe.ch/archive/papers/Berg08eElsevier.pdf

**Comment by thron7** [comment]
Just wanted to preserve the OSCON'14 talk about Moose linked on Gitter: https://youtu.be/LKXvG6VKew4

**Comment by stahl-riesa** [comment]
IMHO: no need for traits.

**Comment by zaucker** [comment]
On Wed, 31 Aug 2016, Patrick Fischer wrote:

> IMHO: no need for traits.

Perhaps you could give your reasons? A comment like that is not helpful.

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by stahl-riesa** [comment]
only perhaps... freedom of speech... no reason needed...

besides:
mixins are good.
traits are too complex.
I don't like the idea of porting traits to qooxdoo.
Traits doesnt offer more helpful features than qooxdoo already has.

**Comment by thron7** [comment]
I think it was @level420 who suggested on Gitter to postpone the naming issue, and first focus on a list of desired features. And then, maybe with all the reading and video material in the back, come up with ideas how to realize them.

**Comment by level420** [comment]
@thron7 yes, and name it then as it fits best: roles, traits, whatever...
