### ISSUE TITLE
current devel playground throws exception on startup

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9149]
When loading http://www.qooxdoo.org/devel/playground/ I'm getting three assert errors in console (Chrome 52, Firefox 48, IE11 on Windows7x64):

```
playground.js:213 001717 Assertion error! : Called assertTrue with 'false'
 Stack trace: 
qx.core.AssertionError.constructor://www.qooxdoo.org/devel/playground/scrip…anonymous(),anonymous(),qx.bom.request.Script.prototype._emit(),anonymous()
```

The visible impact is that the pre defined example list on the left side is empty.

**Comment by level420** [comment]
I've backed out @johnspackman s memory management PR https://github.com/qooxdoo/qooxdoo/pull/8986 as it "felt" to have something to do with hashcodes by using a fresh master clone like this:
```
git clone https://github.com/qooxdoo/qooxdoo.git
cd qooxdoo
git revert 88d974a1c8f0ea7236374ea7c0db9e142ae670f2 -m 1
```
and voila the playground works again as expected.

I think the relevant location where the problem is showing up is https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/html/Element.js#L572-L573

@johnspackman could you please have a look into this? Thank you.

**Comment by johnspackman** [comment]
no problem, ill have a look later on this evening

**Comment by johnspackman** [comment]
Fixed in https://github.com/qooxdoo/qooxdoo/pull/9150

**Comment by level420** [comment]
Thank you @johnspackman
