### ISSUE TITLE
Testrunners index-source is broken currently

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9151]
It claims that IDisposable is an invalid mixin. Using the build version works.

`Error: The implement definition in class "qx.event.Manager" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: The implement definition in class "qx.util.ObjectPool" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: Invalid config in class "qx.event.Pool"! Every non-static class has to extend at least the "qx.core.Object" class.
Class.js:807:17
Error: The implement definition in class "qx.util.DeferredCallManager" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: The implement definition in class "qx.theme.manager.Decoration" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: The implement definition in class "qx.theme.manager.Font" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: The implement definition in class "qx.event.Timer" contains an invalid interface at position 0: undefined
Class.js:866:23
Error: The implement definition in class "qx.html.Element" contains an invalid interface at position 0: undefined`

etc.

**Comment by level420** [comment]
Because of what I've found in https://github.com/qooxdoo/qooxdoo/issues/9149 I've backed out PR https://github.com/qooxdoo/qooxdoo/pull/8986 with:

```
git revert 88d974a1c8f0ea7236374ea7c0db9e142ae670f2 -m 1
```

and the testrunner runs again in source mode

**Comment by level420** [comment]
@johnspackman could you please have a look into this?

**Comment by johnspackman** [comment]
no problem

**Comment by cajus** [comment]
Turned out to be a false positive. Closing.
