### ISSUE TITLE
qx.lang.Function.create speedup in "debug" build

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9161]
I've found on my application, that `qx.lang.Array.toString()` was using up most of the time while creating a data Model for a List (via `qx.data.marshal.Json.createModel()`)...

After a little digging I found that it was issued in the debug assertion check at `qx.lang.Function.create` :
```
      // ...
      return function(event)
      {
        if (qx.core.Environment.get("qx.debug"))
        {
          if (qx.core.Object && options.self && qx.Bootstrap.isObject(options.self) && options.self.isDisposed && qx.Bootstrap.isFunction(options.self.isDisposed))
          {
            qx.core.Assert && qx.core.Assert.assertFalse(
              options.self.isDisposed(),
              "Trying to call a bound function with a disposed object as context: " + options.self.toString() + " :: " + qx.lang.Function.getName(func)
            );
          }
        }
```
The 2nd parameter (`msg`) of `qx.core.Assert.assertFalse` is **always** evaluated, independent whether the assertion triggers or not.

What about changing it to:
```
      // ...
      return function(event)
      {
        if (qx.core.Environment.get("qx.debug"))
        {
          if (qx.core.Object && options.self && qx.Bootstrap.isObject(options.self) && options.self.isDisposed && qx.Bootstrap.isFunction(options.self.isDisposed))
          {
            if (options.self.isDisposed()) {
              qx.core.Assert && qx.core.Assert.fail(
                "Trying to call a bound function with a disposed object as context: " + options.self.toString() + " :: " + qx.lang.Function.getName(func)
              );
            }
          }
        }
```
The assertion is still checked, but now the (expensive!) options.self.toString() is only executed if the assertion really failed!

On my real-life example this changed the creation time of a model from 10164ms to 2318ms!

I would love to see this change in qooxdoo, it speeds up debug code a lot (10 seconds is an awful long time :snail: ; while 2.5 seconds is workable!)

**Comment by oetiker** [comment]
how about creating a PR ? ... maybe this pattern exists in other locations too ?

**Comment by schnepe2** [comment]
@oetiker : I did a quick search for similar pattern, but did not find any more that could have such an impact. Although this was by far not a **full scan of all assert calls**!
I am sorry, but I don't have the time to do a full check of **all** message creations of **all** assert calls.
Most are "harmless" however, I believe.

**Comment by oetiker** [comment]
no problem :) thanks for the PR

**Comment by level420** [comment]
Fixed via PR https://github.com/qooxdoo/qooxdoo/pull/9162 and commit https://github.com/qooxdoo/qooxdoo/commit/34a1a93c8705593ce78e5319b7d639452f2dd965
