### ISSUE TITLE
generator.py compiler does not detect faulty string literals in function definitions

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9165]
As discussed in https://github.com/qooxdoo/qooxdoo/issues/9153#issuecomment-244052804 the generator does not detect an error if the function definition contains a string literal like this:

```javascript
  myFunc : function('bla') {
  },
```
which should lead to an error during compilation.

**Comment by thron7** [comment]
I'll try to look into this. (Don't know how to assign it to me here on Github.)

**Comment by thron7** [comment]
(@thron7 Self-mentioning, so I have it in my list of 'mentioned' issues ...)

**Comment by level420** [comment]
fixed via https://github.com/qooxdoo/qooxdoo/pull/9168 and landed master via 02d75a54faa9040f19e06f77a0b0dc92028b5963
