### ISSUE TITLE
Interfaces do not work as documented when used with abstract classes

### ISSUE THREAD

**Issue by gernotpokorny** [qooxdoo/qooxdoo#9170]
http://www.qooxdoo.org/5.0.1/pages/core/interfaces.html
"Before the actual implementation is called, the precondition of the interface is called with the same arguments."

Interfaces work as documented except when using them with abstract classes. The code from the function in the interface gets never called.
# **update:**

Changed code to a playground example
http://tinyurl.com/zpxus6w

If `MyClass` implements the interface instead of `AMyClass`, then it works like in the docu. But if the abstract class implements the interface as in the playground-example it does not work like described in the documentation.

**Comment by level420** [comment]
@gernotpokorny could you please create a playground sample for this issue?
Thank you!

**Comment by gernotpokorny** [comment]
I changed the code to a playground example

**Comment by level420** [comment]
@gernotpokorny could you please describe what the expected output should be in the playground example? Your example http://tinyurl.com/zpxus6w does not create any output.

**Comment by hkollmann** [comment]
No answer - closed
