### ISSUE TITLE
class properties: check could not handle (static) class references

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9172]
I am using static class variables to store possible values of properties. It fails:
_Uncaught TypeError: Cannot read property 'Z' of undefined_

It seems to me that check could not handle class references. If I am using self.Z it works. But again, If I want to use a other class I will get the error message again.

``` javascript
qx.Class.define("A", {
    extend : qx.core.Object,
    construct : function(el) {
         this.base(arguments);
         /* ... */
    },
    statics : {
        Z: ["a", "b", 'c', 's']
    },
    properties : {
        char : { init: 'a', nullable : false, check : A.Z}
    },
    members : {
        /* ... */
    }
});
```

PS:
If I get some free time on weekends evenings I will try to do more investigations on this and my other issues.

**Comment by level420** [comment]
@stahl-riesa could you please revisit this issue? thank you!

**Comment by derrell** [comment]
Statics may not yet be defined at the time that the properties are defined. I think you can solve this problem with something like:

```
properties :
{
  char :
  {
    init : 'a',
    nullable : false,
    check : function(value)
    {
      return A.Z.indexOf(value) != -1;
    }
  }
}
```

**Comment by stahl-riesa** [comment]
I will close it because of fixing it is not so important. Derrell showed I nice way to get around the problem.
