### ISSUE TITLE
Test qx.test.Mixin erroneously include()s and then patch()es using the same class and mixin

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#9175]
The mixin facilities qx.Class.include and qx.Class.patch are mutually exclusive. One should either use the "safe" version (qx.Class.include), or if one really, Really, REALLY knows what one is doing, can use the unsafe version (qx.Class.patch). Both, however, are irreversible -- once a class has been altered with a mixin, those changes can not be removed in any automated fashion; they have become a part of the class.

In qx.text.Mixin, near line 257, the test calls

```
qx.Class.include(qx.Patch1, qx.MPatch);
```

and then later calls

```
qx.Class.patch(qx.Patch1, qx.MPatch);
```

The include() made changes, including adding qx.MPatch's private variable __b. It did not overwrite the existing method sayJuhu because include does not, by definition, alter existing methods.

When patch() is called, it _again_ tries to add qx.MPatch's private variable __b, which it finds that it can't do because that private variable already exists from the prior include().

Because a mixin can not be extricated once it is mixed in via include() or patch(), these mutually excusive calls can not be in the same test. They must be done in two entirely independent tests such that the mixin has _not_ been included at the point that patch() is called.

**Comment by derrell** [comment]
This came up as a result of #9153 and then PR #9158 which tried to make the linter happy. By the time this current issue is worked on, qx.test.Mixin may have been altered to make the linter happy, by changing __b from private to protected, or by accessing it using array notation so that the linter doesn't notice. Once this issue is fixed, the test should return to using a private member with standard object member access notation.

**Comment by hkollmann** [comment]
@derrell : Tests are working . IMHO we can close this issue?

**Comment by derrell** [comment]
Yes this appears no longer to be an issue. Closing.
