### ISSUE TITLE
Main menu of qooxdoo.org pages differs

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9179]
Hi,

The qooxdoo.org main menu is different between the main page and others (for example : http://qooxdoo.org, http://www.qooxdoo.org/demos.html)

**Comment by cajus** [comment]
I guess we all need to eat some time-extension-pills (TM) and re-do the complete page, finally ;-)

**Comment by stahl-riesa** [comment]
@cajus I could try to unify the pages main menu, if you like. I have got some time after christmas.

**Comment by level420** [comment]
@stahl-riesa Shure! Your help is very welcome!

**Comment by hkollmann** [comment]
closed because we want to rework the webpage
