### ISSUE TITLE
lint warning in qx.lang.normalize.Array prevents successful travis run  

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9187]
It seems that this came in with https://github.com/qooxdoo/qooxdoo/pull/9177/files
```
Running lint...
  - Warning: qx.lang.normalize.Array (389, 36): qx.core.Environment.get: first argument is not a string literal.
Lint warnings are treated as errors! Please fix!
```
Here one of the latest travis runs: https://travis-ci.org/qooxdoo/qooxdoo/jobs/161879413

**Comment by level420** [comment]
@johnspackman could you please have a look? Thank you!

**Comment by johnspackman** [comment]
no problem

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9192
