### ISSUE TITLE
qx.data.marshal.Json#createModel "caches" model classes without bubble-differentiation

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9193]
`qx.data.marshal.Json#createModel` checks if a class representing the given model already exists and re-uses that class.
This however creates a problem when the same (native) model is requested **once without**, and later **with** `includeBubbleEvents` set.

The hashing (to determine if a fitting class exists) should include that bubble-information!

See [playground example](http://tinyurl.com/jseqz3v)

**Comment by level420** [comment]
@schnepe2 It would be very nice to have a PR for this. Thank you.

**Comment by level420** [comment]
The fix would be to add the ```includeBubbleEvents``` added as parameter to ```qx.data.marshal.Json.__jsonToHash```  at https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/data/marshal/Json.js#L82 and forward the parameter downstream to it.

**Comment by level420** [comment]
On more hint: ```qx.util.OOUtil.getEventType(clazz, 'changeBubble');``` could be used to test if the ```changeBubble``` event is present.

**Comment by schnepe2** [comment]
@level420 Yes all this seems to be easy,
```
    __jsonToHash: function(data, includeBubbleEvents) {
      return Object.keys(data).sort().join(includeBubbleEvent?'~'?'"');
    },
```
..but now comes the part that's tricky:

The signature of the **public** method `toModel(data)` should not be changed and so inside this method comes the part were to decide for a class with bubbling or one without bubbling.

In case we have the same data but two different classes (one with bubbling and one without bubbling like in my playground example)

My current proposal for this is following:
In case of a dilemma, **always** use the class with bubbling. I don't see how this could be made better without changing the API (of `toModel(data)`).
Any (better) ideas / thoughts?

**Comment by level420** [comment]
Regarding ```toModel(data)``` we could add the additional and optional parameter ```includeBubbleEvents```. If ```includeBubbleEvents``` is omitted ( ```=== undefined```), then we could use your strategy to always return the class with bubbling if we have both classes, with and without bubbling.
If ```includeBubbleEvents``` is ```true``` or ```false```, then right class should be returned.

**Comment by schnepe2** [comment]
...yeah, that feature could be included (too). I'll first try to check whether that "automatically choose the most enhanced class" approach works.
After that I think extending `toModel` by an optional `includeBubbleEvents` parameter would be an enhancement.
I currently have to create some tests for all this.

**Comment by schnepe2** [comment]
@level420 ....while looking over the implementation details of your proposal for the optional `includeBubbleEvents` parameter for `toModel` I found another dilemma:
What if the user created (only) a class without bubbling, then decides to want it when using `toModel`?
Like:
```
var data = {foo: "bar"};
var marshaler = new qx.data.marshal.Json();
marshaler.toClass(data, false);
var model = marshaler.toModel(data, true); // <= exception? or warn and "auto" ?
```
.
.
My proposed `toModel` signature  currently is like this (note the 'tristate' nature of `includeBubbleEvents`)
```
    /**
     * Creates for the given data the needed models. Be sure to have the classes
     * created with {@link #toClass} before calling this method. The creation
     * of the class itself is delegated to the {@link #__createInstance} method,
     * which could use the {@link qx.data.store.IStoreDelegate} methods, if
     * given.
     *
     * @param data {Object} The object for which models should be created.
     * @param includeBubbleEvents {Boolean?null} Whether a model with support
     *   for the bubbling of change events should be used or one without.
     *   If omitted or <code>null</code>, an automatic selection will take place
     *   which selects the "best" model currently available.
     * @return {qx.core.Object} The created model object.
     */
    toModel : function (data, includeBubbleEvents) {
      return this.__toModel(data, includeBubbleEvents, null, 0);
    },
```

**Comment by level420** [comment]
If someone creates a class without bubbling and then asks for a class with bubbling, then I'll consider this being a bug, thus an exception should be thrown.

**Comment by schnepe2** [comment]
|Model with|Model without
------------ | ------|-------
**Class with** | :white_check_mark:   | :white_check_mark:
**Class without** | :no_entry_sign:  | :white_check_mark:

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9205
