### ISSUE TITLE
qx.Annotation partly lacks parameter description

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9199]
If one inspects http://www.qooxdoo.org/devel/api/#qx.Annotation, it is marked with a yellow "!" and most of the contained methods are marked with a red "x". Should be updated before a release IMHO.

**Comment by johnspackman** [comment]
yes indeed

**Comment by level420** [comment]
@johnspackman it is the ```return``` vs. ```@return``` in the jsdoc annotations of the methods.
