### ISSUE TITLE
Filtered table not working after filling the table with addRows

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo#9204]
Please have a look at the following playground example: http://tinyurl.com/zc6xg34

Initially you can activate/deactivate the filtering by clicking the filter-button. But after cklicking the refresh-button, the filtering is broken (table is empty).

The problem is, that by resetting the tableModel with `setData([])` the initial `__fullArr` gets resetted too, but when you fill the tableModel by using addRows/setRows and not setData `__fullArr` does not get updated.

A possible solution would be to remove the overridden setData method from qx.ui.table.model.Filtered. The described problem is fixed then, but I don't know if it has any unwanted impact.

Also I was wondering what would happen if a row was added to the tableModel (by using addRows) when a filter is active. After deactivating the filter, the tableModel would be replaced with `__fullArr` which does not know about the new row?

**Comment by peuter** [comment]
Forget about the mentioned solution as creates more errors than it solves

**Comment by oetiker** [comment]
I think the best thing to be done about the filtered table model is to mark is as deprecated, and advise people to use a different implementation technique as discussed a few months ago ...

**Comment by derrell** [comment]
I would tend to agree. It was contributed and used (extensively, I think) by the contributor, but not well used otherwise, and has had a number of problems reported over the many years since it was included, with little additional attention paid to it by the contributor nor anyone else that I know of.

**Comment by peuter** [comment]
Can you give me a hint about the different implementation technique you are talking about?

**Comment by level420** [comment]
@woprandi could you help here?

**Comment by woprandi** [comment]
@peuter You should use filter on your data array. I modified your example (line 45) : http://tinyurl.com/hedgrr9

**Comment by peuter** [comment]
@woprandi Thank you!

**Comment by level420** [comment]
@peuter can we close this issue?

**Comment by peuter** [comment]
Sure

**Comment by carlosfvieira** [comment]
Hi @woprandi ,

How exactly this works differently from using the Filtered model? Will you not be resetting initial data also? Leading to the same problem stated on the creation of this issue?

Can you provide an example? The provided link on quote is now broken...

Thanks

>@peuter You should use the Array.filter method on your data array. I modified your example (line 45) : http://tinyurl.com/hedgrr9
