### ISSUE TITLE
qooxdoo.org currently down

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9220]
Due to currently unknown reasons qooxdoo.org is unavailable and shows a rudimentary page where all assets are missing.

All demos, api viewer, documentation and the playground is unavailable atm.

We are investigating the issue and hope we will be online again soon.

**Comment by cajus** [comment]
github update:

> Thanks for that additional information! Our engineers are currently looking into what might be happening. I can't promise an ETA, but I'll let you know as soon as there's any news!

**Comment by cajus** [comment]
While they're inspecting the problem:

docs: https://ferdi.naasa.net/qx/current
api: https://ferdi.naasa.net/qx/current/api

devel - docs: https://ferdi.naasa.net/qx/devel
devel - api: https://ferdi.naasa.net/qx/devel/api

**There's no rewrite of the navigation links, so some of them might end nowhere.**

**Comment by thron7** [comment]
Just to mention this again, docs are also available via ReadTheDocs: https://qooxdoo.readthedocs.io/en/latest/

Master is built quite regularly there. Links are also not rewritten.

**Comment by level420** [comment]
@cajus could we close this, as your workaround seems to have solved it?

**Comment by cajus** [comment]
Lets do so...
