### ISSUE TITLE
Make qooxdoo compatible with LibreJS

### ISSUE THREAD

**Issue by LibreJS** [qooxdoo/qooxdoo#9222]
Easy guide on how to do it: https://www.gnu.org/software/librejs/manual/librejs.html#Setting-Your-JavaScript-Free

This should take no more than a few minutes.

Thank you.

**Comment by johnspackman** [comment]
@LibreJS you look like a robot.  If you want to start a discussion that's fine, otherwise you're just spam.  A brief look at LibreJS seems to show that it objects to minified and "nontrivial" javascript applications, and Qooxdoo is designed specifically for building nontrivial apps.  Discuss...
