### ISSUE TITLE
Spinner Focus problem

### ISSUE THREAD

**Issue by Syrrius78** [qooxdoo/qooxdoo#9245]
Hi all,
I think, there is a problem with Spinner object when we use the method '.focus()'.
The object seems to receive the focus but we can't use the keyboard in order to change the value.
(ok with tab key)

Example:
```
// Create a button
var button1   = new qx.ui.form.Button("First Button", "icon/22/apps/internet-web-browser.png");
var mySpinner = new qx.ui.form.Spinner(0, 0, 99);

// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(button1,   {left : 100, top  : 50});
doc.add(mySpinner, {right: 100, top  : 50});

// Add an event listener
button1.addListener("execute", function(e) {mySpinner.focus();});
```

**Comment by cajus** [comment]
Added playground link: http://tinyurl.com/zkacv57

**Comment by cajus** [comment]
@Syrrius78, can you verify whether https://github.com/qooxdoo/qooxdoo/pull/9246 fixes your issue?

**Comment by Syrrius78** [comment]
@cajus : Great! It's working fine now with the Spinner fix. Thanks a lot for your quick solution ^^.

**Comment by cajus** [comment]
Not yet merged. Will re-open it until it's merged.
