### ISSUE TITLE
Wrong appearance for qx.ui.toolbar.SplitButton

### ISSUE THREAD

**Issue by RemiHeugue** [qooxdoo/qooxdoo#9249]
When using the theme Simple (or Indigo which inherit Simple) and you put a qx.ui.toolbar.SplitButton alone in a toolbar (or alone in a qx.ui.toolbar.Part) there is a gap between the left and right part of the button.

If you have more than one button in Part, there is no problem.

Playground example : http://tinyurl.com/z3nph3e

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9250
