### ISSUE TITLE
Focus on object in window that is partially out of screen causes blink in IE.

### ISSUE THREAD

**Issue by trupljan** [qooxdoo/qooxdoo#9253]
Focus on object in window that is partially out of screen causes blink in IE on Windows 10.

Steps to reproduce:
1. Start Internet Explorer (tested on IE11)
2. Open: http://www.qooxdoo.org/current/demobrowser/#table~Table_Huge.html
3. Move window with table to the right-bottom corner so that only some cells are visible.
4. Click on a cell, then on another and so on, you should see it blinking each time you click.

It seems that the content of windows is forced to be within bounds of screen and only a while later it is moved to original position. For a while, you can see whole window in the right-bottom corner.

The problem also very rarely occurs in latest chrome, but it is not that visible because chrome is fast, very hard to reproduce, noticed only after I discovered this while testing on IE.

It happens if method focus() is called on a widget inside window that is partially out of screen and the widget is also partial out of screen, it is not definitely problem with qx.ui.table.Table as it happens also with any other widget focused (tested with qx.ui.form.TextField and qx.ui.form.PasswordField). The window must have quite a lot of stuff for this to be visible, otherwise it happens very rarely.

**Comment by trupljan** [comment]
Not sure if focus() is really responsoble for this...

**Comment by level420** [comment]
@trupljan I can reproduce this in the demo browser. But if I run http://www.qooxdoo.org/current/demobrowser/#table%7ETable_Huge.html and use the "run in own window" I cant' reproduce it any more. 

So this may be due to the demobrowser itself being a qx.website app and running qx.desktop apps inside.

Can you reproduce this outside demobrowser?
I've tested this with a really complex widget stack in a window without seeing any window jump.

**Comment by level420** [comment]
Could reproduce this with the huge table demo when run in own window with IE 11.

May be related to https://github.com/qooxdoo/qooxdoo/commit/49a0b5859bcb844332f491e29f3fe5809ed5e26a

**Comment by trupljan** [comment]
I was able to partialy solve the problem by disabling usage of widow.requestAnimationFrame by adding this code to main method of application (this is a hack!):

        qx.bom.AnimationFrame.request = function(callback, context) {
          var cb = function() {
            callback.call(context, Date.now());
          };
          return window.setTimeout(function() {
            cb();
          }, qx.bom.AnimationFrame.TIMEOUT);
        };

Is there any better way to disable "css.animation.requestframe" in environment so that qx.core.Environment.get("css.animation.requestframe") returns null?

**Comment by trupljan** [comment]
My fix does not work at all, if debugging in chrome I can see the window "blink" during stepping. It seems that window is moved temporarily so that it's bottom-right corner is in the bottom-right corner of a browser and then later it is moved back so that it's bottom-right corner is outside screen.

In chrome it happens so fast that it is not visible. Also it is not table widget related, it happens with other windows too (only saw it in explorer which does not render so fast...).

**Comment by hkollmann** [comment]
Can not reproduce this any longer
