### ISSUE TITLE
Possible script transport problems ahead with Chrome 56 and stop working qx.bom.request.Script and qx.io.remote.transport.Script

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9254]
Chrome will stop loading scripts for script tags with missing or invalid MIME type with version 56 (currently in beta).

See: https://www.chromestatus.com/feature/5760718284521472

Allowed MIME types are: https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type

Both ```qx.bom.request.Script``` and ```qx.io.remote.transport.Script``` use dynamically created script tags which are created via ```document.createElement("script")``` but do not set a MIME type, which could be done via 
```javascript
var script = document.createElement("script");
script.type = 'text/javascript';
```
The location where this should be done is https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/io/remote/transport/Script.js#L259 or https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/bom/request/Script.js#L662

This is just a reminder issue. Not sure if it really is/will be present.

If someone uses the script transport: please test and report back.

**Comment by kreimer** [comment]
Tested in Chrome Version 56.0.2924.21 beta (64-bit) (linux) the following code is working ok:

`            this._loaded = 1;
            var ol3Script = new qx.bom.request.Script();
            var thizz = this;
            ol3Script.onloadend = function() {
                thizz._loaded = 2;
                thizz._pendingCallbacks.forEach(function(callback, idx, callbacks) {
                    callback();
                }, thizz);
            };
            ol3Script.open("GET", "/ext/openlayers/ol.js");
            ol3Script.send();
`

**Comment by kreimer** [comment]
I patched a copy of [https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/bom/request/Script.js#L662](https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/bom/request/Script.js#L662)

as following:

```javascript
    /**
     * Create and configure script element.
     *
     * @return {Element} Configured script element.
     */
    __createScriptElement: function() {
      var script = this.__scriptElement = document.createElement("script");
      script.type = "text/javascript";
      qx.log.Logger.debug("patched mime type: " + script.type);
      script.src = this.__url;
      script.onerror = this.__onNativeErrorBound;
      script.onload = this.__onNativeLoadBound;

      // BUGFIX: IE < 9
      // Legacy IEs do not fire the "load" event for script elements.
      // Instead, they support the "readystatechange" event
      if (this.__environmentGet("engine.name") === "mshtml" &&
          this.__environmentGet("browser.documentmode") < 9) {
        script.onreadystatechange = this.__onNativeLoadBound;
      }

      return script;
    },
```
and it works ok  in Chrome Version 56.0.2924.21 beta (64-bit) (linux)
![screenshot from 2016-12-13 11-53-04 copy 2](https://cloud.githubusercontent.com/assets/2874633/21137734/2cd88bd6-c12b-11e6-99ab-70dc89a99711.png)

**Comment by level420** [comment]
It seems that the default for the MIME type is "text/javascript" as per https://developer.mozilla.org/de/docs/Web/HTML/Element/script and answer here https://bugs.chromium.org/p/chromium/issues/detail?id=626321&desc=2#c18 .

So we _should_ be safe.
