### ISSUE TITLE
In IE11, a window field lose focus when browser window is resized

### ISSUE THREAD

**Issue by Syrrius78** [qooxdoo/qooxdoo#9256]
I'm using qooxdoo 5.0.1  for a desktop application (use the standard theme 'qx.theme.modern').
In my application, I have a window with a field.
I want to relocate the window when the browser window is resized.
So I declared that :
```
      this.getRoot().addListener("resize", function(){
        winTst.center();
      });
```

It's working fine with Firefox but I have a problem with IE11.
When I resize my browser window, my field lose focus and my focus is outside the window:
![test](https://cloud.githubusercontent.com/assets/24386840/21236052/c03da0b2-c2f9-11e6-9006-d1c58f3948d6.png)

I test on your playground. It's working
http://tinyurl.com/jyv3e3w

Did someone correct that on your side ? I see nothing in closed issues
Thanks in advance.

**Comment by level420** [comment]
@Syrrius78 I could not reproduce the bug on the 5.0.1 playground with current IE11 on windows 7x86 with latest updates from yesterday: http://tinyurl.com/h5kfr9a

Are you sure that the bug shows up wit IE11 in playground?

**Comment by Syrrius78** [comment]
@level420: Hi
That's what I said : "I test on your playground. It's working"
No error on IE11 with your playground.
But on my side, I created a standalone application with the framework 5.0.1 (same code), it's not working on IE11 (screenshot).
So It's strange.
That's why I'm asking if it's really a bug or if you have corrected something on your side/on the playground
(I can't see if it was corrected in a closed issue)
And if there is a correction, what is it?

Thanks in advance for your help.
I hope I'm a little clearer (I know, my English is not terrible ^^)

**Comment by Syrrius78** [comment]
Ohhh .. I'm very sorry. 
I created a new application that only do that. It's working fine on IE11.
But in my big application, it's not working at all 
(The code is the same but maybe there is something that cause this problem in my big application).

I'll try to understand...
Sorry again

**Comment by level420** [comment]
@Syrrius78 so you think this is not a bug in qooxdoo but in your application?

**Comment by Syrrius78** [comment]
@level420 : It's very strange because no error message in the console and the window code is the same but it's integrated in a big application (working in the small app / not working in my big app).
Maybe there something that do this problem in my big app.
I'll try to have more information...

**Comment by level420** [comment]
@Syrrius78 please report back here and if you don't think it is a bug in qooxdoo, please close this issue. 
thank you.

**Comment by Syrrius78** [comment]
@level420 ok, sorry for the inconvenience.
I've done a "distclean" on my big application and it's working perfectly now.
(Maybe something went wrong after doing "generate source" at least more than 100 times without cleaning the application).
Next time, I'll do that first ("distclean") before creating an Issue.
Have a good day.
