### ISSUE TITLE
QxBuilder.js

### ISSUE THREAD

**Issue by cbsistem** [qooxdoo/qooxdoo#9259]
helo
not found QxBuilder.js, exist QxBuilder.js ??

reference: https://sourceforge.net/p/qooxdoo/mailman/message/5588468/
tanks

**Comment by johnspackman** [comment]
No, that post will have been referring to a very early version of Qooxdoo (ie pre- v1.0 ).  Perhaps you could try explaining what you are trying to achieve either as a StackOverflow question (please remember to tag your question with "qooxdoo") and/or ask on Gitter https://gitter.im/qooxdoo/qooxdoo
