### ISSUE TITLE
"click" event no longer fired for a middle mouse button click on chrome 55

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9268]
Hi,

On this example : http://tinyurl.com/hpe2ugf on chrome (55), the "click" event is no longer fired with a middle or right click (only left). I think it's only since chrome 55 but I didn't test with a previous version. I tried with "tap" event but the behavior is the same. I noticed the recent 5.0.2 release but no changes
On Firefox, no issue.

**Comment by level420** [comment]
@woprandi It seems that Firefox is the only browser which fires a right mouse button click (in windows and osx). Tested with Internet Explorer 11, current Edge, Opera 42, Firefox 50 on windows and Safari 10, Firefox 50 on osx.

Could not test middle mouse clicks, as my mouse has only a left and right button.

The documentation for the click event says that it should react on left and middle mouse clicks:
http://www.qooxdoo.org/current/api/#qx.ui.core.Widget~click!event

The right mouse button should only react on the contextmenu event:
http://www.qooxdoo.org/current/api/#qx.ui.core.Widget~contextmenu!event

So the issue title should be changed maybe to something not specific to chrome or version 55 of chrome.

Are you shure that it worked on chrome 54?

**Comment by level420** [comment]
@woprandi as a workaround you could use the `mousedown` event.
See http://tinyurl.com/jln6ks2

http://www.qooxdoo.org/current/api/#qx.event.type.Mouse

**Comment by woprandi** [comment]
@level420 This code worked for a long time (for middle click). Chrome 55 release seems to be a good culprit. I don't know any other reason but I didn't check since it's not trivial to get a old chrome package

**Comment by woprandi** [comment]
@level420 I can confirm it WORKS with Chrome **53** (could not get a 54 release) and NOT on 55

**Comment by level420** [comment]
@woprandi on which os are you?

**Comment by woprandi** [comment]
@level420 Linux

**Comment by stahl-riesa** [comment]
I have to confirm.  Same issue on Windows 7-64 with Chrome 55 (Opera). Middle and right button does not fire an click event.
My user agent string: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.94

**Comment by level420** [comment]
As of the documentation click should never be fired on right mouse click. On richt mouse click it should fire the contextmenu event.

@stahl-riesa How did you test middle mouse clicks? Do you have a three button mouse?

**Comment by level420** [comment]
@woprandi @stahl-riesa could you please verify if middle mouse click is working in this jsfiddle?
http://jsfiddle.net/h4JXs/5070/

**Comment by derrell** [comment]
Linux / Chrome 54: I get an alert on left-click, nothing on middle-click, context menu on right-click.

**Comment by level420** [comment]
Thank you @derrell 

It indeed seems that chrome since v 55 does natively not fire a click event anymore on middle mouse button click. The new event name for that is ```auxclick```.

Clicks with the non primary button of a mouse is allways an ```auxclick```.

Read the original chrome announcement:
https://developers.google.com/web/updates/2016/10/auxclick

Firefox will follow in version 53.
http://forums.mozillazine.org/viewtopic.php?f=23&t=3026069&p=14726897&sid=8a56775d01abae13fd98ba71909b43d3
See https://bugzilla.mozilla.org/show_bug.cgi?id=1304044

We do not currently detect auxclick in qooxdoo. As allways PRs are welcome which change this.

**Comment by woprandi** [comment]
@level420 No alert with middle-click

**Comment by stahl-riesa** [comment]
@level420 Nothing happens on clicking the middle mouse button / the mouse wheel.

**Comment by level420** [comment]
@woprandi please test PR https://github.com/qooxdoo/qooxdoo/pull/9270 if it solves this issue.

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9270
