### ISSUE TITLE
if isDisposed() is true, please not  call renderLayout.

### ISSUE THREAD

**Issue by tiandian** [qooxdoo/qooxdoo#9272]
I create a class as below: 
```
qx.Class.define("My.TestForm", {
    extend: qx.ui.window.Window,
    members: {
        Init: function() {
            var that = this;
            this.addListener("close", function() {
                qx.lang.Function.delay(
                    function() {
                        that.dispose();
                 }, 1);
            });
            this.center();
        }
    }
});

 var f= new My.TestForm();
 f.Init();
 f.show();
```

I want when the window is closed, throught call **that.dispose()** to remove window from the dom tree, but the error occurs in widgets's  renderLayout() function, because when the window is closing, it still will call renderLayout() the last time,  
```
    renderLayout : function(left, top, width, height)
    {
      var changes = this.base(arguments, left, top, width, height);
      ...

      if (Object.keys(contentStyles).length > 0) {
        content.setStyles(contentStyles); //here will error, because content is null
      }
```

because **content is null** after window is disposed, so **content.setStyles will error**.

so, better let renderLayout return when widget is disposed, such as:
```
    renderLayout : function(left, top, width, height)
    {
        if(this.isDisposed())
        {
            return;
        }
        
        ...
    }
```
thanks.

**Comment by derrell** [comment]
I'm not at my computer right now to verify the property name, but in git
(not yet released), there's a new property called something like
destroyOnClose which does what you want. You might consider using master,
or wait for upcoming release which will include it.

Derrell

**Comment by tiandian** [comment]
@derrell, i have test the devel version, everyting is ok.
thanks!
