### ISSUE TITLE
Can Button and  Command has a ID property?

### ISSUE THREAD

**Issue by tiandian** [qooxdoo/qooxdoo#9273]
I want do as below:

```
var button1 = new qx.ui.toolbar.Button("ID1");
button1.addListener("execute", this.ExecCommand);

var button2 = new qx.ui.toolbar.Button("ID2");
this.button2.addListener("execute", this.ExecCommand);

var button3 = new qx.ui.toolbar.Button("ID3");
this.button2.addListener("execute", this.ExecCommand);
...
ExecCommand: function (e)
{
      switch(e.getID())
      {
           case "ID1":
                    fun1();
                    break;
           case "ID2":
           case "ID3":
                    fun2(id);
                    break;
           defaut:
                    break;
      }
}
```
That is, all the buttons go to the same method, but now button/command has no ID property, how can i 
distinguish the buttons.
thanks!

**Comment by zaucker** [comment]
Use getLabel()

Cheers,
Fritz

**Comment by cajus** [comment]
Label has the disadvantage that it may be translated. Normally you need to store the Button widgets for proper disposal. If you have done that, you can just compare with that object.

Another way can be *yourButton.setUserdata("id", "foobar")*. You can get the userdata via *getUserData("id")* back from the button object - which is not in *e* in your example btw.

**Comment by cajus** [comment]
Closing the issue, because it's more a Q&A. @tiandian, feel free to post it to stackoverflow if you think it requires more discussion ;-)

**Comment by tiandian** [comment]
@cajus, thanks, i see.
