### ISSUE TITLE
Including qooxdoo after sinon.js makes some properties undefined

### ISSUE THREAD

**Issue by jibesh** [qooxdoo/qooxdoo#9277]
If I include qooxdoo after including sinon.js, I can no longer call _sinon.FakeXDomainRequest_

The order in which I include is as follows:
````javascript
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sinon.js/1.15.4/sinon.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/qooxdoo/5.0/q.min.js"></script>
````

**Comment by cajus** [comment]
What does "I can no longer call..." mean in detail? Do you have some example code?

**Comment by jibesh** [comment]
Sorry for not providing details. The following is what I mean:

When I include only _sinon.js_, the access path _sinon.FakeXDomainRequest_ points to a function. I am able to call the function.

But, if I include _qooxdoo_ after including _sinon.js_ (as shown by the snippet in my previous comment), sinon.FakeXDomainRequest now becomes undefined.

````javascript
\\ Including: only sinon.js
typeof sinon.FakeXDomainRequest; \\ "function"

\\ Including: sinon.js
\\ Including: qooxdoo
typeof sinon.FakeXDomainRequest; \\ "undefined"
````
It seems, qooxdoo is overwriting the identifier _sinon_ defined by sinon.js causing the above problem.
````javascript
\\ Including: only sinon.js
Object.keys(sinon).length; \\ 46

\\ Including: sinon.js
\\ Including: qooxdoo
Object.keys(sinon).length; \\ 41
````
Tested in Chrome 56

**Comment by cajus** [comment]
Qooxdoo includes sinon (1.9.1), so one idea would have been that this causes your observations. I'm not familiar with qx.web, so I've no idea whether it's included there or not.

Can you please try, *not* loading sinon and check if *sinon* is defined? If so, it is included and just overloads 1.15.x with an older version.

**Comment by jibesh** [comment]
I checked by not loading _sinon.js_ i.e., by only loading _qooxdoo_.
Yes, _sinon_ is defined but lacks the extra properties that newer version of _sinon.js_ has.

It means your observation is correct, _qooxdoo_

>  just overloads 1.15.x with an older version

and will get fixed if  _sinon.js_ included in _qooxdoo_ is updated to a newer version.

**Comment by cajus** [comment]
Ok. Which means that you don't have to include it at all ;-)

I'll update sinon in the framework as soon as possible.
