### ISSUE TITLE
Incorrect selection in lists and tables in YandexBrowser v17.1.1.266 (Chromium)

### ISSUE THREAD

**Issue by mef1stofel** [qooxdoo/qooxdoo#9278]
Positioning on the list items occurs incorrectly in the browser. In this case, double-click is performed on the correct item in the list, but another element is highlighted.
If you open the developer console - everything works as it should.
You can see this in the following video:
https://youtu.be/CGY-9f4mC2M

**Comment by level420** [comment]
Dies this only happen in the yandex browser, not in chrome?

Please create a playground example http://www.qooxdoo.org/devel/playground/ which shows the problem preferably in current chrome.

**Comment by mef1stofel** [comment]
In Chrome 55.0.2883.87 (64-bit) all works perfect!
Problem only in Yandex browser: on Linux (17.1.1.266 beta (64-bit)), on Windows (v. 17.1.0.2033).

**Comment by level420** [comment]
Anyway: please create a playground sample which shows the problem in the yandex browser

**Comment by mef1stofel** [comment]
"Table" sample on palyground shows it:  http://tinyurl.com/hej49um
Moreover, the list of examples in the Yandex browser does not work properly! I can select one only with keyboard arrows.

**Comment by level420** [comment]
I suspect that browser detection fails here which leads specific adaptions for chrome to fail.

Could you please start the playground http://www.qooxdoo.org/devel/playground/, open the developer console in the yandex browser and paste following commands there:

```javascript
qx.core.Environment.get("browser.version");
qx.core.Environment.get("browser.name");
qx.core.Environment.get("engine.version");
qx.core.Environment.get("engine.name");
```
Please report the results back here.

**Comment by mef1stofel** [comment]
`qx.core.Environment.get("browser.version");
"55.0"
qx.core.Environment.get("browser.name");
"chrome"
qx.core.Environment.get("engine.version");
"537.36"
qx.core.Environment.get("engine.name");
"webkit"`

**Comment by level420** [comment]
Thank you @mef1stofel 
that is exactly the output when chrome 55 is running.

**Comment by level420** [comment]
Another question: do you have zoom enabled in the browser?

**Comment by mef1stofel** [comment]
> Another question: do you have zoom enabled in the browser?
You mean page scaling? 100%. If not, how can i check it?

**Comment by mef1stofel** [comment]
Why opnened developer console fix this problem?

**Comment by level420** [comment]
Yes I meant page scaling. 100% is ok.
Why opening the developer console fixes the problem? I've really no idea.

**Comment by level420** [comment]
It would be helpfull if you run the source version of qooxdoo playground locally to check if there is any error in the console and report that here, or better, clone the qooxdoo repo and try to fix it via a PR.

**Comment by mef1stofel** [comment]
There is two problems while generating source:
>>> Executing shell command "sass -C -t compressed -I ../../framework/source/resource/qx/mobile/scss -I ../../framework/source/resource/qx/scss --update source/resource/playground/scss:source/resource/playground/css"...
/bin/sh: 1: sass: not found
  - Skipping shell command: It seems that Sass (http://sass-lang.com/) is not installed and/or executable, which is needed for the SCSS-compilation.
>>> Done (0m00.00)
In console it is only ine missing css file, no other errors.
![_2017-01-27_12-53-24](https://cloud.githubusercontent.com/assets/3930855/22366900/f8e02f7c-e48f-11e6-8ff8-acb4598edb56.png)

**Comment by level420** [comment]
You need to install the sass compiler on your system.
But there are no error message in the console, besides the not unavailable css file.
So I'm out of clues!

**Comment by mef1stofel** [comment]
> You need to install the sass compiler on your system.

Done! generate source, refresh page. No changes ...

![_2017-01-27_13-25-56](https://cloud.githubusercontent.com/assets/3930855/22367764/4e73ca76-e494-11e6-8aed-653b0827f40c.png)

**Comment by mef1stofel** [comment]
Right button clik on row set focus on a right row.
Maybe I fix it:
when i disable some flag on page browser://flags - it start work good!

**Comment by level420** [comment]
Please report back exactly for which flag set true or false it works or does not work.
Maybe the yandex browser has other defaults as the chrome browser.
And please use current master from github for your tests.
Thank you!

**Comment by mef1stofel** [comment]
There is no problems if #enable-pointer-events flag is False.
I chek on current master: if the flag #enable-pointer-events is "True" or "Default"- selection in lists and tables is wrong (in Yandex Browser).

If you set #enable-pointer-events flag to "True" or "False", or "Default" in Google chrome - it still works, and no problems with selection like in Yandex Browser.
I wrote a Ticket #17012616580229734 to Yandex Browser Support, but they have not yet responded.

**Comment by mef1stofel** [comment]
@level420 can I close this issue?

**Comment by level420** [comment]
@mef1stofel if you think this is not qooxdoos fault, then close this issue. Thank you.
But please, even if it is closed, report back the feedbak of the yandex guys.

**Comment by jonimnim** [comment]
The answer is that anything with Yandex?

**Comment by level420** [comment]
Closing this issue for now. Please feel free to reopen if you think we can do something in qooxdoo to solve the problem. Of course best if you could offer a pull request ;-)
