### ISSUE TITLE
Native pointer events are not sent to qooxdoo preventing swiping on elements on Chrome, platform Android

### ISSUE THREAD

**Issue by lepokle** [qooxdoo/qooxdoo#9283]
Qooxdoo supports native pointer events. However the browser has a default handling for some actions like swiping.
If the browser supports native pointer events (like Chrome 55 on Android) qooxdoo listens to these pointer events to send own track or swipe events.
On the other hand Chrome has a default action for swiping. This results in only about three pointer events for qooxdoo: pointerdown, pointermove, pointercancel. Especially the missing pointermove event is only sent once.
There is a CSS-property which tells the browser whether to do the default handling: `touch-action`, see https://developer.mozilla.org/de/docs/Web/CSS/touch-action.

With setting this property to 'none', all pointerevents are sent to qooxdoo (especially all the pointermoves).

Only setting `touch-action` to `none` for all elements is not a solution if you use native scrolling (as this would disable scrolling as well).

**Comment by level420** [comment]
@lepokle which qooxdoo version do you use? And which part? qooxdoo mobile or desktop? Did you note the fix for chrome 55 in https://github.com/qooxdoo/qooxdoo/pull/9219 ?

**Comment by lepokle** [comment]
Hi @level420,
we used qooxdoo  5.0.2 mobile but are now on master. As far as I understood this has nothing to do with #9219. It is just about how the browser works with pointer events.

Chrome tries to handle swiping on his own therefore he sends a cancel event even if the user is still swiping. This can be avoided by setting the correct touch-action as noted above.

Please also have a look at the discussion on https://github.com/angular/material/issues/10145#issuecomment-275234528.

**Comment by lepokle** [comment]
Note that it could be a problem on all browsers supoorting pointer events.

**Comment by level420** [comment]
@lepokle It seems that you already digged deeper into this subject. Could the solution be to add `touch-action: none` on pointer down event (and remove it on pointer up) for the questionable element or is this to late?
It would be great if you could help us here, optimally by offering a pull request to fix this ;-)
Thank you.

**Comment by johannes-nivus** [comment]
I think the problem is visible on mobile picker:
The picker doesn't snap to an item because the trackend event isn't fired.
This is reproducible with mobile showcase on android chrome.

**Comment by lepokle** [comment]
@level420 I'll try. We used the following fix in our project at the moment but I'm not able to see possible side effects at this time. I've to investigate a little bit more :-(
`
:not(.scoll):not(.native) {
        touch-action: pan-y;
    }
`

**Comment by level420** [comment]
@lepokle thank you for your efforts!
