### ISSUE TITLE
qooxdoo doesn't support es6?

### ISSUE THREAD

**Issue by tiandian** [qooxdoo/qooxdoo#9285]
e.g:
```let a = 1;```
add above es6 code in main, then run "python generate.py source", will show below error:

```
>>> Scanning libraries
>>> Collecting classes   <class 'ecmascript.frontend.SyntaxException.SyntaxException'> :
Unknown operator u'let' (pos (36, 7))
```

thanks!

**Comment by level420** [comment]
@tiandian yes, the python generator ( `generate.py` ) does not support es6. There are some good efforts replacing the python generator by a js based tool qxcompiler which is a contribution by @johnspackman 
Please visit https://github.com/johnspackman/qxcompiler

**Comment by level420** [comment]
@thron7 could we do something to get es6 compatibility into qooxdoo? Thank you in advance.

**Comment by cajus** [comment]
@level420 I don't think that this is a quickie. It would be nice to have something like it, though.

**Comment by level420** [comment]
@cajus yes, we may in the end have to wait for qxcompiler for that. But it costs nothing to ask ;-)

**Comment by thron7** [comment]
@level420 I had a look at a list of es6 features, as I'm not familiar with them. 

I think a lot can be achieved if all that you want is an "accepting" parser, a parser that recognizes es6 syntax as valid and integrates it into the parse tree. Semantic support would be much more effort (like checking that a 'const' is not assigned to again, evaluating an interpolated string, etc.). But accepting is probably what you mean with "compatibility".

A few features are almost trivial ('u' for regexps, Symbol/Set/Map/ArrayBuffer/*Array/Promise/Proxy/Reflect/Intl data types, the new built-in methods, ...). Let's say 1-2 man days.

const, let, arrows, rest and spread parameters, string interpolation, binary/octal literals, expressions as object keys, destructuring assignment of lists, export/import statements with wildcards, most of the class syntax with super and static, yield and function* - these should all be straight forward to add to the parser. Let's say 5-7 man days.

function calls without parens (backticks?), parameter defaults, object properties shorthand, method properties, destructuring assignment of objects, for (... of ...) iterations,  class getters/setters - these might be a bit more tricky. Let's say 10 - 15 man days.

But the effect would just be that the syntax is accepted, and reproduced for the (compressed) build output. No transpilation or such. If you feed it to a runtime (browser, etc.) that doesn't understand it, it breaks.

If I were to do the first and the second block, even if I get into a good rhythm, it would take me several weeks to complete, 6 - 8 at a minimum. But it could easily get longer. Of course I could issue PRs piecewise, one for every new feature, and you could prioritize what you need most. - Would that be worth it?

**Comment by tiandian** [comment]
Is it possible to compile qooxdoo to a signle javascript file eg. qooxdoo.js?
then i use qooxdoo.js as below in html:
```
<script type='text/javascript' src=' qooxdoo.js'></script>
```

then i can use both qooxdoo framework and use es6 too.
because now i needn't use python after compile qooxdoo to a signle javascript file.

thank!

**Comment by level420** [comment]
@thron7 thank you for your detailed elaborations. Reading that, I don't think that it is worth the enormous effort. I think that @johnspackman s qxcompiler is the way to go for es6 as it does tranpiliation via babel.

**Comment by level420** [comment]
@taindin thank you for your last question in comment https://github.com/qooxdoo/qooxdoo/issues/9285#issuecomment-278817125. Please re-ask your question on stackoverlow and tag it with qooxdoo, as I think this is out of the issues scope, but may be of interest for others using qooxdoo with es6. Thank you.

Closing this issue now.
