### ISSUE TITLE
Add possibility to disable promises in build

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9294]
For applications that need to look at the memory they consume or the data that needs to be transferrerd, it would be nice to have some *qx.promises* flag to disable their inclusion. If there's a way to detect the use of pomises (i.e. directly or thry async properties), an automatic detection would be even nicer (maybe in post *generator* times).

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9295
