### ISSUE TITLE
qx.ui,table.pane.Scroller#onTableModelDataChanged: ScrollBarMaximum is calculated after rendering the table pane

### ISSUE THREAD

**Issue by Plasmodino** [qooxdoo/qooxdoo#9296]
this.__tablePane.onTableModelDataChanged(firstRow, lastRow, firstColumn, lastColumn);
      var rowCount = this.getTable().getTableModel().getRowCount();

      if (rowCount != this.__lastRowCount)
      {
        this.updateVerScrollBarMaximum();

        if (this.getFocusedRow() >= rowCount)
        {
          if (rowCount == 0) {
            this.setFocusedCell(null, null);
          } else {
            this.setFocusedCell(this.getFocusedColumn(), rowCount - 1);
          }
        }
        this.__lastRowCount = rowCount;
      }
    },

**this.updateVerScrollBarMaximum();** should be called  before **this.__tablePane.onTableModelDataChanged(firstRow, lastRow, firstColumn, lastColumn);**,
otherwise the updated scrollbar position value might not match the value anymore that was used for rendering the pane.

**Comment by level420** [comment]
@Plasmodino thank you for the bug report. 
It would be good (if this is possible) to have a playground sample showing the bug, and of course, even better, a pull request which solves the bug. Thank you.
