### ISSUE TITLE
"Use of Mutation Events is deprecated. Use MutationObserver instead." warning in Firefox

### ISSUE THREAD

**Issue by firewave** [qooxdoo/qooxdoo#9300]
I am not really sure which widget this actually triggers this, but it somehow originates from inside of the qooxdoo framework  and not the application code (possibly qx.ui.embed.Iframe related?).
I see at least two mutation events in the Firefox debugger - one "DOMContentLoaded" and "DOMNodeInserted" (this seems to trigger the warning) both on something in qooxdoo-5.0.2-sdk/framework/source/class/qx/lang/Function.js. I looked a bit on the web and it appears this warnings has been around for several years now and it appears that Chrome also gave this warning at some point. I am not seeing it in Chrome though.

I am using qooxdoo 5.0.2 and Firefox 52 64-bit on Windows 10.

**Comment by level420** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

It could be that DOM-Events will be deprecated in the future.

**Comment by schnepe2** [comment]
Can someone make a test case for this issue?
It seems that the work-around that has been added (for old [Bug 2756](https://github.com/qooxdoo/qooxdoo/commit/0975a69aadfaca68ed2ae6be2e978085666030a8) rsp. issue #2887)
should also be applied for current Chrome[1].
At least when the scenario is like the one described in #2887

[1] Version 57.0.2987.133 (64-bit)

**Comment by schnepe2** [comment]
By the way: The original issue was, that "relocating" the iframe into another container did not re-render a changed source-URL:
```
container1.add(iframe, {flex: 1});
window.setTimeout(function() {
  iframe.setSource("http://www.ajaxian.com");
  container2.add(iframe, {flex: 1});                    // <= this one !!
}, 5000);
```
...but isn't that something that shouldn't be done?

**Comment by schnepe2** [comment]
I've integrated tests into the PR ( #9314 ) as @oetiker suggested.

**Comment by cboulanger** [comment]
@level420 @schnepe2 @firewave Has this issue been fixed in the meantime by @level420's commit?

**Comment by hkollmann** [comment]
No answer - closed
