### ISSUE TITLE
Website: Community link(s) broken

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9305]
In the footer of the main page, the "Community" heading links to http://www.qooxdoo.org/community.html which does not exist.  

It's also been reported by @JosKar that the link http://www.qooxdoo.org/community/contribution isn't working, but I don't know where yet - @JosKar please could you update this issue with more information?

**Comment by JosKar** [comment]
You can find the link in the readme.rst in the contributing section
https://github.com/qooxdoo/qooxdoo/blob/master/readme.rst#contributing

**Comment by hkollmann** [comment]
We want to modernize the webite - so this is obsolete
