### ISSUE TITLE
Locale is not correctly detected at least on Android >= 4.4.x

### ISSUE THREAD

**Issue by lepokle** [qooxdoo/qooxdoo#9310]
There is some workaround code in qx.bom.client.Locale which tries to read the locale from the user agent string in case of android.
However the bug (http://code.google.com/p/android/issues/detail?id=4641) seems to be fixed at least in 4.4.x.
Therefore the locale can be read from navigator.language for these versions.

**Comment by level420** [comment]
Fixed via #9311
