### ISSUE TITLE
Conflicting property method qx.ui.table.columnmenu.MenuItem.isVisible with qx.ui.core.Widget

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9313]
With the current (master) build, using a table the following warning is logged:
`Conflicting property method qx.ui.table.columnmenu.MenuItem.isVisible with qx.ui.core.Widget`

The auto generated isVisible() method of the `qx.ui.table.columnmenu.MenuItem`s `visible` property triggers this.

So either the changes of commit 51a8c2261eef5feab112e6ba4e5d07e702ddc4d5 need to be changed,
or the name of `MenuItem`s property could be changed,
or the implementation of issue #1911 might have to be changed.

Options (1) or (3) are both not my area of expertise, so I can't provide a PR for this.

The playground surely does not show this 'cause it's not a debug-build.

**Comment by level420** [comment]
@schnepe2 I think it is not the fault of PR https://github.com/qooxdoo/qooxdoo/pull/9232 here, because this PR only reveals that we have a conflict here. The solution would be to change the implementation of `qx.ui.table.columnmenu.MenuItem`

https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/table/columnmenu/MenuItem.js#L32-L38

**Comment by schnepe2** [comment]
I agree, unfortunately we have to change the Interface as well.
Easy to change that property name to "`shown`". But that name feels kind of edgy. Anyone here with a nicer name?

**Comment by schnepe2** [comment]
I still don't really like the property's name "`show`", but unless someone comes with a better idea / name:
Take it or leave it.

**Comment by oetiker** [comment]
how about calling it `columnVisible`

**Comment by schnepe2** [comment]
@oetiker Done! Still not perfect, but much better than `shown` :+1:

**Comment by level420** [comment]
Fixed via #9317
