### ISSUE TITLE
VirtualComboBox - Selection does not hide when tab is switched

### ISSUE THREAD

**Issue by helmut-kleinhans** [qooxdoo/qooxdoo#9319]
in case there is a VirtualComboBox placed inside a tab and the selection is opened by cursor down, but no selection is made and then the user clicked into the next tab the selection box is not closed. the box is still showing but at screenposition x=0,y=0  

You can test that in the first tab of the top tabview where the combobox is placed in the  [playground](http://www.qooxdoo.org/5.0.2/playground/#%7B%22code%22%3A%22%252F*%2520************************************************************************%250A%250A%2520%2520%2520qooxdoo%2520-%2520the%2520new%2520era%2520of%2520web%2520development%250A%250A%2520%2520%2520http%253A%252F%252Fqooxdoo.org%250A%250A%2520%2520%2520Copyright%253A%250A%2520%2520%2520%2520%25202004-2008%25201%25261%2520Internet%2520AG%252C%2520Germany%252C%2520http%253A%252F%252Fwww.1und1.de%250A%250A%2520%2520%2520License%253A%250A%2520%2520%2520%2520%2520LGPL%253A%2520http%253A%252F%252Fwww.gnu.org%252Flicenses%252Flgpl.html%250A%2520%2520%2520%2520%2520EPL%253A%2520http%253A%252F%252Fwww.eclipse.org%252Forg%252Fdocuments%252Fepl-v10.php%250A%2520%2520%2520%2520%2520See%2520the%2520LICENSE%2520file%2520in%2520the%2520project%27s%2520top-level%2520directory%2520for%2520details.%250A%250A%2520%2520%2520Authors%253A%250A%2520%2520%2520%2520%2520*%2520Sebastian%2520Werner%2520(wpbasti)%250A%2520%2520%2520%2520%2520*%2520Fabian%2520Jakobs%2520(fjakobs)%250A%250A************************************************************************%2520*%252F%250A%250A%252F*%2520************************************************************************%250A%250A%250A************************************************************************%2520*%252F%250A%252F**%250A%2520*%250A%2520*%2520%2540asset(qx%252Ficon%252F%2524%257Bqx.icontheme%257D%252F16%252Fapps%252Futilities-terminal.png)%250A%2520*%2520%2540asset(qx%252Ficon%252F%2524%257Bqx.icontheme%257D%252F32%252Fapps%252Futilities-terminal.png)%250A%2520*%2520%2540asset(qx%252Ficon%252F%2524%257Bqx.icontheme%257D%252F16%252Fapps%252Futilities-notes.png)%250A%2520*%2520%2540asset(qx%252Ficon%252F%2524%257Bqx.icontheme%257D%252F16%252Fapps%252Futilities-calculator.png)%250A%2520*%2520%2540asset(qx%252Ficon%252F%2524%257Bqx.icontheme%257D%252F16%252Fapps%252Futilities-help.png)%250A%2520*%252F%250A%250Aqx.Class.define(%2522demobrowser.demo.widget.TabView%2522%252C%250A%257B%250A%2520%2520extend%2520%253A%2520qx.application.Standalone%252C%250A%250A%2520%2520members%2520%253A%250A%2520%2520%257B%250A%2520%2520%2520%2520main%253A%2520function()%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520this.base(arguments)%253B%250A%250A%2520%2520%2520%2520%2520%2520var%2520scroller%2520%253D%2520new%2520qx.ui.container.Scroll()%253B%250A%250A%2520%2520%2520%2520%2520%2520var%2520container%2520%253D%2520new%2520qx.ui.container.Composite(new%2520qx.ui.layout.VBox(10))%253B%250A%2520%2520%2520%2520%2520%2520container.setPadding(20)%253B%250A%2520%2520%2520%2520%2520%2520container.setAllowStretchX(false)%253B%250A%250A%2520%2520%2520%2520%2520%2520scroller.add(container)%253B%250A%250A%2520%2520%2520%2520%2520%2520this.getRoot().add(scroller%252C%2520%257Bedge%2520%253A%25200%257D)%253B%250A%250A%2520%2520%2520%2520%2520%2520container.add(this.getTabView1())%253B%250A%2520%2520%2520%2520%2520%2520container.add(this.getTabView2())%253B%250A%2520%2520%2520%2520%2520%2520container.add(this.getTabView3())%253B%250A%2520%2520%2520%2520%257D%252C%250A%250A%2520%2520%2520%2520getTabView1%2520%253A%2520function()%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520var%2520tabView%2520%253D%2520new%2520qx.ui.tabview.TabView()%253B%250A%2520%2520%2520%2520%2520%2520tabView.setWidth(500)%253B%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%2520TEST%2520PAGE%25201%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%2520%2520%2520%2520%2520%2520var%2520page1%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Layout%2522%252C%2520%2522icon%252F16%252Fapps%252Futilities-terminal.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520page1.setLayout(new%2520qx.ui.layout.VBox())%253B%250A%2520%2520%2520%2520%2520%2520page1.add(new%2520qx.ui.basic.Label(%2522Layout-Settings%2522))%253B%250A%2520%2520%2520%2520%2520%2520var%2520fu%2520%253D%2520new%2520qx.data.Array(%255B%27a%27%252C%27b%27%252C%27c%27%255D)%253B%250A%2520%2520%2520%2520%2520%2520var%2520combobox%2520%253D%2520new%2520qx.ui.form.VirtualComboBox(fu)%253B%250A%2520%2520%2520%2520%2520%2520%250A%2520%2520%2520%2520%2520%2520page1.add(combobox)%253B%250A%2520%2520%2520%2520%2520%2520tabView.add(page1)%253B%250A%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%2520TEST%2520PAGE%25202%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%2520%2520%2520%2520%2520%2520var%2520page2%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Notes%2522%252C%2520%2522icon%252F16%252Fapps%252Futilities-notes.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520page2.setLayout(new%2520qx.ui.layout.VBox())%253B%250A%2520%2520%2520%2520%2520%2520page2.add(new%2520qx.ui.basic.Label(%2522Notes...%2522))%253B%250A%2520%2520%2520%2520%2520%2520tabView.add(page2)%253B%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%2520TEST%2520PAGE%25203%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%2520%2520%2520%2520%2520%2520var%2520page3%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Calculator%2522%252C%2520%2522icon%252F16%252Fapps%252Futilities-calculator.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520page3.setLayout(new%2520qx.ui.layout.VBox())%253B%250A%2520%2520%2520%2520%2520%2520page3.add(new%2520qx.ui.basic.Label(%2522Calculator...%2522))%253B%250A%2520%2520%2520%2520%2520%2520tabView.add(page3)%253B%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%2520TEST%2520PAGE%25204%2520%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%2520%2520%2520%2520%2520%2520var%2520page4%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Help%2522%252C%2520%2522icon%252F16%252Fapps%252Futilities-help.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520page4.setLayout(new%2520qx.ui.layout.VBox())%253B%250A%2520%2520%2520%2520%2520%2520page4.add(new%2520qx.ui.basic.Label(%2522Help...%2522))%253B%250A%2520%2520%2520%2520%2520%2520tabView.add(page4)%253B%250A%250A%250A%2520%2520%2520%2520%2520%2520return%2520tabView%253B%250A%2520%2520%2520%2520%257D%252C%250A%250A%250A%2520%2520%2520%2520getTabView2%2520%253A%2520function()%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520var%2520tabView%2520%253D%2520new%2520qx.ui.tabview.TabView()%253B%250A%2520%2520%2520%2520%2520%2520tabView.setWidth(500)%253B%250A%250A%2520%2520%2520%2520%2520%2520for%2520(var%2520i%253D1%253B%2520i%253C%253D20%253B%2520i%252B%252B)%250A%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520page%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Page%2520%2523%2522%2520%252B%2520i%252C%2520%2522icon%252F16%252Fapps%252Futilities-terminal.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520page.setLayout(new%2520qx.ui.layout.VBox())%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520page.setShowCloseButton(true)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520page.add(new%2520qx.ui.basic.Label(%2522Page%2520%2523%2522%2520%252B%2520i%2520%252B%2520%2522%2520with%2520close%2520button.%2522))%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520tabView.add(page)%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520return%2520tabView%253B%250A%2520%2520%2520%2520%257D%252C%250A%250A%250A%2520%2520%2520%2520getTabView3%2520%253A%2520function()%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520var%2520tabView%2520%253D%2520new%2520qx.ui.tabview.TabView()%253B%250A%2520%2520%2520%2520%2520%2520tabView.setWidth(500)%253B%250A%2520%2520%2520%2520%2520%2520tabView.setHeight(300)%253B%250A%250A%2520%2520%2520%2520%2520%2520for%2520(var%2520i%253D1%253B%2520i%253C%253D3%253B%2520i%252B%252B)%250A%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520page%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Page%2520%2523%2522%2520%252B%2520i%252C%2520%2522icon%252F32%252Fapps%252Futilities-terminal.png%2522)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520page.setLayout(new%2520qx.ui.layout.VBox(4))%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520tabView.add(page)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520page.add(new%2520qx.ui.basic.Label(%2522Page%2520%2523%2522%2520%252B%2520i))%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520%2520%2520var%2520firstPage%2520%253D%2520tabView.getChildren()%255B0%255D%253B%250A%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%2520CONTROL%2520BAR%2520POSITION%250A%250A%2520%2520%2520%2520%2520%2520var%2520barLabel%2520%253D%2520new%2520qx.ui.basic.Label(%2522Bar%2520Position%2522)%253B%250A%250A%2520%2520%2520%2520%2520%2520var%2520barTopButton%2520%253D%2520new%2520qx.ui.form.RadioButton(%2522top%2522)%253B%250A%2520%2520%2520%2520%2520%2520var%2520barBottomButton%2520%253D%2520new%2520qx.ui.form.RadioButton(%2522bottom%2522)%253B%250A%2520%2520%2520%2520%2520%2520var%2520barLeftButton%2520%253D%2520new%2520qx.ui.form.RadioButton(%2522left%2522)%253B%250A%2520%2520%2520%2520%2520%2520var%2520barRightButton%2520%253D%2520new%2520qx.ui.form.RadioButton(%2522right%2522)%253B%250A%250A%2520%2520%2520%2520%2520%2520firstPage.add(new%2520qx.ui.core.Spacer(10%252C%252010))%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(barLabel)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(barTopButton)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(barBottomButton)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(barLeftButton)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(barRightButton)%253B%250A%250A%2520%2520%2520%2520%2520%2520var%2520group%2520%253D%2520new%2520qx.ui.form.RadioGroup(barTopButton%252C%2520barBottomButton%252C%2520barLeftButton%252C%2520barRightButton)%253B%250A%2520%2520%2520%2520%2520%2520group.addListener(%2522changeSelection%2522%252C%2520function(e)%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.setBarPosition(e.getData()%255B0%255D.getLabel())%253B%250A%2520%2520%2520%2520%2520%2520%257D%252C%2520tabView)%253B%250A%250A%2520%2520%2520%2520%2520%2520barLeftButton.setValue(true)%253B%250A%250A%250A%2520%2520%2520%2520%2520%2520%252F%252F%2520ADD%252FREMOVE%2520BUTTONS%250A%250A%2520%2520%2520%2520%2520%2520var%2520buttonAdd%2520%253D%2520new%2520qx.ui.form.Button(%2522Add%2520new%2520page%2522)%253B%250A%2520%2520%2520%2520%2520%2520var%2520buttonRemoveFirst%2520%253D%2520new%2520qx.ui.form.Button(%2522Remove%2520first%2520page%2522)%253B%250A%2520%2520%2520%2520%2520%2520var%2520buttonRemoveLast%2520%253D%2520new%2520qx.ui.form.Button(%2522Remove%2520last%2520page%2522)%253B%250A%250A%2520%2520%2520%2520%2520%2520firstPage.add(new%2520qx.ui.core.Spacer(10%252C%252010))%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(buttonAdd)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(buttonRemoveFirst)%253B%250A%2520%2520%2520%2520%2520%2520firstPage.add(buttonRemoveLast)%253B%250A%250A%2520%2520%2520%2520%2520%2520buttonAdd.addListener(%2522execute%2522%252C%2520function(e)%250A%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520count%2520%253D%2520tabView.getChildren().length%252B1%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520page%2520%253D%2520new%2520qx.ui.tabview.Page(%2522Page%2520%2523%2522%2520%252B%2520count%252C%2520%2522icon%252F32%252Fapps%252Futilities-terminal.png%2522)%253B%250A%250A%2520%2520%2520%2520%2520%2520%2520%2520tabView.add(page)%253B%250A%2520%2520%2520%2520%2520%2520%257D)%253B%250A%250A%2520%2520%2520%2520%2520%2520buttonRemoveFirst.addListener(%2522execute%2522%252C%2520function(e)%250A%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520children%2520%253D%2520tabView.getChildren()%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(children.length%2520%253E%25200)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520tabView.remove(children%255B0%255D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%257D)%253B%250A%250A%2520%2520%2520%2520%2520%2520buttonRemoveLast.addListener(%2522execute%2522%252C%2520function(e)%250A%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520var%2520children%2520%253D%2520tabView.getChildren()%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(children.length%2520%253E%25200)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520tabView.remove(children%255Bchildren.length-1%255D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%257D)%253B%250A%250A%2520%2520%2520%2520%2520%2520return%2520tabView%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D%250A%257D)%253B%250A%22%2C%20%22mode%22%3A%22ria%22%7D)

**Comment by cajus** [comment]
What do I have to do to reproduce it in the playground? The opened selectbox closes directly when I change tabs.

**Comment by cajus** [comment]
Wait. You're right. Managed to get the issue in Chrome.

**Comment by hkollmann** [comment]
Reproducable in current master. Must be fixed

**Comment by hkollmann** [comment]
fixed with #9827
