### ISSUE TITLE
Key repetition (in Table) broken

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9323]
It seems like the key repetition (at least for Tables) is broken.

To show the issue: Select a cell and hold the cursor down, to scroll through the table
http://www.qooxdoo.org/devel/playground/#Table-ria

Version 5.0.2 does not have this issue:
http://www.qooxdoo.org/5.0.2/playground/#Table-ria

Cursor- Up/Down and page-Up/Down do not repeat.

**Comment by level420** [comment]
@schnepe2 

Tested http://www.qooxdoo.org/devel/playground/#Table-ria on following OS and browsers:

Windows 7 x64 
* Chrome 59: cursor keys **OK**, page up/down **OK**
* IE 11: cursor keys **NOT OK**, page up/down **NOT OK**
* Firefox 53: cursor keys **NOT OK**, page up/down **NOT OK**
* Opera 45: cursor keys **OK**, page up/down **OK**

Windows 10
* Chrome 59: cursor keys **OK**, page up/down **OK**
* IE 11: cursor keys **NOT OK**, page up/down **NOT OK**
* Firefox 53: cursor keys **NOT OK**, page up/down **NOT OK**
* Edge: cursor keys **OK**, page up/down **OK**

macOS 10.12.5
* Safari 10.1.1:  cursor keys **OK**, page up/down **OK**
* Firefox 53: cursor keys **OK**, page up/down **OK**
* Chrome 59: cursor keys **OK**, page up/down **OK**

@schnepe2 could you please add your OS and browser? Thank you.

**Comment by schnepe2** [comment]
Here the ones that **fail**:

Windows 10 (x64)
- PaleMoon 27.3.0 (32-bit)
- Firefox 53.0.3 (32-Bit)
- IE 11


Working though:
- Chrome 58.0.3029.110 (64-bit)
- Chrome 59.0.3071.86 (64-Bit)
- Edge 40.15063.0.0

**Comment by hkollmann** [comment]
Just tested with http://www.qooxdoo.org/apps/playground/#Table-ria in IE 11 and it works
