### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#9324]
Basic TypeScript support would be of great benefit for static syntax checking as well as IDE integration.

E.g. @pdfisk announced yesterday in [qooxdoo-devel] that he is using Qooxdoo with TypeScript extensions to ease development of his [pdfisk/vista-basic](https://github.com/pdfisk/vista-basic) framework. In particular, Qooxdoo classes are mapped to TypeScript, which allows for easy IDE integration.
![vb-client-typescript](http://vistabasic.com/wp-content/uploads/2017/05/vb-client-typescript.png)
> Above is some TypeScript code extending the Qooxdoo framework. Qooxdoo is a fantastic JavaScript framework that should be much more popular than it seems to be at the moment.

from: http://vistabasic.com/index.php/2017/05/06/in-praise-of-qooxdoo/

However, the repository above did not (yet) contain the TypeScript extensions mentioned. After some more research, I stumbled upon @jbaron's work on Code Assistant for Type Script (CATS) at [jbaron/cats](https://github.com/jbaron/cats) which is basically a full TypeScript IDE. Its extension [jbaron/qx-parser](https://github.com/jbaron/qx-typed) allows to generate a [qooxdoo.d.ts](https://github.com/jbaron/qx-parser/blob/master/qooxdoo.d.ts) typings file by reading qooxdoo's API documentation. 

It would be great if @pdfisk and @jbaron could help us to integrate the TypeScript Definition files into the main qooxdoo repository as I am sure many (especially new) qooxdoo users will benefit from it!

**Comment by pdfisk** [comment]
I will make the TypeScript extensions available.

They were originally generated by "qx-parser" and I have been adding in missing typings as needed.

**Comment by pdfisk** [comment]
Vista Basic client code is now on GitHub.
https://github.com/pdfisk/vista-client

The typings file is here:
https://github.com/pdfisk/vista-client/tree/master/src/qkwidgets/types

**Comment by tcsaddul** [comment]
This is great news to TypeScript coders like me.

**Comment by johnspackman** [comment]
Looking at the jbaron's qooxdoo.d.ts it should be quite straightforward to build a target for qxcompiler that provides this; I'll add an issue

**Comment by tcsaddul** [comment]
I hope the qooxdoo team will consider adding "official" support for TypeScript and make it easily accessible to newcomers.

Here is another UI framework I've been following the following for years which is very much like qooxdoo:  www.webix.com which has now also supports TypeScript:  https://blog.webix.com/typescript-types-in-webix-ui-framework/

Here is their typescript definition:  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webix

**Comment by hkollmann** [comment]
qx can produce ts file
