### ISSUE TITLE
qx.ui.table.pane.Scroller.js: Dragging of items does not work anymore after editing a table cell

### ISSUE THREAD

**Issue by Plasmodino** [qooxdoo/qooxdoo#9334]
In `startEditing()` a pointerdown-listener is attached to `this.__focusIndicator`:

```javascript
// prevent tap event from bubbling up to the table
this.__focusIndicator.addListener("pointerdown", function(e) {
    this.__lastPointerDownCell = {
         row : this.__focusedRow,
         col : this.__focusedCol
    };
    e.stopPropagation();
}, this);
```

This listener is not removed anymore in `cancelEditing()`:
```javascript
cancelEditing : function() {
      if (this.isEditing())
      {
        if (!(this._cellEditor instanceof qx.ui.window.Window))
        {
          this.__focusIndicator.removeState("editing");
          this.__focusIndicator.setKeepActive(true);
        }
        this._cellEditor.destroy();
        this._cellEditor = null;
        this.__cellEditorFactory = null;
      }
    },
```
The listener keeps on catching pointerdown-events by stopping event propagation. Solution is to save the listener-id and then remove the listener again in `cancelEditing()`.

**Comment by johnspackman** [comment]
Sounds reasonable - please can you put your fix forward as a Pull Request?

**Comment by level420** [comment]
@Plasmodino thank you for your bug report. It would be very nice if you could provide your proposed fix as a pull request. As you obviously are affected by the bug you could test the fix in your app. Thank you.

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9357
