### ISSUE TITLE
qx.ui.form.renderer.Single: Flex setting for wrong column?

### ISSUE THREAD

**Issue by BaaaZen** [qooxdoo/qooxdoo#9339]
In line 31 the flex setting is activated for column 0:

`layout.setColumnFlex(0, 1);`

Column 0 is the column for the labels. Is that correct? So the labels get stretched and the form fields stay small.
Shouldn't line 31 be:

`layout.setColumnFlex(1, 1);`

**Comment by kreimer** [comment]
I agree. I have something like

            renderer.getLayout().setColumnWidth(0, 128);
            renderer.getLayout().setColumnFlex(0, 0);
            renderer.getLayout().setColumnFlex(1, 3);

in my code as well.

**Comment by johnspackman** [comment]
Although I don't use Form's myself, this sounds like a reasonable change to me; please can you propose it as a Pull Request?  This is usually the best and fastest way to get a proposed change into the library

**Comment by BaaaZen** [comment]
Pull request: https://github.com/qooxdoo/qooxdoo/pull/9341
