### ISSUE TITLE
Updating developer documentation for qx 6.0

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9343]
@oetiker can you create a repository "qx-dev-manual" (or whatever name seems fitting)

**Comment by cboulanger** [comment]
Created https://github.com/qooxdoo/qx-dev-manual

However, it makes more sense to re-integrate the developer manual into the qooxdoo framework source code, replacing the existing [tech manual](https://github.com/qooxdoo/qooxdoo/tree/master/documentation/tech_manual). This will happen as soon as we have updated the manual.

**Comment by cboulanger** [comment]
- [ ] Style guide: Important for contributors. Should come with a linter file for client and server (nodejs-stuff)

**Comment by derrell** [comment]
@oetiker I think this is related to work you've done recently? Can this be closed?

**Comment by cboulanger** [comment]
Issue solved, we use  https://github.com/qooxdoo/qx-dev-manual for contributor info & governance issues
