### ISSUE TITLE
travis ci failing with latest chrome unstable

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9349]
We are getting the following messages when trying to start chrome:

```
14 06 2017 12:28:20.640:ERROR [launcher]: Cannot start Chrome
	[3750:3762:0614/122820.429774:ERROR:bus.cc(422)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Xlib:  extension "RANDR" missing on display ":99.0".
[3750:3777:0614/122820.443087:FATAL:nss_util.cc(679)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.

```

**Comment by level420** [comment]
@cajus could you please have a look into this if we could do something here? As chrome since version 59 supports headless mode, we could maybe run the tests without xvfb

See 

- https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
- https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by cajus** [comment]
@level420 I've updated it to run headless locally, but it's more about the incompatible NSS version.

**Comment by level420** [comment]
Ah. I see ... So it's about choosing another ubuntu version for the container based tests which hopefully have a more up to date NSS?

**Comment by level420** [comment]
Seems that travis ci offers ubuntu 14.04 LTS
https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
which offers nss v 3.28 which would fit:
https://launchpad.net/ubuntu/trusty/+source/nss

**Comment by oetiker** [comment]
oh :-) we might want to upgrade

**Comment by oetiker** [comment]
adding `dist: trusty` to the .travis file should do the trick

**Comment by cboulanger** [comment]
Any progress on this?

**Comment by peuter** [comment]
I get the same error in another project using pretty much the same build environment. I already use the `trusty` dist, so the upgrade does not solve the problem.

**Comment by peuter** [comment]
Travis trusty image is a little bit outdated, it uses libnss3 in version 3.23. When you upgrade the package (`sudo apt-get --only-upgrade install libnss3`) to 3.28, the error is gone.

**Comment by oetiker** [comment]
can you do a PR for the .travis.yml ?

**Comment by peuter** [comment]
I can try, I have to check if using the "trusty" image introduces new errors.

**Comment by cajus** [comment]
Well. We spent *much* time to have a container based build - and the ticket is currently assigned to me.

**Comment by cajus** [comment]
As travis sucks from time to time, and I spent countless hours into various problems until now, I tend to make a docker image of our own which contains a *recent* distribution. Trusty is "beta" on travis side - and it's more than outdated in real life.

**Comment by cajus** [comment]
I've fixed the two errors (headless / travis beta container) and we're green again. I'll leave this issue open for the docker image - to get rid off the travis container dependency.

**Comment by oetiker** [comment]
yes that seems rather odd I wonder what makes it so hard for them to offer current images

**Comment by level420** [comment]
seems to work again: https://travis-ci.org/qooxdoo/qooxdoo/builds/246984619

**Comment by level420** [comment]
thank you @cajus

**Comment by sfc0907** [comment]
I am facing the same issue with NSS_VersionCheck.My Ubuntu's version is 14.04LTS.I try this command sudo apt-get --only-upgrade install libnss3,but it seems that the vesion is 3.15.Do you have any ideas about this?Thank you.

**Comment by leothor2015** [comment]
> Travis trusty image is a little bit outdated, it uses libnss3 in version 3.23. When you upgrade the package (sudo apt-get --only-upgrade install libnss3) to 3.28, the error is gone.

This one solved the issue. Thanks.

**Comment by smartm0use** [comment]
@peuter 's solution works, it does the trick! Thank you!

**Comment by hkollmann** [comment]
Done.
