### ISSUE TITLE
CheckGroupBox does not disable inner elements when the parent element gets disabled

### ISSUE THREAD

**Issue by helmut-kleinhans** [qooxdoo/qooxdoo#9350]
You could use this code to see the result in the playground. 
When you click the "disable window" button everything works fine, but when the checkbox of the CheckGroupBox is operated twice (deactivate/activate) the inner elements are not longer set to disabled if the window is set to disabled. 

==================== playground sample =============================
`
var win = new qx.ui.window.Window("First Window");
win.setWidth(300);
win.setHeight(200);
win.setShowMinimize(false);
win.setLayout( new qx.ui.layout.VBox() );

var btn1 = new qx.ui.form.Button('disable window')
var btn2 = new qx.ui.form.Button('enable window')
var btn3 = new qx.ui.form.Button('a button in the group box')
btn1.addListener('execute',function(){win.setEnabled(false)});
btn2.addListener('execute',function(){win.setEnabled(true)});
btn3.addListener('execute',function(){ qx.log.Logger.info(qx.application.Standalone,'click done')});

win.add(btn1 );
var groupbox = new qx.ui.groupbox.CheckGroupBox("test group");
groupbox.setLayout( new qx.ui.layout.VBox() );
groupbox.add( btn3 );
win.add(groupbox);

this.getRoot().add(btn2,{left:20, top:10});

this.getRoot().add(win, {left:150, top:10});
win.open();
`

**Comment by level420** [comment]
Verified on master and 5.0.2: both show the described effect.
