### ISSUE TITLE
Window not focusing in Chrome

### ISSUE THREAD

**Issue by MakotoNinja** [qooxdoo/qooxdoo#9356]
There appears to be a bug in Chrome when opening a window from a button where the window isn't focused right away, even if the button is set to focusable : false and keepFocus : false and explicitly calling focus on the window via appear listener.
Here is a playground example: http://tinyurl.com/yclhxrg2
In the example (using Chrome) if you click the 'Launch Window' button, a window opens and if you hit 'Enter', the button executes again, however, if you hit 'Enter' again, the window receives the event.
Works as expected in FF.

Dietrich Streifert @level420 responded on gitter with the following:
_@MakotoNinja it seems to be some timing issue. If the call to win.open() in the onExecuteevent handler is de-coupled via a timer function like this qx.event.Timer.once(function() { this.open(); }, win, 0); it works as expected. See the modified playgrouns sample http://tinyurl.com/yapyw62j
@MakotoNinja please open an issue for this. thank you._

**Comment by level420** [comment]
Verified von chrome and edge.

**Comment by hkollmann** [comment]
Working in the current Chrome version.
