### ISSUE TITLE
Chrome: blocker does not block keyboard events

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9393]
Here's how to reproduce it:

 * open [the playground](http://tinyurl.com/y9fk83ow) in google chrome
 * click on the 'Button' (a modal window opens)
 * press "Enter" or "Space"

What happens:
 * the "Button" is executed a second time, opening another modal window

What is expected to happen:
 * nothing, because the button is blocked by the modal window

The problem only exists in Chrome. Firefox does not open the second window. Note, that it only works once.

**Comment by cboulanger** [comment]
It doesn't exist in Safari (11.0) either. But I know this problem from my Dialog contrib demo, it would be great to find out the source of it

**Comment by cajus** [comment]
@cboulanger I'll have time to inspect it later today, but there's some hope that someone *facepalms* and knows why it happens ;-)

**Comment by mbgonicus** [comment]
Chrome natively fires both - a pointerup and a mouseup event (in that order). The pointerup results in an execute event on the button and finally opens the dialog. Then the mouseup event is received resulting in the button getting the focus. While focussed it receives the keyboard events and can fire an execute event again.

**Comment by level420** [comment]
Is it the normal behavior of other browsers that they get the focus on mouseup?
