### ISSUE TITLE
Bug? Model-to-target converter is called multiple times.

### ISSUE THREAD

**Issue by chrisch-hh** [qooxdoo/qooxdoo#9405]
Take a look at this playground example: http://tinyurl.com/y9w9knuk

I've bound a store model to a form controller model with a converter function. The converter function is called multiple times (see the console log). The first times it is called with null, the last time it is called with the correct value. I don't know if its a bug or if its the intended behavior or my mistake, but I think the converter function should be called only once.

**Comment by chrisch-hh** [comment]
And another thing: The signature of the converter function according to the [SingleValueBinding](http://www.qooxdoo.org/current/api/#qx.data.SingleValueBindingl)  is: 

`converter : function(data, model, source, target) {};`

But the `model` parameter is always `undefined` in my playground example...?

**Comment by cajus** [comment]
@chrisch-hh that's because you've an undefined model initially. Change

```      
      // add converter to firstName binding
      controller.addBindingOptions("firstName", model2target, target2model);

      // bind store model with form controller model
      store.bind("model", controller, "model");
```

to

```
      // bind store model with form controller model
      store.bind("model", controller, "model");
      
      // add converter to firstName binding
      controller.addBindingOptions("firstName", model2target, target2model);
```

in order to have an initialized model. Your converter will be only called once in this case. The reason is that the property chaining tries to resolve a "null" source and then runs into a fallback.

**Comment by hkollmann** [comment]
@cajus answered this on 12 Oct 2017.
