### ISSUE TITLE
Unreachable Code in qx.Promise

### ISSUE THREAD

**Issue by FriedrichF** [qooxdoo/qooxdoo#9413]
Firefox prints a warning, that in the Promise.js (https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/Promise.js#L6374) there is unreachable Code. Should this line be deleted or do i miss something?

**Comment by level420** [comment]
@johnspackman could you please have a look into this? thank you!

**Comment by derrell** [comment]
@johnspackman ping.

**Comment by hkollmann** [comment]
it's a copy from bluebird. Should be fixed there. Or remove bluebird
