### ISSUE TITLE
Review "experimental" status of classes

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9418]
A number of classes in the framework are marked as "experimental" and have been like this for years - but the classes themselves have become such established components of Qooxdoo that they benefit from just as much concern over maintenance and backwards compatibility as any other class.  There is an argument then that these are no longer "experimental" at all.

We should review the classes and consider dropping the "experimental" status

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9826
