### ISSUE TITLE
Check whether CLDR can be replaced by Intl

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9419]
We've some dependency to CLDR. It looks like all or parts of it can be replaced by the browsers `Intl` faciilty. Needs to be checked as it would remove one dependency and speed up load time.

See [here](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl) for more details.

**Comment by hkollmann** [comment]
changed with compiler
