### ISSUE TITLE
Tab key not working if you click outside a modal window and then return to the window

### ISSUE THREAD

**Issue by AmjadKh** [qooxdoo/qooxdoo#9449]
in desktop:
when you open a window with controls in it, if you press tab key it will navigate correctly, but if you click outside the window and then click inside the window, the cursor remains on the textfield and will not move to the next control.
I notices also, not only the Tab key not working, also Space key not working when you press it on buttons.

**Comment by level420** [comment]
Verified on current chrome 63 and firefox 57.

**Comment by level420** [comment]
Only true for modal windows

**Comment by level420** [comment]
Same as ##8104

**Comment by AmjadKh** [comment]
Thanks for your reply.
It is strange that the issue is exist 4 years ago and still not resolved

**Comment by level420** [comment]
@AmjadKh please have a look into PR https://github.com/qooxdoo/qooxdoo/pull/9466 and report back if it solves the issue for you. Thank you.
