### ISSUE TITLE
populate "files" key in package.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9450]
@johnspackman @hkollmann In order not to upload the whole of the qooxdoo-sdk to NPM when all we need is the "framework" folder, we need to set the "files" key in `package.json`:

https://github.com/npm/npm/wiki/Files-and-Ignores

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9464
