### ISSUE TITLE
move readme.rst to readme.md

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9456]
the readme for on npm must be in md format to be recognized.
The current Version in qooxdoo is rst format.

Problem to change: In .travis/make-release-sdk line 58 the readme.rst is transformed into readme.html for the pages. This is done by a python script rst2html. 

Any ideas how to handle this? 
One idea is to use an npm based package, found here: https://www.npmjs.com/package/md2html

Better ideas?

**Comment by johnspackman** [comment]
transforming .rst to .md sounds like a good plan to me 👍

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9464
