### ISSUE TITLE
Some iframe related tests fail in testrunner in full run, but not if run separately

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9467]
All failing tests are somehow iframe related. I suspect that it has something to do with the native iframe "load" event not being fired or not bubbling up to the listeners. The problem is, that if you don't run the test completely but just start each section separately and run them in linear order, starting from "application" to "util" you won't see the tests failing which makes it horrible to debug, as it always needs a refresh and a full run til it breaks.

**Comment by level420** [comment]
It should be discussed if it would be possible to split the monolithic travis runs into single sections, to allow running as the tests do not fail this way. At least not if you run them interactively/manually by clicking on the sections and hitting the "run tests" button. This would result in 20 separate runs of testrunner, where we additionally have to move the test classes `qx.test.*` into `qx.test.base` to have them in one section.

**Comment by hkollmann** [comment]
We will rework the tests to use the compiler. We should'nt change the current build chain anymore
