### ISSUE TITLE
Unify npm package names

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9471]
Currently we have:

* qooxdoo-sdk
* qx-cli
* qxcompiler

This doesn't feel very streamlined. Long version:

 * qooxdoo-sdk
 * qooxdoo-cli
 * qooxdoo-compiler

or short version

 * qx-sdk
 * qx-cli
 * qx-compiler

or something else?

Publishing it as *qooxdoo-sdk* when it becomes *qx-sdk* will not make sense. Except it's possible to remove these entries again.

**Comment by hkollmann** [comment]
There already exists a qooxdoo-sdk on npm

**Comment by level420** [comment]
We should go with
- qx-sdk
- qx-cli
- qx-compiler
if possible

**Comment by johnspackman** [comment]
I quite like the longer `qooxdoo-*` versions, it's immediately recognisable and better for search engines.

**Comment by cajus** [comment]
[![](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/Use%20qooxdoo-*)](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/Use%20qooxdoo-*/vote)
[![](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/Use%20qx-*)](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/Use%20qx-*/vote)
[![](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/I%20don't%20care)](https://api.gh-polls.com/poll/01C1NBVETC3AFXSGHGA9PF4MRK/I%20don't%20care/vote)

**Comment by derrell** [comment]
I prefer the longer `qooxdoo-*` version. Whose is the existing `qooxdoo-sdk` that's in npm?

**Comment by derrell** [comment]
Uggh. I clicked on the fuel bars to bring up the voting, only to discover that where i clicked registered my vote. I do *not* want to vote for qx-*, i want to vote for `qooxdoo-*`

**Comment by johnspackman** [comment]
`qooxdoo-sdk` is ours, now - the original author handed it over to us

**Comment by cajus** [comment]
Stupid poll. You can vote as often as you want :-(

**Comment by johnspackman** [comment]
But it doesn't count up extra times - I tried voting twice and it didn't increase the count




On Mon, Dec 18, 2017 at 6:15 PM +0000, "Cajus Pollmeier" <notifications@github.com> wrote:












Stupid poll. You can vote as often as you want :-(

**Comment by cboulanger** [comment]
Closing in favor of #9663
