### ISSUE TITLE
python build process error

### ISSUE THREAD

**Issue by rkroboth** [qooxdoo/qooxdoo#9473]
I keep running into a python build error.

I have a linux system that is mounting an OSX server. The qooxdoo library is all on this mount point. When I run the generate.py to build my project, I get the following Python error:

```
Traceback (most recent call last):
  File "/mnt/proj/qooxdoo/tool/bin/generator.py", line 27, in <module>
    from generator import Generator
  File "/mnt/proj/qooxdoo/tool/pylib/generator/Generator.py", line 29, in <module>
    from generator.code.DependencyLoader import DependencyLoader
  File "/mnt/proj/qooxdoo/tool/pylib/generator/generator.py", line 29, in <module>
    from generator.code.DependencyLoader import DependencyLoader
```

I believe the problem is with mounted file systems that are case-insensitive (OSX and Windows), the python files can't have a directory name that is the same as a classname under it, or else the python import system seems to import the classes in the directory into the wrong scope?

I encounter this problem when the mount point is either an OSX or a windows file system.  I don't have the problem when the mount point is a linux file system.

For example, if I change the name of the directory "pylib/generator" to just "pylib/gen", and change the python import lines in the code to reflect that  -- like "from gen.code.DependencyLoader import DependencyLoader" ---  then it seems to get past this error (although there are other class files under directories of the same name, so the problem just occurs further along)

And of course if I just copy the entire thing into a local non-mounted directory, the python generator builds it fine there.

**Comment by cm-perrs** [comment]
Stumbled across this problem today using WSL.

FWIW this can be fixed in a WSL environment with `fsutil.exe file setCaseSensitiveInfo <path> enable`

**Comment by hkollmann** [comment]
generator is dead
