### ISSUE TITLE
Testrunner: qx.Promise tests interfere with other tests

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9474]
It's currently not clear how, but in current testrunner it seems that the tests in `qx.test.Promise` leave some change in testrunner behind which makes specific tests fail.

I'm currently only able to reliably reproduce this on safari by the following steps:

1. load the test runner in safari
2. run the `qx.test.Promise` tests by selecting them in the tree and hit "Run Tests" which all will succeed
3. run the `qx.test.bom.media.Audio."test Play Event"` test which will fail
You'll see the following message in the "Test Results" area or the log:
```
qx.test.bom.media.Audio:test Play Event
Error message is: 
: Expected '' but found 'oops'!
```
4. Search for the occurrence of the string 'oops' in the framework and you'll find it exclusively in `qx.test.Promise` in 5 locations.

The question is: how do the tests in `qx.test.Promise` leave changes behind in the testrunner which interfere somehow with other tests.

**Comment by level420** [comment]
Here the messages in the console:
```
2255953 qx.Promise: Unhandled promise rejection: (not from exception)
2255954 Assertion error! : Expected '' but found 'oops'! Stack trace: qx.core.AssertionError.constructor:51,qx.core.Assert.__fail:45,
qx.core.Assert.assertEquals:39,
qx.type.BaseString.assertEquals:34,
anonymous(),
anonymous(),
qx.event.GlobalError.handleError(),
qx.event.GlobalError.__onErrorWindow(),
anonymous()
```

**Comment by hkollmann** [comment]
Current test are working
