### ISSUE TITLE
add find() method to qx.data.Array

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9482]
`qx.data.Array` should mirror the native Array methods, but is lacking the find() method currently: 

- http://www.qooxdoo.org/current/api/#qx.data.Array
- https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find

The method should be added. There is a polyfill in the MDN docs which could be adapted. 

- [x] Add method
- [ ] Add tests

**Comment by level420** [comment]
We already have a polyfill in place for `Array`: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/lang/normalize/Array.js#L265
We only need to wrap it into a `qx.data.Array` method:
```javascript
    /**
     * Creates a new array with found items in the current array.
     * @param callback {Function} The mapping function, which will be executed for every
     *   item in the array. The function will have three arguments.
     *   <li><code>item</code>: the current item in the array</li>
     *   <li><code>index</code>: the index of the current item</li>
     *   <li><code>array</code>: The native array instance, NOT the data array instance.</li>
     * @param self {var?undefined} The context of the callback.
     * @return {qx.data.Array} A new array instance containing the found items.
     */
    inf: function(callback, obj) {
      return return new qx.data.Array(this.__array.find(callback, self));
    },
```
and of course write some tests.
