### ISSUE TITLE
qx.ui.form.List._applyOrientation leaks previous layout instance

### ISSUE THREAD

**Issue by gnikolaidis** [qooxdoo/qooxdoo#9488]
When changing the orientation of a list widget from horizontal to vertical or vice-versa:

https://github.com/qooxdoo/qooxdoo/blob/7fa76d1550a4186a6d8f3c54d50e961c34914bcb/framework/source/class/qx/ui/form/List.js#L272

the previous layout instance (qx.ui.layout.VBox or qx.ui.layout.HBox) is not disposed.

**Comment by level420** [comment]
@gnikolaidis yes, a explicit disposal should be better. I'l create a PR soon for this.

**Comment by level420** [comment]
@gnikolaidis could you please check if the fix is working for you? thank you!

**Comment by gnikolaidis** [comment]
@level420 your PR fixes the memory leak, thanks

**Comment by level420** [comment]
@gnikolaidis we have to wait with closing this issue until the PR gets merged.

**Comment by gnikolaidis** [comment]
@level420 Oops my bad... regarding GitHub code of conduct, I am but a caveman ;-)
