### ISSUE TITLE
Getting Started: not entirely clear what file(s) you need

### ISSUE THREAD

**Issue by motoom** [qooxdoo/qooxdoo#9489]
The 'Getting Started' link brings one to https://github.com/qooxdoo/qooxdoo/releases , but there one must make a choice between q-sdk-5.0.2.zip and qooxdoo-5.0.2-sdk.zip, and for someone who has never worked with qooxdoo it is not immediately clear which one to download (or both of them?). A description behind each file, or an explanation text would take away that decision hurdle.

**Comment by hkollmann** [comment]
Closed because we are in work to have npm package only
