### ISSUE TITLE
arguments.callee vs table model sorting functions

### ISSUE THREAD

**Issue by petitben** [qooxdoo/qooxdoo#9501]
Hi,

I see you make some more arguments.callee cleanup in the code what is a great initiative :-)

This message following the recent integration of #9499.
Was it mandatory to include the third parameter ?
Wouldn't it work by declaring named functions like this ? I know it leads to issues regarding memory management in IE8- but is there still anybody who cares about IE8- nowadays) ?

```
// old version
_defaultSortComparatorAscending : function(row1, row2)
    {
      var obj1 = row1[arguments.callee.columnIndex];
      var obj2 = row2[arguments.callee.columnIndex];
      if (qx.lang.Type.isNumber(obj1) && qx.lang.Type.isNumber(obj2)) {
        var result = isNaN(obj1) ? isNaN(obj2) ?  0 : 1 : isNaN(obj2) ? -1 : null;
        if (result != null) {
          return result;
        }
      }
      return (obj1 > obj2) ? 1 : ((obj1 == obj2) ? 0 : -1);
    },

// new version
_defaultSortComparatorAscending : function __ascSort(row1, row2)
    {
      var obj1 = row1[__ascSort.columnIndex];
      var obj2 = row2[__ascSort.columnIndex];
      if (qx.lang.Type.isNumber(obj1) && qx.lang.Type.isNumber(obj2)) {
        var result = isNaN(obj1) ? isNaN(obj2) ?  0 : 1 : isNaN(obj2) ? -1 : null;
        if (result != null) {
          return result;
        }
      }
      return (obj1 > obj2) ? 1 : ((obj1 == obj2) ? 0 : -1);
    },
```

**Comment by johnspackman** [comment]
I think that the issue is that the `ascSort.columnIndex` is an odd way of achieving it - it requires explanation for something that would be implicitly obvious if we instead used a `columnIndex` parameter.

Also, your "new version" example wouldn't quite work because there is no `__ascSort` variable in scope, you would have to specify the full classname, eg:

```
// new version
_defaultSortComparatorAscending : function __ascSort(row1, row2)
    {
      var obj1 = row1[mypackage.module.TableEditor.__ascSort.columnIndex];
      var obj2 = row2[mypackage.module.TableEditor.__ascSort.columnIndex];
```

There's nothing wrong with that longer version of `mypackage.module.TableEditor.__ascSort.columnIndex` but I would *much* prefer to write just `columnIndex`, IMHO it's more readable e.g.:

```
// proposed version
_defaultSortComparatorAscending : function __ascSort(row1, row2, columnIndex)
    {
      var obj1 = row1[columnIndex];
      var obj2 = row2[columnIndex];
```

**Comment by level420** [comment]
@petitben Interresting. I never thought about using named functions as members in qx classes.
Did you check if this works with generator and compiler?

My second question is: why is it so bad to have the third parameter in the sort function? We have to deal anyway with the column index in the sorting function as we need to get the sortable value out of the two rows to be compared? Having a clear interface via the third parameter is imho much better than using the "function attribute mechanism" which was used before.

**Comment by level420** [comment]
There is one alternative I've thought about before, put "feeled" much "heavier" than the current solution with the third parameter: We could bind the sort function via a closure to the model instance on sorting. See https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/table/model/Simple.js#L333-L335
we could modify this to 
```javascript
var model = this;
this.__sortColumnIndex = columnIndex;
this.__sortAscending = ascending;      
this._rowArr.sort(function(row1, row2) {
  return comparator.call(model, row1, row2, columnIndex);
});
```
This way we could retreive the current sort index in the soft function this way:
```javascript
_defaultSortComparatorAscending : function __ascSort(row1, row2)
{
  var columnIndex = this.getSortColumnIndex();
  var obj1 = row1[columnIndex];
  var obj2 = row2[columnIndex];
}
```

**Comment by petitben** [comment]
It think there is a misunderstanding. I never meant your solution was bad at all :-)
Using a named function simply avoid final users to refactor their code if they want to migrate.
Voilà. I see everybody already validated your pull request. So I guess it's OK.
