### ISSUE TITLE
Resize handler is overlapped

### ISSUE THREAD

**Issue by Adolfrizer** [qooxdoo/qooxdoo#9502]
When I increase a last table column for a table **without a vertical scrollbar** I can't make it smaller back because a resize handler is overlapped by this last column. You can see that in the demobrowser:
1) go to the http://www.qooxdoo.org/current/demobrowser/#table~Table.html page
2) click the "Remove 5 rows" button several times to remove the vertical scrollbar
3) try to resize the last column and release the mouse button over the "column button" ![image](https://user-images.githubusercontent.com/6869544/36971795-cbe2a46e-208e-11e8-978f-0e01ef126f49.png)
4) try to make this column smaller back

Result (modern theme):
![image](https://user-images.githubusercontent.com/6869544/36974106-48be2424-2097-11e8-81e2-a383ba6039b1.png)

**Comment by level420** [comment]
Confirmed.
The solution would be to not allow the resizer of the last column to move below the left edge of the column visibility button or to re-calculate the max size of the right column to not go behind the column visibility button.

**Comment by level420** [comment]
@Adolfrizer thank you for the bug report. As always we encourage the issue author to offer a pull request to solve the bug.

**Comment by hkollmann** [comment]
@level420 : Do you have an hint where to start? Where is calculating done?

**Comment by hkollmann** [comment]
closed with #9842
