### ISSUE TITLE
Tests: support for travis jwt ends on april 17th

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo#9508]
We're currently using [JWT](https://docs.travis-ci.com/user/jwt) for our tests in saucelabs. This was needed, because we do not want to expose credentials inside PR builds. Sadly there seem to be some concerns with it, so travis decided to shut it down.

Loosing JWT also shuts down our saucelabs tests, so we've to act somehow. I had no time to think/work on an alternative way of authenticating. Ideas are welcome.

**Comment by oetiker** [comment]
I have done some research and it seems that no one has yet come up with a good solution ... saucelabs does not say anything on their blog or otherwise ... 

so, for now, I guess we have to go back to our old solution ...

**Comment by cajus** [comment]
What about this approach:

 * disable automatic tests in travis
 * create a webhook in github which calls a simple service (which i.e. our company could host)
 * let the service trigger the travis build by completely providing the .travis.yml information via the travis API
 * let the service provide the credentials which get directly removed after setting up the tunnel
 * all this must happen before scripts in our .travis directory are executed

The service should keep a blacklist of files (i.e. .travis.*) when a travis build must not be triggered.

I know that this involves an additional service, but it's a realtive simple one. We already have the travis ci config, just the handling of secure env variables can be disabled, because we can control when to expose them.

**Comment by oetiker** [comment]
yes, an external service seems to be the only way around this ... taking the ability to mess with the test suit away ... is it possible to set up the saucelab link before any user code is run?

**Comment by level420** [comment]
Some reading about replacing jwt:
https://blog.algolia.com/travis-encrypted-variables-external-contributions/
https://www.bountysource.com/issues/54239718-jwt-deprecation-figure-out-how-to-test-on-sauce-labs-during-pr-checks

**Comment by level420** [comment]
@cajus seems like ampproject found a way to use saucelabs with something they call "temporary per-run token".
See https://github.com/ampproject/amphtml/pull/14034
Could you have a look? Thanky you!

**Comment by level420** [comment]
now after a long grace period it seems that travis really took jwt offline.

"He's dead Jim!"

**Comment by hkollmann** [comment]
Tests are working.
