### ISSUE TITLE
qx.module.util.Object.merge utilizes missing qxWeb function

### ISSUE THREAD

**Issue by sqville** [qooxdoo/qooxdoo#9528]
Receive an error on line 90 of qx.module.util.Object. Seems the line is trying to reference an object that does not exist within qxWeb. Replaced line (see below) and merge function seems to work as intended.

//var varargs = qxWeb.array.fromArguments(arguments);
var varargs = qx.module.util.Array.fromArguments(arguments);

**Comment by sqville** [comment]
Will do!

**Comment by sqville** [comment]
Tobi, where do i add a test class? I went through the project. I don't see a jump off point anywhere

**Comment by oetiker** [comment]
in general, tests go here: https://github.com/qooxdoo/qooxdoo/tree/master/framework/source/class/qx/test but I just realize that there don't seem to be any for qxWeb ...

**Comment by sqville** [comment]
Upon further analysis, it looks as if qx.module.util.Object is dependent upon qx.module.util.Array. Added @requires (qx.module.util.Array) to qx.module.util.Object, ran the generator and it works as needed

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9531
