### ISSUE TITLE
qx.ui.list.List PageUp/PageDown behave like Home/End

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9545]
**Description**
When using the "`PageUp`" rsp. "`PageDown`" keys at a virtual List, the selection jumps only between first and last item (as if having used the "`Home`" rsp. "`End`" key).
The expected behavior would be more like 5 to 10 items up or down.

**To Reproduce**
Just use the virtual list at the demobrowser(s):
- [Virtual List at "current"](http://www.qooxdoo.org/current/demobrowser/#virtual~List.html) (5.0.2)
- [Virtual List at "devel"](http://www.qooxdoo.org/devel/demobrowser/#virtual~List.html)

**Expected behavior**
The expected behavior would be more like 5 to 10 items up or down.
Or at least a similar stepping as the "non-virtual" List applies.
See for example [List](http://www.qooxdoo.org/5.0.2/demobrowser/#widget~List.html) and [ListController](http://www.qooxdoo.org/5.0.2/demobrowser/#data~ListController.html) demobrowser examples

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9837
