### ISSUE TITLE
Blocker does not block active/focused widget when blocker is attached to Composite

### ISSUE THREAD

**Issue by ronkie** [qooxdoo/qooxdoo#9551]
qx.ui.core.Blocker does not block active/focused widget when blocker is attached to qx.ui.container.Composite which contains that widget.

**To Reproduce**
1. Go to playground example: http://tinyurl.com/y862cwg7 
2. Type something into text field, then Press Enter. It will activate the Blocker which is attached to Composite that contains text field
3. See that you can still type into the widget, which is not correct. If now to click outside the text field to make it loose focus, it will get blocked as expected.

**Expected behavior**
Text field should get blocked immediately, so user cannot type anything into there anymore.

**Desktop:**
 - OS: Mac OSX, Windows 10
 - Tested in latest Chrome

**Comment by level420** [comment]
The blocker does not contain any code which causes the focus to be removed from the current widget (here the text field). If you first call `text.blur();` in your example it should work:

http://tinyurl.com/y862cwg7

**Comment by level420** [comment]
Or attach the blocker to root. this way all keyboard input is captured:

http://tinyurl.com/yc86a7zm

**Comment by hkollmann** [comment]
No PR received.
