### ISSUE TITLE
Table "Select All" code not being executed

### ISSUE THREAD

**Issue by patbuxton** [qooxdoo/qooxdoo#9552]
Code in qx.ui.table.Table to select all Rows of a table is not being executed. The code is in a keypress event for Ctrl-A. The event seems to be fired for pressing Control, but not for the key combination.

Code is here: https://github.com/qooxdoo/qooxdoo/blob/5bc4793fb106bcb817f07dc6b05c7072f2c181f0/framework/source/class/qx/ui/table/Table.js#L1435-L1456

**To Reproduce**
1. Go to http://www.qooxdoo.org/5.0.2/demobrowser/#table~Table.html
2. Focus Table, hit Ctrl-A
3. Contents are not selected

Expected behaviour:
   All rows of the table should be selected

This was on Linux or Windows, both using Chrome

I've implemented this myself in a descendant of table by creating a qx.ui.command.Command("Ctrl+A") and then basically executing the same selection code.

**Comment by level420** [comment]
This is fixed in current master. See:
http://www.qooxdoo.org/devel/demobrowser/#table~Table.html

**Comment by patbuxton** [comment]
Yep, it certainly is. Thanks
