### ISSUE TITLE
Setting a custom Column Width on a table makes rendering much slower

### ISSUE THREAD

**Issue by sambu16** [qooxdoo/qooxdoo#9556]
Calling setColumnWidth on a tableColumnModel makes the rendering of the table very slow. I have a table on a tabview and this the switch between tabs is taking ~6 seconds. If I remove the setting of the column width then performance is restored. I presume I can edit a default columnWidth somewhere which I'll look into, but setting it this way shouldn't cause such bad performance.

I created a playground version that's not as poor performance as my actual app, but does demonstrate the performance decrease when switching from Tab1 to Tab2 vs the performance of switching from Tab2 to Tab1.

http://tinyurl.com/y8m5djmq

**Comment by derrell** [comment]
The Table widget is notoriously bad about handling large numbers of columns. One major problem you're seeing here is that for **each column** width change, scroller widths and scroll bar visibility are being calculated: qx.ui.table.columnModel.Basic's `setColumnWidth` fires event `widthChanged` which invokes qx.ui.table.Table's `_onColWidthChanged` method, which updates scroller widths and scroll bar visibility. There is lots of room for deferred processing, that this widget doesn't do. It's one of the very old qooxdoo widgets, and although it's great for many things, it has severe limitations. You're hitting on one of them.

What I don't understand is why the rendering is slow upon subsequent tab changes. Those event listeners should only be called during table creation. There's more to this than meets the eye...

If all or most of your columns are the same size, you can change the default column width with
`qx.ui.table.columnmodel.Basic.DEFAULT_WIDTH = 120;`

**Comment by patbuxton** [comment]
Thanks for the tip, this'll work nicely because it is only to make the default bigger for a specific table so I'll set it, build the table and set it back again so I don't change the default anywhere else.

**Comment by cboulanger** [comment]
I don't think this is fixable without rewriting major parts of the Table, so I'll close that issue. Feel free to reopen if anyone has an idea to fix it (preferably with a accompanying PR).
