### ISSUE TITLE
Troubles with Qooxdoo Master and 5.0.2 on iOS

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9566]
There are some annoying effects with Qooxdoo 5.0.2 and 4.0.2 on todays iOS devices. It is hard to debug,

For example:
On every click-event (even on those using pure JavaScript) oder interactive element (input, select) the page jumps on top of the page.

I know Qooxdoo 4.0.2 is still very old. I hope there is maybe someone remembering having same issues in the past and could give m a advice how to solve.

Greetimgs.

**Comment by oetiker** [comment]
and qooxdoo-trunk ?

**Comment by stahl-riesa** [comment]
Yes. With Master too.

**Comment by stahl-riesa** [comment]
The links shows a minimalist demo. It is just a huge page with a span as button at the end. The span tag has got a click event handler.

[https://www.sunny-dessous.de/ios.html](https://www.sunny-dessous.de/ios.html)

If the built qxbasic-core.js-file is inlcuded, clicking the span-button the viewport scrolls / jumps at the top of the page.

The effect is reproducible on Safari and Firefox (Chrome I haven't testetd) on iOS. I'm using an iPad and iPhone 8 with iOS 11.4.1 for testing.

**Comment by level420** [comment]
@stahl-riesa the demo is password protected. could you please send the credentials?

**Comment by oetiker** [comment]
can you create a minimal example ?

**Comment by stahl-riesa** [comment]
@level420 The JavaScript file was included with a wrong path. I fixed it, so it should work now.

@oetiker I will try.

**Comment by stahl-riesa** [comment]
I think, there was an error at our internal building process. Cleaning up, trying, trying and tyring of included and excluded classes solved the issue. So I will close this report. Thank you for your help!
