### ISSUE TITLE
new `null` value feature in list controller does not work with modelSelection

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo#9569]
unfortunately the playground isn't up-to-date, so I can only provide some "pseudo"-code to describe the problem:

If you select an "non-null" item in the selectbox, the model selection changes. If you select the "null"-value again, the model selection does not change.

The problem is this line: https://github.com/qooxdoo/qooxdoo/blob/97418ba9a62fed5eb00efbbac5190fdde66ed24b/framework/source/class/qx/ui/form/MModelSelection.js#L77

because the "null" item has not model, and is not added to the modelSelection. Then you have `modelSelection.length = 0`and `data.length = 1` and nothing happens, although the model selection should be resetted.

@johnspackman Do you have any suggestion how to solve the problem.

The code above would show that there is no model selection change in case of re-selecting the "null"-item.

```
// Create a button
var model = new qx.data.Array();
model.push(qx.data.marshal.Json.createModel({name: 'Test 1', id: 1}))
model.push(qx.data.marshal.Json.createModel({name: 'Test 2', id: 2}))
var box = new qx.ui.form.SelectBox();
var controller = new qx.data.controller.List();
controller.set({
  allowNull: true,
  nullValueTitle: '-'
})

// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(box,
{
  left : 100,
  top  : 50
});

// Add an event listener
box.getModelSelection().addListener("change", function(e) {
  console.log('model selection changed:', e.getData())
});
```

**Comment by level420** [comment]
@peuter playground should be (nearly) up to date: http://www.qooxdoo.org/devel/playground/ based on this commit: https://github.com/qooxdoo/qooxdoo/commit/6606c75

It seems that the last merge did not push a new playground version, as it had a timeout in the firefox tests. I'm investigating and be back.

**Comment by johnspackman** [comment]
@peuter please can you try that PR in your code?  the file https://github.com/johnspackman/qooxdoo/blob/fix-list-controller-null-selection/uitests/selectbox/source/class/selectbox/Issue9569Application.js has your sample code from above

**Comment by peuter** [comment]
@johnspackman Your fix works for me.
