### ISSUE TITLE
Mobile: Snap for Native Scroll broken on Chrome

### ISSUE THREAD

**Issue by johannes-nivus** [qooxdoo/qooxdoo#9593]
Since no pointerup event is fired in Android Chrome snapping with "qx.mobile.nativescroll" : true is broken.
The _onTrackEnd handler in MNativeScroll.js isn't called.

Reproducable on:
https://www.qooxdoo.org/devel/mobileshowcase/index.html
Dialog Widgets --> Picker.

A quick and dirty fix is to delete the check for _onTrack in the _onScroll timeout. But this leads to "jumpy" behaviour when stopping the gesture without raising.

I don't have any idea how to fix it correctly, because there's no event that signals the raise of the finger.

With iScroll snapping is working but this has other issues I need to investigate (e.g. scrolling when pinch to zoom).

Regards, Johannes

**Comment by cboulanger** [comment]
@johannes-nivus Is this still an issue in the current Android Chrome version? If yes, Have you come up with a fix? PRs are always welcome!

**Comment by johannes-nivus** [comment]
Thanks for reminding me.
Please find attached a workaround, which could be transferred to a PR by someone with more insight.
The files need to be applied to:
qooxdoo-master\framework\source\class\qx\ui\mobile\container

Summary:
Use Native Snap where possible (Chrome and Safari)
Changed Snap boundaries to middle of previous element, because of Chrome snapping native to fractions of a pixel which leads to snapping to the wrong element.
Todo:
Improve the browser conditionals (Perhaps include Versions etc.).

[container.zip](https://github.com/qooxdoo/qooxdoo/files/3988510/container.zip)

**Comment by johannes-nivus** [comment]
@cboulanger 
Sorry, I forgot the css.

[container.zip](https://github.com/qooxdoo/qooxdoo/files/3988670/container.zip)

**Comment by cboulanger** [comment]
I encourage you to try and submit a PR via github. This will also record you as the one who fixed the bugs and will allow a proper testing and review of the bug fix. As we are trying to squash a huge number of bugs in the run-up to the new release, this is required to make sure your fix wil be considered with priority. Thank you!

**Comment by hkollmann** [comment]
Got no PR. Closed.
