### ISSUE TITLE
On widgets.destroy has the error: Error in de 'Dispose' queue

### ISSUE THREAD

**Issue by nwgroup** [qooxdoo/qooxdoo#9595]
When we destroy the widget appears the next bug:

011912 Error in the 'Dispose' queue:Error: The array field: __widgetChildren of object: qx.ui.container.Composite[594-0] has non disposable entries: Error: The array field: __widgetChildren of object: qx.ui.core.scroll.ScrollPane[615-0] has non disposable entries: Error: The array field: __widgetChildren of object: qx.ui.container.Composite[613-0] has non disposable entries: Error: The array field: __widgetChildren of object: qx.ui.container.Composite[2926-0] has non disposable entries: Error: The array field: __widgetChildren of object: qx.ui.container.Composite[2931-0] has non disposable entries: TypeError: Cannot read property 'getTracks' of null
window.console.error @ VM57592:37
qx.log.appender.Native.process() @ Native.js:59
qx.log.Logger.__log() @ Logger.js:462
qx.log.Logger.error() @ Logger.js:209
(anonymous) @ Manager.js:194
qx.ui.core.queue.Manager.__executeAndRescheduleOnError() @ Manager.js:224
qx.ui.core.queue.Manager.flush() @ Manager.js:184
(anonymous) @ Manager.js:69
clb @ AnimationFrame.js:184
requestAnimationFrame (async)
qx.bom.AnimationFrame.request() @ AnimationFrame.js:190
qx.ui.core.queue.Manager.scheduleFlush() @ Manager.js:64
qx.html.Element.prototype._scheduleChildrenUpdate() @ Element.js:480
qx.html.Element.prototype.__removeChildHelper() @ Element.js:935
qx.html.Element.prototype.remove() @ Element.js:1111
qx.ui.core.Widget.prototype.setLayoutParent() @ Widget.js:987
qx.core.Object.prototype.base() @ Object.js:139
qx.ui.window.Window.prototype.setLayoutParent() @ Window.js:439
qx.ui.core.Widget.prototype.__removeHelper() @ Widget.js:2150
qx.ui.core.Widget.prototype._remove() @ Widget.js:2002
qx.ui.core.Widget.prototype.destroy() @ Widget.js:3818
(anonymous) @ forms.js:1918
qx.event.dispatch.Direct.prototype.dispatchEvent() @ Direct.js:134
wrappedFunction @ Interface.js:538
qx.event.Manager.prototype.dispatchEvent() @ Manager.js:873
qx.event.Registration.fireEvent() @ Registration.js:304
qx.core.Object.prototype.fireEvent() @ MEvent.js:179
(anonymous) @ Timer.js:309
qx.event.Timer.prototype._oninterval() @ GlobalError.js:132
__oninterval @ Timer.js:61
setInterval (async)
qx.event.Timer.prototype._applyEnabled() @ Timer.js:222
qx.event.Timer.prototype.setEnabled() @ VM60379:3
qx.event.Timer.prototype.start() @ Timer.js:240
qxnw.forms.prototype.cleanAll() @ forms.js:1916
(anonymous) @ forms.js:118
qx.event.dispatch.Direct.prototype.dispatchEvent() @ Direct.js:134
wrappedFunction @ Interface.js:538
qx.event.Manager.prototype.dispatchEvent() @ Manager.js:873
qx.event.Registration.fireEvent() @ Registration.js:304
qx.core.Object.prototype.fireEvent() @ MEvent.js:179
qx.ui.window.Window.prototype.close() @ Window.js:634
qx.ui.window.Window.prototype._onCloseButtonTap() @ Window.js:1051
qx.event.dispatch.Direct.prototype.dispatchEvent() @ Direct.js:134
wrappedFunction @ Interface.js:538
qx.event.Manager.prototype.dispatchEvent() @ Manager.js:873
qx.event.Registration.fireEvent() @ Registration.js:304
qx.core.Object.prototype.fireEvent() @ MEvent.js:179
qx.ui.form.SplitButton.prototype.execute() @ MExecutable.js:111
wrappedFunction @ Interface.js:538
qx.ui.form.Button.prototype._onTap() @ Button.js:308
qx.ui.core.EventHandler.prototype._dispatchEvent() @ EventHandler.js:315
qx.event.dispatch.AbstractBubbling.prototype.dispatchEvent() @ AbstractBubbling.js:241
qx.event.Manager.prototype.dispatchEvent() @ Manager.js:873
qx.event.Registration.fireEvent() @ Registration.js:304
qx.event.handler.Gesture.prototype._fireEvent() @ Gesture.js:187
qx.event.handler.GestureCore.prototype.gestureFinish() @ GestureCore.js:317
qx.event.handler.GestureCore.prototype.checkAndFireGesture() @ GestureCore.js:152
qx.event.handler.Gesture.prototype.__callBase() @ Gesture.js:218
qx.event.handler.Gesture.prototype.checkAndFireGesture() @ Gesture.js:137
(anonymous) @ Function.js:337
qx.event.dispatch.Direct.prototype.dispatchEvent() @ Direct.js:134
wrappedFunction @ Interface.js:538
qx.event.Manager.prototype.dispatchEvent() @ Manager.js:873
qx.event.Registration.fireEvent() @ Registration.js:304
qx.event.handler.Pointer.prototype._fireEvent() @ Pointer.js:148
qx.event.handler.Pointer.prototype._onPointerEvent() @ Pointer.js:168
(anonymous) @ Function.js:337

The widget is this:

var css = {
                width: 280,
                height: 195
            };
            var arrbtRemote = {
                autoPlay: true,
                width: 280,
                muted: true
            };

            self.__video = new qx.html.Element("video", css, arrbtRemote);

![seleccion_035](https://user-images.githubusercontent.com/34222364/49301377-73ccbc00-f492-11e8-9895-9efe87a2508e.png)

**Comment by cboulanger** [comment]
@nwgroup Is this still occurring? And if yes, can you put together a playground example that will show the error? Even better, if you have fixed the error in your code in the meantime, can you provide a PR?

Thank you.

**Comment by hkollmann** [comment]
no answer
