### ISSUE TITLE
Regression with Drag&Drop

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#9598]
**Describe the bug**
When the drag target passes over a possible drop target enroute to a different drop target, and is dropped on the latter, the `drop` event is fired on the former instead of the latter as expected.

This regression was introduced with commit 4160586f5784633b377d6afb81cd11a7ac40ec67
@johnspackman This was your commit.

**To Reproduce**
In the following playground sample, drag the "Drag Me" label _over_ "First Window" then continue on to "Second Window". When you release the mouse while over "Second Window", the alert will tell you that the `drop` event was actually wrongly fired on "First Window". If, on the other hand, you drag the round-about way, around the windows so that the drag never passes over "First Window" and goes immediately to "Second Window" where it is dropped, the correct object receives the `drop` event.

http://tinyurl.com/y7k8a2zq

**Expected behavior**
A drop on "Second Window" would be expected to fire a `drop` event on 'Second Window", not on "First Window" as it is doing with the regression commit through master.

**Comment by reedspool** [comment]
Found the cause: https://github.com/qooxdoo/qooxdoo/blob/4160586f5784633b377d6afb81cd11a7ac40ec67/framework/source/class/qx/event/handler/DragDrop.js#L749

This returns after emitting an event. In the previous version, there was no return, and this.__dropTarget is subsequently updated. I think the solution is to just remove `return`.

**Comment by johnspackman** [comment]
I think this PR will fix your issue; thank you @reedspool, that bit of diagnostics work probably saved me a whole heap of work.

You were right in that the `return` was wrong because it meant the code was skipping essential stages, the final fix is slightly different in that it's necessary to chain the results together (the events system operates a kind of ultra lightweight promise system)
