### ISSUE TITLE
qx.core.Id: provide an event stream

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9606]
In order to be able to monitor which events are fired on objects that have an ID, `qx.event.Manager.dispatchEvent` should optionally provide for the possibility to forward the event, the id and the node to a central location; or provide some way to attach an observer. This will allow to record and playback user interaction for use in application testing.

**Comment by johnspackman** [comment]
fixed by https://github.com/johnspackman/qooxdoo/tree/fix-object-ids-2 (PR pending)

**Comment by cboulanger** [comment]
Implemented with https://github.com/qooxdoo/qooxdoo/pull/9607
