### ISSUE TITLE
Replace qx.event.Manager.{set|get}GlobalEventMonitor  with qx.event.Manager.{add|remove}GlobalEventListener

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9616]
Since https://github.com/qooxdoo/qooxdoo/commit/32f6bc032b469eab3b7cd0f03cea0f45be148f36, we have the ability to monitor all events that are dispatched centrally by setting a monitor function using `qx.event.Manager.setGlobalEventMonitor`. This is very useful, but it turns out that allowing only one monitor function is not optimal. Ideally, we want to register a number of monitor functions (i.e. listeners) from different parts of the code, which should not conflict with each other, and which should be individually removable, too. 

So the API should be changed from a setter/getter pattern to an add/remove pattern, where the add() function returns an id with which the listener can later be removed, such as:
```
qx.event.Manager.addGlobalEventListener(fn {Function}, context {Object}) =>  {Integer}
qx.event.Manager.removeGlobalEventListener(id {Integer})
```

**Comment by oetiker** [comment]
makes sense indeed

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9965
