### ISSUE TITLE
pointermove/mousemove events return wrong result in isLeftPressed()

### ISSUE THREAD

**Issue by fortooon** [qooxdoo/qooxdoo#9619]
Hi,
I found that pointermove/mousemove events in qoodoo layer use (or include) wrong mouse button info.
pointermove/mousemove events return wrong  result in method isLeftPressed()  in my browser, if I press left mouse button or not pointermove.isLeftPressed() -> false, pointermove.isLeftPressed() -> true always.  May be reason is that ```event._native.button``` include wrong button ID. Or may be I just don't understand something...

Please, help with workaround or patch  for qooxdoo event processing.

**To Reproduce**

just run simple example based on http://www.qooxdoo.org/current/demobrowser/#root~Application.html and see in console
```
qx.Class.define("demobrowser.demo.root.Application",
{
  extend : qx.application.Standalone,

  members :
  {
    main: function()
    {
      this.base(arguments);

      var container = new qx.ui.container.Composite(new qx.ui.layout.HBox());
      container.setDecorator("main");
      container.addListener("pointermove", this.__onPointerMove, this);
      container.addListener("mousemove", this.__onPointerMove, this);

      this.getRoot().add(container, {edge:0});
    },
    __onPointerMove : function(event) {
      var t1 = new Date();
      console.log("Time:", t1.getTime());     
      console.log("Check event info", event.isLeftPressed(), event.getType(), event.getButton());
    }
  }
});
```

**Desktop :**
 - OS: Ubuntu
 - Browser chromium
 - Version 71.0.3578.98

qooxdoo version : 5.0.2

**Comment by level420** [comment]
bug confirmed on firefox 65 windows 10.
playground sample http://tinyurl.com/yykfr9oy

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9828
