### ISSUE TITLE
Resizing a table column while any cell is being edited, resizes the editor even when in a different column.

### ISSUE THREAD

**Issue by lucapivato** [qooxdoo/qooxdoo#9620]
**Describe the bug**
Resizing any column while editing a cell, resizes the editor regardless of which column it belongs to.

**To Reproduce**
1. Go to http://www.qooxdoo.org/current/demobrowser/#table~Table_Cell_Editor.html
2. Start edit mode in column 2
3. Resize column 1
4. The editor shrinks when it shouldn't.

**Expected behavior**
The editor should resize only when the column it belongs to is resized.

**Screenshots**

![image](https://user-images.githubusercontent.com/37640802/51945225-13072480-23ec-11e9-88ea-261c5a5ec5f7.png)

After resizing column 1

![image](https://user-images.githubusercontent.com/37640802/51945231-1bf7f600-23ec-11e9-853c-105bb29aeb56.png)

** Fix **

The fix is in qx.ui.table.pane.Scroller._stopResizeHeader()

Move this.__resizeColumn to the end and change the check to this:

// handle edit cell if available and if it's in the column being resized.
if (this.isEditing() && this.__focusIndicator.getColumn() === this.__resizeColumn) {

I can do a pull request, but I'm not sure the version I have forked on my account is up to date. We fixed in our wisej build, but I wanted to report here since it seems to be an old bug.

One more small issue, it seems better to use this

        var size = this.__focusIndicator.getInnerSize();
        this._cellEditor.setUserBounds(0, 0, size.width, size.height);

Instead of

	var height = this._cellEditor.getBounds().height;
	this._cellEditor.setUserBounds(0, 0, this.__lastResizeWidth, height);

Because the focus indicator may have a border and __lastResizeWidht would resize the editor a a bit outside of the focus indicator.

Thanks.

**Comment by lucapivato** [comment]
Yep, will fork again to be up to date. But looking more into this it seems that a better fix is to set the focusIndicator's layout to Grow and remove the forced resizing of the cell editor which is what causes the bug. Will test some more and do the PR later.

**Comment by level420** [comment]
Fixed via #9621
