### ISSUE TITLE
Bug in MEvent.addListenerOnce() for multiple times call with same args

### ISSUE THREAD

**Issue by fortooon** [qooxdoo/qooxdoo#9627]
Hi,
I found that MEvent.addListenerOnce() has the bug. If I set same handler to one object to process same event multiple times, in result after fire current event only first handler will be removed, others will be a live forever.  Reason is that `type + this.$$hash` key in  `listener.$$wrapped_callback[type + this.$$hash] = callback;` is not unique in such case.

Probably,  there is needed `__lastUnique` helper variable to generate wright key like in  qx.event.Manager.js

**To Reproduce**
You can run simple example based on http://www.qooxdoo.org/current/demobrowser/#widget~Button.html and see in browser console
```
qx.Class.define("demobrowser.demo.widget.Button",
{
  extend : qx.application.Standalone,

  members :
  {
    main: function()
    {
      this.base(arguments);

      var box = new qx.ui.layout.HBox();
      box.setSpacing(10);

      var container = new qx.ui.container.Composite(box);
      container.setPadding(20);
      this.getRoot().add(container, {left:0,top:0});

      this.addNormalButtons(container);
      
    },

    addNormalButtons : function(container)
    {
      var btn1 = new qx.ui.form.Button("Button A", "icon/22/apps/media-video-player.png");
      container.add(btn1);
      btn1.addListenerOnce("execute", this.onExecute, this);
      // second handler will be a live forever
      btn1.addListenerOnce("execute", this.onExecute, this);
    },    

    onExecute : function()
    { 
      var t1 = new Date();
      console.log("onExecute", t1.getTime());      
    }
  }
});
```

**Expected behavior**
On second button click `console.log` (`onExecute`) must not be called. But on this example in browser console we can see that every other click ob button will be handled.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chromium
 - Version 71.0.3578.98

qooxdoo version : 5.0.2

**Comment by level420** [comment]
@fortooon Thank you for reporting this issue. It would be great if you could offer a PR to solve the issue.

**Comment by fortooon** [comment]
@level420  please, check

**Comment by hkollmann** [comment]
@fortooon :Is this still an issue in the current master?

**Comment by hkollmann** [comment]
Just did a test: It is.

**Comment by hkollmann** [comment]
@fortooon : You have an branch wich will fix this. Could please create an PR for qooxdoo/qooxdoo? You created a PR request for fortooon/qooxdoo in February....

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9843
