### ISSUE TITLE
IListDelegate sorter() doesn't work anymore on chrome

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9635]
Hi,

The `sorter` function on a `IListDelegate` interface doesn't work anymore on recent version of chrome.

Check here : http://tinyurl.com/y6hyjrp2 the list is not sorted on last version of Chrome (72)

It still works on up-to-date Firefox and older versions of Chrome

**Comment by hkollmann** [comment]
Edge is'nt working either!

**Comment by woprandi** [comment]
After some investigation it's not a bug. The sorter function is supposed to return a integer (-1, 0 or 1) and not a boolean (despite it worked before). Chrome has changed it's sort algorithm since v70 and i's probably a side-effect
https://www.reddit.com/r/javascript/comments/9sb87m/chrome_70_and_nodejs_11_no_longer_sort_arrays/
