### ISSUE TITLE
Desktop Tutorial broken links

### ISSUE THREAD

**Issue by TechplexEngineer** [qooxdoo/qooxdoo#9637]
**Describe the bug**
In the [desktop tutorial part 3](http://www.qooxdoo.org/current/pages/desktop/tutorials/tutorial-part-3.html) the identi.ca service mock url does not work: http://demo.qooxdoo.org/5.0.2/tweets_step4.5/resource/tweets/service.js

Also note link to status.net is confusing. http://status.net/wiki/Twitter-compatible_API#Timeline_resources

More explanation that identi.ca is not actually used would be nice.

**Comment by TechplexEngineer** [comment]
More clairification:

The link with version 5.0.2 does not work:
http://demo.qooxdoo.org/5.0.2/tweets_step4.5/resource/tweets/service.js

I found that changing the version to 3.0.2 actually worked. I'm guessing when the 5.0.2 release was cut the assets weren't all published:

http://demo.qooxdoo.org/3.0.2/tweets_step4.5/resource/tweets/service.js

**Comment by oetiker** [comment]
resolved in the new documenttion
