### ISSUE TITLE
Since Firefox 66, event.getKeyIdentifier() returns wrong identifiers for some keys

### ISSUE THREAD

**Issue by ronkie** [qooxdoo/qooxdoo#9643]
Firefox 66 has changed keyCode and charCode of the keypress event. For more info see:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66

Because of that, letters from p to z result in incorrect key identifiers. For example, "r" results in "F3".
It can lead to problems when developers rely on getKeyIdentifier() method of qx.event.type.KeySequence event.

1. Go to qooxdoo playground (make sure to have Firefox 66):
http://www.qooxdoo.org/current/playground/
2. Try to change some code by typing 'v'
3. See that no v symbol is typed and console opens instead.

Expected behavior:
Character 'v' is typed.

Browser:
Firefox 66.

**Comment by gnikolaidis** [comment]
Thank you! 97b3ea6 applied cleanly on Qooxdoo 5.0.2 and solved our many problems with users reporting that they are unable to type in 'R' on their new Firefox 66.

**Comment by hkollmann** [comment]
Done  with #9644
