### ISSUE TITLE
Regression with images in Table

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#9646]
Reference commit 0937f6c9ef8bf14ca05a9f778001b8d9290b0804: Add support for hi-res images to AbstractImage cellrenderer (#9625)

The ![correct](https://drive.google.com/open?id=1A3NC6MtZMtFJQfdGcEyieUqnSV5nqEhY)  behavior and ![new, incorrect](https://drive.google.com/open?id=1adcEg-eukkP-6xAisAQl3Ni05Y5vqEZ1) can be seen in these two images. The incorrect behavior was introduced with the above commit.

**Comment by derrell** [comment]
Correct
![correct](https://user-images.githubusercontent.com/361247/54917006-37095280-4ed1-11e9-85f9-6f2028e90874.jpg)

New, incorrect
![new, incorrect](https://user-images.githubusercontent.com/361247/54917005-37095280-4ed1-11e9-95d4-289542e51b59.jpg)

**Comment by derrell** [comment]
@jpriebe Would you please have a look?

**Comment by derrell** [comment]
The difference in HTML of the two images is that the incorrect one has `background-size: 11px, 11px`, and in fact, removing that attribute using Chrome Developer Tools properly corrects the image.

Correct image:
```html
<div style="width:11px;height:11px;display:inline-block;vertical-align:top;position:static;-webkit-user-drag:none;background-position:0 0;background-image:url(resource/mutualink/decoration/checkbox/checked-orig.png);background-repeat:no-repeat;"></div>
```

Incorrect image:
```html
<div style="width:11px;height:11px;background-size:11px, 11px;display:inline-block;vertical-align:top;position:static;-webkit-user-drag:none;background-position:0 0;background-image:url(resource/mutualink/decoration/checkbox/checked-orig.png);background-repeat:no-repeat;"></div>
```

**Comment by hkollmann** [comment]
Could you try to remove the , in background-size? That's wrong:

**Comment by jpriebe** [comment]
@hkollmann, you're right, the comma is not correct.  But even with that, I get proper behavior on my system.

@derrell - are you sure that the second image is incorrect?  The checkmarks look properly sized in that image; they're just blurry.  But that was exactly the problem I was trying to fix.  In my current qooxdoo app, if I remove my @2x images from the app, I get properly-sized, blurry images.

I'll post examples in a second...

**Comment by jpriebe** [comment]
Also, @oetiker - apparently, you can use `backgroundSize` instead of `"background-size"`, and it still works.  I guess somewhere in the internals of `Decoration`, camel case is converted to kebab case.  For consistency, I guess it should be `backgroundSize`.

**Comment by oetiker** [comment]
@jpriebe browser behavior when facing incorrect syntax may not be consistent ...

**Comment by derrell** [comment]
Removing the comma does not solve the blurry image problem.

The crisp images are the correct ones and as it's been for ages. The blurry images appear with the new code.

**Comment by jpriebe** [comment]
Definitely true.  At this point, the only incorrect syntax is the comma that shouldn't be there.  I've seen no problems with the comma on these platforms: Chrome (Windows and Mac OS), Firefox (Windows and Mac OS), and Safari (Mac OS).

We can remove the comma to correct the CSS syntax.  We can change kebab case to camel case for code aesthetics.  But I don't expect to see a behavioral change with table images.

So I'm trying to better understand what @derrell is seeing.

@derrell, what is the size of the blue checkbox image in your example?  Do you have a high-resolution version of the image?

**Comment by derrell** [comment]
The images, in this case, are 6x6px. qooxdoo is rendering them, according to the above HTML, in an 11x11 area, but they shouldn't be stretched if not explicitly requested.

**Comment by derrell** [comment]
High-resolution 6x6 image? :-) 

![checked-orig](https://user-images.githubusercontent.com/361247/54931215-f7e9fa00-4eee-11e9-9d06-feccf63c0102.png)

**Comment by jpriebe** [comment]
The 11 pixel dimension comes from `this.__imageData.width`.  So that ultimately comes from the ResourceManager, right?  Why does the ResourceManager think your image is 11x11 ?

**Comment by derrell** [comment]
$ identify /tmp/checked-orig.png 
/tmp/checked-orig.png PNG 6x6 6x6+0+0 8-bit sRGB 5.46KB 0.000u 0:00.000
$

**Comment by jpriebe** [comment]
That mismatch between the actual image size and ResourceManager's version of the size is also causing the image to not be centered in your "correct" version (since it's in the upper-left-hand corner of an 11x11 box).  The image is slightly to the left of center within the table cell.

**Comment by derrell** [comment]
It's a good question why the wrong data is being returned. The generated script file has, in qx.resources, 
```
"mutualink/decoration/checkbox/checked-orig.png":[6,6,"png","mutualink"]
```
so the size is correct there...

**Comment by jpriebe** [comment]
Maybe you're using a Boolean cell renderer?  It hard-codes images to 11px width and height.

**Comment by derrell** [comment]
Yes, I am using a Boolean cell renderer.

**Comment by jpriebe** [comment]
Seems like the best option is to provide an 11x11 image to go with the boolean cell renderer (and a 22x22 @2x version at the very least).

**Comment by derrell** [comment]
Yes, we could certainly do that in this particular case. That only solves the problem in this one case, though. The box in which an image is rendered,, and the actual image size, are unrelated. No stretching should be done if one doesn't request that it be stretched; rather (and for backward-compatibility), I think we should find a solution that doesn't alter the long-time behavior...

**Comment by jpriebe** [comment]
But in effect, isn't the subclass requesting that the image be stretched?  It is explicitly setting the width and height to 11.

I'm trying to think of use cases where you would want to have a table cell with a larger image element but a smaller image within that area.  But I can't think of a good reason to do that.  The image would not be centered horizontally or vertically within the tablecell.

If you want a tiny checkbox, you can pad it with transparent pixels in an image editor.

I don't mean to argue with you -- I think it's good to consider backward compatibility to avoid breaking changes.  I just want to make sure that the support for `background-size` stays in the code in one form or another so that I can use high-resolution images in my qooxdoo tables.  It has to be present on the `div` in order for the @2x image to not show up gigantic and blurry.

**Comment by oetiker** [comment]
the problem with the table classes is that they are pretty old ... but hardcoding any sizes anywhere can certainly NOT be a good thing ... what happens when the boolean cell renderer is fixed to respect the size of the resource?

**Comment by derrell** [comment]
Yes, I've been looking at that. The size is available in ResourceManager; the BooleanCellRenderer doesn't use that; it just uses the AliasManager. I need to figure out the best way of correlating the two. Mostly, I need to figure out where the ID comes from in Resource manager, which isn't used on the Alias side.
