### ISSUE TITLE
Firefox: Debug console shown unexpectedly

### ISSUE THREAD

**Issue by benzen** [qooxdoo/qooxdoo#9655]
**Describe the bug**
A debug console is shown unexpectedly. 

**To Reproduce**
Use my app
1-either focused in a field, or not
2-press the lower case v

**Expected behavior**
If focused on a field write the letter v, otherwhise nothing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos and windows
 - Browser firefox 
 - Version 66. 

**Additional context**
Firefox 65 didn't raise this issue

**Comment by benzen** [comment]
![Capture d’écran, le 2019-03-28 à 15 58 51](https://user-images.githubusercontent.com/139909/55188967-0ba59280-5173-11e9-80c1-67e4a210dd10.png)
Here is a print screen of this.


Of course i never intended to show this console.
And in chrome i don't have this problem

**Comment by cboulanger** [comment]
Can you please try this:
https://github.com/qooxdoo/qooxdoo/releases/tag/v5.0.3-beta
and see if it fixes your problems? Thank you.

**Comment by benzen** [comment]
Is it possible to make a release into maven central for this ?

**Comment by cboulanger** [comment]
I am afraid you'll have to manually download the ZIP from the tag and replace your qooxdoo installation with it. We do not have maven integration at this point.

**Comment by benzen** [comment]
I confirm this fix my issue.

When is planned the official release ?

**Comment by cboulanger** [comment]
If no issues are reported with the beta, we can release it soon. Unfortunately, the extensive qooxdoo test suite is no longer compatible with v5 so we cannot test these releases ourselves. 

BTW if Maven is important to you, we have a very old repository which is about Maven integration: https://github.com/qooxdoo/maven-central-integration but I know nothing about it or about how much effort it would be to resuscitate it. Maybe you want to have a look?

**Comment by Holdwyn** [comment]
Seems that the keypress event is not fired anymore for non printable keys.

**Comment by cboulanger** [comment]
@Holdwyn Have you tried https://github.com/qooxdoo/qooxdoo/releases/tag/v5.0.3-beta

**Comment by Holdwyn** [comment]
Yes, sorry forgot to mentioned that I alredy tried 5.0.3-beta. We prevent the browser reload by "F5" keypress event. This isn't working anymore with the hotfix version and FF 66. Navigating in tables by arrow keys is also broken.

**Comment by benzen** [comment]
Since there is no that much activity arround qooxdoo.
I suppose il will be pretty hard to have report of issues on this new release.

Is the effort to update the extensive test suite that much of a problem ?

**Comment by cboulanger** [comment]
@benzen The activity is in the v6 branch, which is almost 100% backwards-compatible with v5 and in use in several production systems. Do not fear the "-alpha.*" version, it just indicates that it is still changing - but only concerning new features. You likely will run into a few small issues during migration but overall the upgrade will be worth it since you'll get all bugfixes and full browser compatibility.

**Comment by Holdwyn** [comment]
Could you point me to the v6 branch? I'm unable to find it in the branches list...

**Comment by derrell** [comment]
@Holdwyn It's the master branch.

**Comment by cboulanger** [comment]
Yes sorry if I was unclear. All development is in the master branch, which is considered safe for general consumption. It is advisable not to update each time a new commit lands since there might be regressions (that's why it is "alpha"). But as I said, the master branch is used in real projects and it is thoroughly tested in a really extensive test suite that runs for more than 2 hours: https://travis-ci.org/qooxdoo/qooxdoo/builds/511008181. We still don't have a release schedule for v6 because it involves much more than just the code (documentation, website, etc.), but it is on the horizon.

**Comment by level420** [comment]
> Yes, sorry forgot to mentioned that I alredy tried 5.0.3-beta. We prevent the browser reload by "F5" keypress event. This isn't working anymore with the hotfix version and FF 66. Navigating in tables by arrow keys is also broken.

@Holdwyn just tested the tables navigation with 5.0.3-beta and firefox 66.0.2 (64-Bit) on windows and it works as expected. Could you please share your browser version and os and how you tested? Thank you.

**Comment by Holdwyn** [comment]
> > Yes, sorry forgot to mentioned that I alredy tried 5.0.3-beta. We prevent the browser reload by "F5" keypress event. This isn't working anymore with the hotfix version and FF 66. Navigating in tables by arrow keys is also broken.
> 
> @Holdwyn just tested the tables navigation with 5.0.3-beta and firefox 66.0.2 (64-Bit) on windows 7 and windows 10 and it works as expected. Could you please share your browser version and os and how you tested? Thank you.

I downloaded the sources zip file (https://github.com/qooxdoo/qooxdoo/releases) and replaced the qooxdoo 5.0.2 checkout from git with it. Then I called generate clean and generate source. If I focus a table cell and try to use the arrow keys to move the focus it didn't work with FF 66.0.2 (64-Bit) on Windows 10 Version 1809.

**Comment by benzen** [comment]
So my initial problem seems to be solved, but @Holdwyn  seems to still see an issue with 5.0.3.

Can we have a feedback on this ?

**Comment by level420** [comment]
@benzen could you please check if table cell navigation with arrow keys works for you? thank you!

**Comment by hkollmann** [comment]
Checked. Working.
