### ISSUE TITLE
Move NPM packages to scoped names, remove separate server package

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9663]
Before release of v6, we should move the NPM packages to[ scope names](https://docs.npmjs.com/about-scopes):

 - `@qooxdoo/framework` replaces `qooxdoo-sdk` (the current "framework") and `qooxdoo` (the server package with a misleading name) and then contains all of the classes that can be compiled
 - `@qoxdoo/compiler` replaces `qxcompiler`

Reasons for not shipping a separate "qx.Server" package:
 -  it is conceptually easier to deal with a single distribution and reduces maintenance effort
 - even though most of the framework folder cannot be used on the server, there might be more blurring of the server-client boundary in the future
 - the size of `node_modules` does not really matter anymore these days

**Comment by hkollmann** [comment]
We had this discussion before: https://github.com/qooxdoo/qooxdoo/issues/9471
We should close #9471

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9671
