### ISSUE TITLE
qx compiler Error

### ISSUE THREAD

**Issue by Level0r0s** [qooxdoo/qooxdoo#9664]
**Describe the bug**
qx compiler in driver other than c: \

d:\qxdemo>qx compile
Error: Error: Empty Manifest.json in library at /Users/pccristiano/AppData/Roaming/npm/node_modules/qxcompiler/node_modules/qooxdoo-sdk/framework
at qx.tool.compiler.files.Utils.correctCase.then.then.then.data (C:\Users\pccristiano\AppData\Roaming\npm\node_modules\qxcompiler\lib\qx\tool\compiler\app\Library.js:149:19)
at <anonymous>

**To Reproduce**
1. c:\npm install -g qxcompiler 
2. d:\mkdir qxdemo
3. d:\cd qxdemo
4. d:\qxdemo\qx create qxdemo --out . --type desktop --noninteractive
5. d:\qxdemo\qx compile	

d:\qxdemo>qx compile
Error: Error: Empty Manifest.json in library at /Users/pccristiano/AppData/Roaming/npm/node_modules/qxcompiler/node_modules/qooxdoo-sdk/framework
at qx.tool.compiler.files.Utils.correctCase.then.then.then.data (C:\Users\pccristiano\AppData\Roaming\npm\node_modules\qxcompiler\lib\qx\tool\compiler\app\Library.js:149:19)
at <anonymous>

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by cboulanger** [comment]
@hkollmann Can you confirm the bug? I don't work on windows...

**Comment by hkollmann** [comment]
Yes i can - but it's a Problem of the Compiler...

**Comment by hkollmann** [comment]
It's a compiler issue - not qooxdoo. Therefore i created https://github.com/qooxdoo/qooxdoo-compiler/issues/371
