### ISSUE TITLE
handle async test functions

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo#9669]
**Is your feature request related to a problem? Please describe.**
When creating an async function in a test, the test is immediately successful.

**Describe the solution you'd like**
The test system should recognize and handle async tests.

**Describe alternatives you've considered**
Not writing async tests ... 

The qooxdoo test system works by looking for exceptions ... it does not curently care for the return values of tests ... but async methods return a promise ... so the test system would have to look out for that and then `catch` the exceptions raised by the promise.

**Comment by hkollmann** [comment]
It's working now

**Comment by cboulanger** [comment]
Thanks so much for your work on this, guys! So important!
