### ISSUE TITLE
Theming doesn't support background images with spaces in their names

### ISSUE THREAD

**Issue by mrfeet** [qooxdoo/qooxdoo#9674]
*When creating a custom theme and referencing background images with a space in their name, these images are not shown.

The problem is in qx.bom.element.Background.js, that doesn't take spaces in image urls into account:

var backgroundImageCssString;
if (this.__isBase64EncodedImage(backgroundImageUrl)) {
backgroundImageCssString = "url('" + backgroundImageUrl + "')";
} else {
backgroundImageCssString = "url(" + backgroundImageUrl + ")";
}

So only for base64 urls the url is quoted. But this quoting also needs to be done when the url contains a space.

So my suggestion is to remove the check for base64encoding and always include the quotes.

I will supply a pull request for this.

**Comment by hkollmann** [comment]
Done with #9675
