### ISSUE TITLE
Remove all labels containing "contrib"

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9684]
See https://github.com/qooxdoo/qooxdoo/labels?utf8=%E2%9C%93&q=contrib

We should close any open issues that have these labels and delete them afterwards.

I assume we need only one label "package system" or "packages" which concerns the infrastructure. We shouldn't have labels with specific package names since they all have their dedicated repo.

**Comment by hkollmann** [comment]
+1

**Comment by hkollmann** [comment]
Done
