### ISSUE TITLE
this.tr('') results in "Project-Id-Version: 1.0↵Report-Msgid-Bugs-To: you@…n; charset=utf-8↵Content-Trans..."

### ISSUE THREAD

**Issue by maettu** [qooxdoo/qooxdoo#9693]
**Describe the bug**
`this.tr('')` results in "Project-Id-Version: 1.0↵Report-Msgid-Bugs-To: you@…n; charset=utf-8↵Content-Transfer-Encoding: 8bit"

**To Reproduce**
1. Go to http://www.qooxdoo.org/qxl.playground/#%7B%22code%22%3A%22%252F%252F%2520Create%2520a%2520button%250Avar%2520button1%2520%253D%2520new%2520qx.ui.form.Button(this.tr('')%252C%2520%2522icon%252F22%252Fapps%252Finternet-web-browser.png%2522)%253B%250Aconsole.log(this.tr(''))%253B%250A%250A%252F%252F%2520Document%2520is%2520the%2520application%2520root%250Avar%2520doc%2520%253D%2520this.getRoot()%253B%250A%250A%252F%252F%2520Add%2520button%2520to%2520document%2520at%2520fixed%2520coordinates%250Adoc.add(button1%252C%250A%257B%250A%2520%2520left%2520%253A%2520100%252C%250A%2520%2520top%2520%2520%253A%252050%250A%257D)%253B%250A%250A%252F%252F%2520Add%2520an%2520event%2520listener%250Abutton1.addListener(%2522execute%2522%252C%2520function(e)%2520%257B%250A%2520%2520alert(this.tr(%2522Hello%2520World!%2522))%253B%250A%257D)%253B%22%2C%20%22mode%22%3A%22ria%22%7D
2. Look at javascript console or the formerly "hello world" button on the right side.

**Expected behavior**
`this.tr('')` should imo result in `''`

**Screenshots**
![Screenshot_2019-06-11_09-58-33](https://user-images.githubusercontent.com/167811/59253919-85580300-8c2f-11e9-80b4-9ccb7ce488f7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by hkollmann** [comment]
@maettu : This seems to be a bug in playground. Please could you move the report to https://github.com/qooxdoo/qxl.playground? 
Thanks!

**Comment by rommni** [comment]
Hum... Strange can't reproduce on chrome 74.0.3729.169 (Build officiel) (64 bits)  
![test_qx_tr](https://user-images.githubusercontent.com/907396/59254923-68bcca80-8c31-11e9-809c-8fdbe3508bf4.PNG)

**Comment by hkollmann** [comment]
We have now seperated repositories for each application and mentain them seperatly.

**Comment by oetiker** [comment]
@hkollmann we have not found it in playground ... but in your production app

**Comment by hkollmann** [comment]
Could it be a Problem of the compiler?

**Comment by oetiker** [comment]
yes, that would be my guess ... that it associates the header of the .po file with the empty string ...

**Comment by hkollmann** [comment]
Then we should move the issue to @qooxdoo/compiler...

**Comment by oetiker** [comment]
Issue moved to [qooxdoo/qooxdoo-compiler #442](https://github.com/qooxdoo/qooxdoo-compiler/issues/442) via [**ZenHub**](https://www.zenhub.com/)
