### ISSUE TITLE
Improve pullapprove algorithm

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9699]
We now have a working review system based on the PullApprove GitHub app. 

See https://github.com/qooxdoo/qooxdoo/blob/master/.pullapprove.yml

It still needs to be optimized for our most common use cases. Here are some suggestions:

1. [The lower threshold for documentation PRs](https://github.com/qooxdoo/qooxdoo/blob/master/.pullapprove.yml#L6-L16) should not apply only for markdown files in the `docs`  folder, but for any file in that folder. This should probably be updated [here ](https://github.com/qooxdoo/qooxdoo/blob/master/.travis/check-if-docs-only), too.
2. Is there more information for first-time-committers that should be put into the [welcome notification](https://github.com/qooxdoo/qooxdoo/blob/master/.pullapprove.yml#L56-L65)?
3. Currently, authors can merge their own PRs if the quorum is reached. Thinking about it, why not?

More ideas?

**Comment by cboulanger** [comment]
Update:
1. Implemented with https://github.com/qooxdoo/qooxdoo/pull/9700/commits/6218a73fcef674397a57b08882263bac108b6c41
2. Pending - thoughts?
3. No objection so far.

**Comment by hkollmann** [comment]
IMHO can be closed

**Comment by cboulanger** [comment]
Ok, closing.
