### ISSUE TITLE
Let documentation run locally

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9705]
The [Docsify-Startpage which we use to serve the MarkDown documentation](https://github.com/qooxdoo/qooxdoo/blob/master/docs/index.html) loads may scripts and resources from CDN servers. This means that it won't work offline. This is not ideal. We should cache the resources locally and ship them with the framework so that the documentation can be browsed independent of network access.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo/pull/9710
