### ISSUE TITLE
Conflicting property method qx.ui.splitpane.Splitter.isVisible with qx.ui.core.Widget

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9719]
The "fix" for #9649  introduced a (runtime-)warning, as it is "overriding" a generated property metghod:
`008327 Conflicting property method qx.ui.splitpane.Splitter.isVisible with qx.ui.core.Widget`

**To Reproduce**
Just run an app (source build) which has a Splitter.

**Expected behavior**
No warnings / errors whatsoever.

**Comment by hkollmann** [comment]
@johnspackman : Why do you closed this?

**Comment by johnspackman** [comment]
Because it was solved by the PR https://github.com/qooxdoo/qooxdoo/pull/9649 which was just merged

**Comment by johnspackman** [comment]
oh hang on, no it's not!!

**Comment by hkollmann** [comment]
It's another issue...

**Comment by schnepe2** [comment]
Should I change the title so it doesn't contain the responsible PR?
(this is what triggered @johnspackman, right?)

**Comment by schnepe2** [comment]
BTW: Last time such an issue came up (#9313), renaming of the method was proposed!
`showKnob` might be an alternative name for it.

**Comment by schnepe2** [comment]
Took a look at the things PR #9649 introduced and I am not sure what to think of it.

1. The documentation of `qx.ui.splitpane.Splitter#visible` property is plain wrong, as it only applies the visibility of the Splitters **knob**!
2. The changes in `qx.ui.splitpane.Pane` seem also to just work with **one** special case
(Try a theme with a different sized knob and you'll probably see things go crazy).
3. Shouldn't all the public properties, members and methods of Splitter (`getChildControl("knob"),` `setVisibility("visible")`, `setVisibility("excluded")`, `getVisibility()`, etc. pp.) be enough for any application programmer to derive a class from it? This request looks like a very special use-case to me.


For the "quick fix" a rename of property `qx.ui.splitpane.Splitter#visible` into `qx.ui.splitpane.Splitter#knobVisible` might be enough, but still I feel like the whole idea has to be tested a lot more...

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo/pull/9951
