### ISSUE TITLE
VBox and HBox ignore  maxHeight and maxWidth with the height percentage layout property.

### ISSUE THREAD

**Issue by lucapivato** [qooxdoo/qooxdoo#9743]
VBox and HBox ignoremaxHeight and maxWidth with the height percentage layout property.

**Expected behavior**
Min and Max constraints should be applied also with the height/width percentages according to the documentation: http://www.qooxdoo.org/current/api/#qx.ui.layout.VBox

To reproduce:

https://bit.ly/30EfPAj

I will fix in our variant of qooxdoo and put a PR. I just wanted to confirm that I'm not reading the documentation wrong and this is the expected behavior.

**Comment by lucapivato** [comment]
Actually only the minHeight and minWidth are used.

**Comment by johnspackman** [comment]
I think your interpretation sounds reasonable - if it's ignored at the moment, then adding support won't cause backwards compatibility issues anyway so I imagine there won't be any objections
