### ISSUE TITLE
Automatic testing of packages

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9753]
We should add a way of automatically testing packages (for example, in the build script of the package browser). Even though server-based tests would be preferable (to allow a wide range of testing frameworks), this would be highly insecure since it would entail to allow to run arbitrary commands on travis. 

Therefore, these test must run in the browser, which means that we must provide the test framework ourselves. ATM we have two existing test pipelines: [TestTapper](https://github.com/qooxdoo/qxl.testtapper) and [EventRecorder](https://github.com/cboulanger/eventrecorder). Next to writing documentation how to write tests for these pipelines, we need to provide a way for packages to indicate that they have matching test suites. This needs to be extendible so that more browser-based frameworks can be added later. 

This information could be put either in a `provides.tests` key in `Manifest.json` (which would, for example, point to a singleton class which contains necessary information) or be part of the `compile.json` metadata. It could also be managed by a new command `qx pkg test`. What are your ideas?

**Comment by johnspackman** [comment]
I think I'd vote for singleton, provided (EG) that there is nothing that would require compilation in order for the compiler to work.  

If there's a server element to a package we wouldn't be able to test it, but server based stuff is on the edge of our remit ATM, as in we support node but don't provide much in the way of node-specific scaffolding.

**Comment by hkollmann** [comment]
There is a mechanism to detect Tests in the Framework itselfs. Test must be derived from qx.dev.unit.TestClass with test Methods named testXXX.
So we could use this - and we could use the inbuild test framework. btw. testtapper do exactly this.

Missing is some glue to start testing.
I am playing around with testtapper and the older testrunner project in the moment. As a first step i extracated testrunner to an package: https://github.com/qooxdoo/qxl.testrunner

**Comment by cboulanger** [comment]
@hkollmann But maybe it still would be good to provide a formal way of saying: "This package contains tests that are meant to be run, and please use this class as an entry", so that you can turn tests off, even though they exist in the code. And the framework could figure out which test framework to run by looking at the class. If it is, for example, an instance of `qx.dev.unit.TestClass`, the framework then knows that it should use the TestRunner. If it is an instance of `cboulanger.eventrecorder.player.Abstract`, it would know that it needs to invoke the EventRecorder. That seems to be more extensible, I think.

**Comment by hkollmann** [comment]
You are right. I only want to Mention that there is some stuff to build upon so we must'nt reevent the wheel

**Comment by hkollmann** [comment]
Done with new qx test command
