### ISSUE TITLE
qx.ui.core.Spacer visibility handling causes Exceptions

### ISSUE THREAD

**Issue by hirsch2k** [qooxdoo/qooxdoo#9763]
In our application created with qooxdoo 5.0.2. we sporadically receive the following exception in qx.ui.core.queue.Layout:  
```
Native.js:59 229777 qx.ui.core.queue.Layout: Error in the 'Layout' queue:TypeError: Cannot read property 'left' of null TypeError: Cannot read property 'left' of null
qx.ui.core.queue.Layout:110:38,
qx.ui.core.queue.Manager:160:41,
qx.ui.core.queue.Manager:223:9,
qx.ui.core.queue.Manager:98:12,
qx.ui.core.queue.Manager:69:16,
qx.bom.AnimationFrame:182:18
```
The exception is caused by a null returned from getBounds() call on a qx.ui.core.ColumnData instance.
The qx.ui.core.queue.Layout flush method considers the ColumnData instance as a root widget and calls getBounds on it.
The ColumnData instance is considered as a root widget because it has no parents and the object is marked as visible in the visibility queue qx.ui.core.queue.Visibility.
Why is this object marked as visible?
Because the qx.ui.core.queue.Visibility contains a visibility marker for an object with the same hash code. The object was an qx.ui.core.Spacer instance. The spacer was created long before and added to the visibility management because it was a child of a visible container. The Spacer instance was later disposed but not removed from the visibility management.
The class qx.ui.core.Spacer is derived from qx.ui.core.LayoutItem not from qx.ui.core.Widget like the most other widget-like instances.
The destructor of qx.ui.core.Widget contains code to remove a widget from the UI queues.
Instances of classes derived from LayoutItem are not removed from the UI queues because there is no code for that in the destructor.
If the hash code is re-used for new objects they now can be erroneously reported as visible.
I made a patch for qx.ui.core.Spacer which adds a destruct method:
```
  destruct : function()
  {
    // Remove from ui queues
    qx.ui.core.queue.Appearance.remove(this);
    qx.ui.core.queue.Layout.remove(this);
    qx.ui.core.queue.Visibility.remove(this);
    qx.ui.core.queue.Widget.remove(this);
  }
```

With this patch the error is solved.
What do you think of this?
Am I on the right way?

**Comment by hkollmann** [comment]
Could you create a PR?
Have you tried the new compiler? Do you can reproduce the problem with it?

**Comment by hirsch2k** [comment]
I tried to create an example code to reproduce this bug easily.
During that I detected that the problem could be solved in a simple way.
When closing a window we used the dispose() method.
When i changed this to destory() the problem does not occur any longer.
