### ISSUE TITLE
Convert tutorials into qxl.* apps

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9771]
The applications in https://github.com/qooxdoo/qooxdoo/tree/master/component/tutorials
need to be transformed into (multi-library) qxl.* packages

**Comment by cboulanger** [comment]
Making this a blocker issue since we either release this in a functional state, or remove the tutorials completely and move this issue to the next release. Thanks for your work on this, @hkollmann .

**Comment by hkollmann** [comment]
Nearly done: https://github.com/qooxdoo/qxl.tweet-tutorial.

**Comment by hkollmann** [comment]
Missing doc, this is handled in https://github.com/qooxdoo/qooxdoo/issues/9773
