### ISSUE TITLE
Move deprecated and obsolete repositories from github.com/qooxdoo to github.com/qooxdoo-archive

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9787]
If no objections are voiced, we will rename github.com/qooxdoo-contrib to github.com/qooxdoo-archive and transfer those of the following repositories which are no longer used:

- [x] rename qooxdoo-contrib to qooxdoo-archive
- [x] Inspector
- [x] Mobile-Frameworks-Comparison-Chart
- [x] Points (deleted, fork)
- [x] admin (deleted, empty skeleton)
- [x] cdnjs (deleted, fork)
- [x] generator-stats (deleted, just a logfile)
- [x] grunt-qx
- [x] maven-central-integration
- [x] qooxdoo-bz-archive
- [x] qooxdoo-preset-env
- [x] qooxdoo-wiki
- [x] qx-phantom
- [x] resources
- [x] sizzle (deleted, fork)
- [x] taskspeed (deleted, fork)
- [x] qx-webdriver
- [x] qxwebdriver-java
- [ ] www

Please let me know if any repo in the list has to be kept within the qooxdoo organization namespace.

**Comment by derrell** [comment]
`qooxdoo-wiki` is current and should not be archived. It contains our developer documentation, among other things.

**Comment by hkollmann** [comment]
I thought that is here https://github.com/qooxdoo/qx-dev-manual?

**Comment by derrell** [comment]
It appears you're correct. That one has more recent changes than `qooxdoo-wiki`, which must have been the predecessor. Yes, it looks like `qooxdoo-wiki` can in fact be archived.

**Comment by cboulanger** [comment]
I will also disable

- https://github.com/qooxdoo/qooxdoo/wiki
- https://github.com/qooxdoo/qooxdoo/projects

since they are not used anymore.

**Comment by johnspackman** [comment]
looks good to me;  deleting www should be paired with removing tool/admin/www (submodule) from the core

**Comment by hkollmann** [comment]
IMHO www is used in the build chain of qooxdoo

**Comment by cboulanger** [comment]
What about the "Inspector"? Doesn't it still work with the old toolchain based on the generator?

**Comment by hkollmann** [comment]
Just checked it. WWW can  be moved - the resources are static on the website

**Comment by hkollmann** [comment]
inspector: Is it worth to moddernize it? Has anyone worked with it?

**Comment by johnspackman** [comment]
re inspector: AFAICR it looked interesting but was too intrusive to work.  Its a long time ago, but I remember thinking that It could be useful *if* it could be outside looking in - eg if your qooxdoo app was inside an iframe, and the inspector was outside but using some kind of remote communication to look inside and inspect the objects.  This would require a small server class inside the app for the inspector to talk to, and https://github.com/qooxdoo/qooxdoo/issues/9781 could be a good fit

**Comment by cboulanger** [comment]
Ok, that's a completely new project. I am going to archive and move it over. Then it can be picked up by anyone who wants to revive the project.

**Comment by cboulanger** [comment]
I left "www" for now, there is no harm and we can revisit this after release. Closing.
