### ISSUE TITLE
Setting environment variable "qx.promise" to false has no effect

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo#9802]
**Describe the bug**
The environment setting "qx.promise" was introduced to be able to compile qooxdoo without promises (because that add about 100kb to the compiled code). Currently this behaviour is broken, qx.Promise is always added to the build, even with "qx.promise = false".

I guess this line causes the problem as it uses qx.Promise without checking the "qx.promise" environment setting: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/handler/DragDrop.js#L321

**To Reproduce**
1. Add "qx.promise = false" to your compiler setting
2. Generate a source or build version
3. See that qx.Promise is part of the generated code

**Expected behavior**
qx.Promise should not be added to the generated code when "qx.promise" is set to false.

**Comment by hkollmann** [comment]
Could you povide a PR with a fix? Thanks!

**Comment by peuter** [comment]
I don't know what `getCurrentActionAsync` should return when you do not use Promises. Is it even used in that case? I could change the code to just return `null` when "qx.promise" is false, but that might break things?! Maybe @johnspackman can give an advice?

**Comment by johnspackman** [comment]
The method should not exist - but as that's going to be tricky, I suggest that it just throws an exception.  The issue is that the calling code will be expecting a promise, so returning null (or anything other than a promise) is going to cause serious problems further up the call stack, and that's going to be harder to debug than throwing an exception.  The calling code would need to detect the `qx.promise` environment setting and make its own decision to call `getCurrentAction()` instead.

**Comment by level420** [comment]
It could be done via a conditional method declaration like here:
https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/io/remote/transport/XmlHttp.js#L63
something like:
```javascript
getCurrentActionAsync : qx.core.Environment.select("qx.promise",
{
   true : function() {
      // async code goes here
   },
   false: function() {
      // error or warning about async code used  goes here
   }
},
```
but I'm not sure if this works with ```qx.promise``` and ```qx.core.Environment.select```

**Comment by level420** [comment]
Here is an example which usess ```qx.promise``` and a conditional method declaration:
https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/type/Event.js#L215-L226
