### ISSUE TITLE
Unreachable code in Promise.js

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9804]
When running the source version of my applications using current master, current firefox 70 complains about unreachable code in line https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/Promise.js#L6503-L6504

I don't know if this is of any evidence.

Feel free to close again if this is intended.

**Comment by schnepe2** [comment]
Just for information:

...from the current bluebird source
https://github.com/petkaantonov/bluebird/blob/12154adb5016609901550aad5250045670644dd4/src/util.js#L213
```javascript
function toFastProperties(obj) {
    /*jshint -W027,-W055,-W031*/
    function FakeConstructor() {}
    FakeConstructor.prototype = obj;
    var receiver = new FakeConstructor();
    function ic() {
        return typeof receiver.foo;
    }
    ic();
    ic();
    ASSERT("%HasFastProperties", true, obj);
    return obj;
    // Prevent the function from being optimized through dead code elimination
    // or further optimizations. This code is never reached but even using eval
    // in unreachable code causes v8 to not optimize functions.
    eval(obj);
}
```
The comment seems to indicate a need for this.

It's a pitty that the warning cannot be "silenced". Is there anyone with insight of V8 that might have another solution for this?
Or can someone find out whether this is still an issue (V8 optimizing this code out)?
