### ISSUE TITLE
WOFF 2.0 Support

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9809]
Current implementation of `qx.bom.webfonts.Manager` doesn't accept ".woff2" web-fonts.
As Web Open Font Format 2.0 is nothing new anymore[1]
and supported by the majority of contemporary clients nowadays[2],
it should be supported.

Note: I'll create a PR for this, that works (for me) shortly.

[1] W3C Recommendation 01 March 2018 https://www.w3.org/TR/WOFF2/
[2] https://caniuse.com/#search=woff2

**Comment by hkollmann** [comment]
done wih #9810
