### ISSUE TITLE
Real-life examples: qooxdoo applications in production environments

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9814]
We are thinking about publishing a curated list of qooxdoo applications on the new homepage (#9709), similar to the obsolete ["Real-life examples"](https://web.archive.org/web/20160510215627/http://qooxdoo.org/community/real_life_examples) page. To this end, we invite anyone who is developing an production application with qooxdoo to add a comment to this issue. In the comment, please provide
- the title of the application
- one or preferrably several screenshots
- a short description (100 words max)
- the URL of a public website, if the application has one
- the URL to the source code of the application, if it is open source

This is a way of advertising your application and also to showcase qooxdoo's quality and versatility!

**Comment by valette** [comment]
There is always a first...
App name : EduAnat2

![EduAnat2 screenshot](https://www.creatis.insa-lyon.fr/~valette/public/project/eduanat2/featured_hu8684937c3e81b81cc700f0e8c08ddf0b_175994_720x0_resize_q90_lanczos.jpg)

This program allows easy visualization of medical images, ideal for teaching life sciences at school. Based on [qooxdoo](https://www.qooxdoo.org/), [DESK](https://www.creatis.insa-lyon.fr/~valette/public/project/desk/) and [electron.js](https://electronjs.org/), Eduanat2 has been developed with ease of use as a primary objective, in cooperation with the [French Institute for Education (IFE)](http://acces.ens-lyon.fr/acces/thematiques/neurosciences/outils-numeriques/eduanat2-et-anapeda).

website URL : https://www.creatis.insa-lyon.fr/~valette/public/project/eduanat2/
source code : https://github.com/valette/eduAnat2

**Comment by sgaillard** [comment]
App name: PREMS (The Plant REsource Management System)
![prems_blured](https://user-images.githubusercontent.com/1439395/70053015-d6d8bd80-15d4-11ea-8446-af448a6befe6.png)
This app is a [qooxdoo](https://www.qooxdoo.org/) based front-end for a postgresql database with python jsonrpc web services (ELVIS, see sources) aimed to manage biological resources for plants and seeds. It is actively developed by the [BIDefI](https://www6.angers-nantes.inra.fr/irhs/Recherche/Bioinformatics-for-plant-Defense-Investigations) team at [IRHS](https://www6.angers-nantes.inra.fr/irhs). In the app, users can define groups or collections of plants and use them in projects and experiments. They can characterize them and will be able to store manipulation done in laboratory like sampling or extracting DNA. It is like a LIMS but focused on plants and samples management.
The instance of the app is for internal use only but the app is released under [CeCILL](https://cecill.info/) free software license.
Source code : https://sourcesup.renater.fr/projects/prems / https://sourcesup.renater.fr/projects/elvis

**Comment by odeimaiz** [comment]
o2S2PARC - Open Online Simulations for Stimulating Peripheral Activity to Relieve Conditions

![Dashboard](https://user-images.githubusercontent.com/33152403/70332302-90d46180-1841-11ea-9c7e-e11227739577.JPG)
![Editor](https://user-images.githubusercontent.com/33152403/70332310-929e2500-1841-11ea-80d6-30347757e48a.JPG)

The [application](https://osparc.io/) is not yet completely accessible since an invitation for registering is required (it will be opened early next year).

Description from [the docs](https://docs.osparc.io/): The aim of o2S2PARC is to establish a comprehensive, freely accessible, intuitive, and interactive online platform for simulating peripheral nerve system neuromodulation/stimulation and its impact on organ physiology in a precise and predictive manner. To achieve this, the platform will comprise both state-of-the art and highly detailed animal and human anatomical models with realistic tissue property distributions that make it possible to perform simulations ranging from the molecular scale up to the complexity of the human body.

Some [diagrams](https://github.com/ITISFoundation/osparc-simcore/blob/master/docs/simcore-stack.md) showing how the stack in the backend is configured.

[Main repo](https://github.com/ITISFoundation/osparc-simcore)
[Front-end using qooxdoo](https://github.com/ITISFoundation/osparc-simcore/tree/master/services/web/client)

**Comment by tcsaddul** [comment]
Our website:  www.digisoftph.com

SIAS Online 3.x 

Main Modules:
1.	Admission and Document Management
2.	Pre-Enlistment (Automatic), Enrollment and Auto-Advising
3.	Class Scheduling Wizard (Deans and Registrar)
4.	Assessment, Discounts and Scholarships (UNIFAST reports)
5.	Grading System:  Adaptive / User-defined, RAW Scores, Automatic Transmutation, Universal Grade Conversion
6.	Instructor Modules:  Class Record (Raw Scores such as Quizzes, Class Standing, Periodic Test, etc.), Grade Sheet, Changing of Grades, Learning Resources, Class Attendance and Class Absences
7.	Student Module:  Enrollment, Assessment, Grades, Curriculum Evaluation, General Weighted Average and Statement of Accounts, Learning Resources, Class Absences and Teachers Evaluation
8.	Parent Access:  Gate Entry/Exit SMS Notifications, Per Subject Absences/Late SMS Notifications, Assessment, Grades, Statement of Accounts, Learning Resources, etc.
9.	Curriculum Evaluation: Credited, Equivalent, Internal and External subjects
10.	Teachers Evaluation:  Students can evaluate their teachers
11.	Centralized Clearance System:  Clearance is required only to tagged students
12.	Learning Management:  eBooks, Learning Modules, Reading Materials, Quizzes, Examinations and Projects attached to Subjects
13.	Class Attendance:  Integrated Calendar of Activities, Class Absences Report
14.	Payroll System:  User-defined Income and deductions, Mandatory deductions, Annualized tax computation, Ensures Net take-home pay, Personal Data Sheet, etc.
15.	Point of Sale:  Cashless (e-Wallet), Cash, Account Receivables, Sales Report, Sales Summary Report, Stock Inventory, Price management, Stock-In/Out, etc.
16.	Library System:  Management, OPAC, Inventory, Self-service Kiosk, Penalties, Book Ledger, Patron Ledger, etc.

Some screenshots:

Class Scheduling Wizard:
![image](https://user-images.githubusercontent.com/2255528/70333704-fa269580-187e-11ea-83cc-95e7a405a0d6.png)

Class Attendance Entry:
![image](https://user-images.githubusercontent.com/2255528/70333994-833dcc80-187f-11ea-9025-5c36252e5546.png)

Class Attendance Report:
![image](https://user-images.githubusercontent.com/2255528/70334095-b6805b80-187f-11ea-88fa-ff66217d6dee.png)

**Comment by cboulanger** [comment]
# Bibliograph: Open Source Online Citation & Library Management

Bibliograph  is an application that lets you collect, edit, and publish bibliographic data collaboratively on the web. It has a modern and intuitive user interface that makes the daily life of working with bibliographies and library collections easy and fun. It allows researchers, librarians, teachers and students work together online without having to install software locally. Bibliograph is fully open source and free to download, install, use and adapt to your particular need.

Website: http://www.bibliograph.org
Source code: https://github.com/cboulanger/bibliograph

![bibliograph](https://user-images.githubusercontent.com/75390/70414150-81c7fc00-1a59-11ea-89ba-8d2cf425bbed.jpg)

**Comment by jennytzen** [comment]
### DataLife: Hospital Information System

DataLife is a hospital information system designed to support the management of healthcare institutions, regardless of specialty. It covers all aspects of operations of small, medium and large general and specialist clinics, rehabilitation centers, public hospitals and nursing homes.

Focusing on information integrity, decision support and simplicity, DataLife features:

- In- and out- patient management
- Electronic Medical Records
- Financials, billing and credit tracking
- Inventory and pharmacy management
- Statistics and reporting

Website: [https://www.datalife.gr/](https://www.datalife.gr/)

Screenshot 1: Calendar and event details
![screenshot-a](https://user-images.githubusercontent.com/35702644/70419654-89de6680-1a6e-11ea-9a1e-e09a5dab8e61.png)

Screenshot 2: Financial accounting
![screenshot-b](https://user-images.githubusercontent.com/35702644/70419659-8e0a8400-1a6e-11ea-9b75-8886ed25ca87.png)

Screenshot 3: Settings and access control
![screenshot-c](https://user-images.githubusercontent.com/35702644/70419667-919e0b00-1a6e-11ea-8459-fae2dd005f9f.png)

**Comment by derrell** [comment]
[Mutualink](https://mutualink.net/) **IWS Web** provides an incident-based highly intuitive graphical user interface (GUI) used by a dispatcher or incident manager to communicate with other dispatch personnel and units in the field. Easily share radio, voice, video & data for cross-agency collaboration. Connect with partner agencies in real time with Mutualink’s interoperability system to quickly resolve incidents.

Public safety agencies and critical infrastructure organizations need radio interoperability. Our solution goes beyond basic radio interoperability to provide LMR to LMR, LMR to LTE, real-time video sharing, geospatial information and data sharing capabilities.

All of this is possible through our powerful capability and network called the Interoperable Response and Preparedness Platform (IRAPP). This network is the largest nationwide network of public safety agencies, critical infrastructure, schools and private enterprise security. The IRAPP is transport agnostic, device agnostic and media agnostic. It leverages your current communications assets and incorporates new devices as needed. Connect to the IRAPP network via public or private LTE, satellite or terrestrial broadband.

Emergencies are unpredictable; the who, what, when and where of communications needed for mitigation is unknown until the incident unfolds. Additionally, emergency environments are not static events; new primary as well as secondary and tertiary effects can rapidly emerge. Therefore, collaboration is needed with those in both remote and immediate proximity. The complex inter-dependencies of the real world require a communications approach that serves this dynamic.

 • Displays available partners and agency resources and active incidents
 • Accommodates multiple incidents
 • Real-time voice, video and data sharing
 • Data Encryption
 • Locate and add partners using Network Map
 • Monitor traffic and weather by activating layers on Network Map
 • Manage incidents in Network Map view


![iwsweb](https://user-images.githubusercontent.com/361247/70443088-81356280-1a65-11ea-9d73-5fa0ab03d2bb.png)

Website: [https://mutualink.net/](https://mutualink.net/)

**Comment by yybalam** [comment]
Polaris Aplive

At Laboratorio Nebula of the UPNFM we develop Polaris Aplive, our Frontend application for students users for their academic management, like enrolment, academic history, messaging,  e-learning, etc.
Polaris is daily used by more of 27,000 students across the country, resulting in a fundamental tool for the University activities.

Login screen
![t1_01](https://user-images.githubusercontent.com/579563/70643594-e4122f80-1c06-11ea-845b-9d4b3156ffcc.png)

Enrolment screen
![Polaris](https://user-images.githubusercontent.com/579563/70643602-e8d6e380-1c06-11ea-8bcc-35828789d0c5.png)

**Comment by Holdwyn** [comment]
**ReForm** (by [SiBit](https://www.sibitag.com/home))
A comprehensive CRUD-like Framewerk specialized for implementing business processes. Based on ReForm we've build applications like a warehouse management system for our customer [AfB](https://www.afb-group.de/home/) and the asset management Software Office Asset.

Some Screenshots:
![image](https://user-images.githubusercontent.com/49226428/74228066-01738080-4cc0-11ea-9ce7-383456befd2e.png)

![image](https://user-images.githubusercontent.com/49226428/74228156-2a941100-4cc0-11ea-8993-4204fe1e0a8e.png)

**Comment by cboulanger** [comment]
Other potential qooxdoo users (h/t @slachtar)
- GPS tracking solutions provider https://gurtam.com/  see https://sdk.wialon.com/api/#qx
- Proxmox v6? (to be confirmed)

**Comment by cboulanger** [comment]
@valette @derrell @yybalam @sgaillard @Holdwyn @jennytzen @tcsaddul @odeimaiz 
I have added your app to http://www.qooxdoo.org/website/portfolio/

You are welcome to clone https://github.com/qooxdoo/website and create a PR against https://github.com/qooxdoo/website/blob/master/html/portfolio/index.html to update your entry.

For layout reasons, I have added only one screenshot. The other ones should be still there in the `img` folder and you can re-insert them into the text. 

When reviewing and revising, please

- try to keep your entry as concise as possible
- provide links to your application, the source code (if open open source), and to your company
- if possible, add some info on what makes qooxdoo especially useful for your app/ your development

Thank you!

**Comment by cboulanger** [comment]
@pcdummy Can you tell us if ProxMox is/has been experimenting/using Qooxdoo? That would be great...

**Comment by pcdummy** [comment]
@cboulanger I was personaly checking Qooxdoo for Proxmox but it never did it's way into Production.

**Comment by cboulanger** [comment]
@pcdummy Thank you for letting us know!

**Comment by johnspackman** [comment]
We've just pushed a new version of the website, including some changes to how portfolio works - please check your entry at http://www.qooxdoo.org/website/portfolio.html

If you want to change your entry (or add a new one) it's easy to do - just fork the [qooxdoo/website](https://github.com/qooxdoo/website) repo and create a PR.  It's a lot simpler to create a portfolio entry now, you just have to add/edit a `.json` file in a directory and it gets picked up automatically.  Full details are in the README for the repo

**Comment by cboulanger** [comment]
Closing, website feature has been implemented.
