### ISSUE TITLE
qx.ui.form.List and PageDown/PageUp may hand the browser.

### ISSUE THREAD

**Issue by lucapivato** [qooxdoo/qooxdoo#9839]
When the scroll area can fit only 1 item, pressing PageDown hangs the browser in an infinite loop.

Playgroud test:
https://bit.ly/2Znd9Ys

Select the first item and press PageDown.

https://github.com/iceteagroup/Wisej/issues/2102

**Comment by lucapivato** [comment]
Fixed in #9840.

**Comment by hkollmann** [comment]
Done with #9840
