### ISSUE TITLE
Wrong column width calculation in grid layout with colSpan

### ISSUE THREAD

**Issue by Holdwyn** [qooxdoo/qooxdoo#9859]
Pretty hard to explain but I'll try:
A widget set to column with colSpan did not increase the width of columns spaned across. The result ist that a second widget set to a colum next to the spaned column ist printed over the first widget.

1. Create a grid with some v- and hSpacing
2. Add a widget with width 300px to column 0 and row 0 with colSpan 2
3. Add widgets with a width of 100px in row 1 and column 0 and 1
4. Add a widget to column 2 and row 0
5. The widget added in step 4 is printed over the widget from step 2

**Expected behavior**
Column 0 and 1 should increase their width so that column 2 is not printed above the widget.

**Screenshots**
![image](https://user-images.githubusercontent.com/49226428/74223873-ee5cb280-4cb7-11ea-8411-c67f4696357e.png)

**Additional context**
The hight calculation with rowSpan seems to work just fine!

**Comment by hkollmann** [comment]
Fixed with #9859
