### ISSUE TITLE
Remove deprecation of qx.io.remote

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9885]
Following on from discussions in gitter, we want to reverse the deprecation of `qx.io.remote` since many people's code depend on it and there is no easy migration path to `qx.io.request`; the `qx.io.remote` has also more features

**Comment by level420** [comment]
I'm heavily using `qx.io.rest.Resource` in my applications which is based on `qx.io.request.Xhr`. 
Deprecating `qx.io.request` will also deprecate `qx.io.rest.Resource`.

**Comment by cboulanger** [comment]
.... wait. I am in favour of removing the deprecation of `qx.io.request` as it is in the docs and the code.  I am not in favour of the what's in the title. I think both APIs should be kept and eventually one of them might fall out of use.

**Comment by cboulanger** [comment]
See my proposal for a new page in the docs: https://github.com/qooxdoo/qooxdoo/blob/6a938448029d477f67a7ead632154d997a8722be/docs/communication/README.md (for which I will make a separate PR in an updated version)

**Comment by johnspackman** [comment]
i just think it's confusing to have both - IMHO it's difficult to be 100% sure which is the newer one without a quick check in the code.

A quick scan in `qx.io.rest` suggests that it would be fairly easy to migrate it to `qx.io.remote` - the only exception could be if the caller is providing their own implementation of `qx.bom.request.IRequest`.

`qx.io.request` is split into `qx.bom.request`, and `qx.io.rest` has a similar split into `qx.bom.rest` - i'm all for separation of concerns etc, but this feels like over-normalisation, and IMHO another mark for deprecating `qx.io.request` (and `qx.bom.request`)

**Comment by cboulanger** [comment]
I cannot comment on how much sense it makes to have `qx.bom.request` and such, but `qx.io.request` is much better architected, for example `qx.io.request.authentication` has no equivalent in `qx.io.remote` - authentication there is put into ad-hoc setter methods, which is not extensible and generally bad IMHO.

**Comment by cboulanger** [comment]
I agree with @johnspackman that the situation is confusing, I  just don't think deprecating the newer and migrating to the older (and in my opinion inferior) API is the right way. I think better documentation which clarifies the situation will help.

**Comment by johnspackman** [comment]
ok fair enough

**Comment by derrell** [comment]
At present, the two have different capabilities, and people are using both. Until we have a single namespace that accomplishes what both current accomplish, it is my opinion that we should not deprecate either. (There is also likely a very lot of code using the original one, so if we move to the new one only, we should try to maintain that API as an option... or maybe implement the old one in terms of the new one, so it's just a backwards-compatible API.)

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9886
