### ISSUE TITLE
Master playground

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9892]
Any URL that points to the master playground (http://qooxdoo.github.io/devel/playground/), like many tinyurl links in bug reports are now worthless as they all end up in the "oops ... this page does not exist" page.
It would be good if http://qooxdoo.github.io/devel/playground/ would work again.

As examples, some (not really 😉) randomly chosen links from [from #9070]:
- http://qooxdoo.github.io/devel/playground/
- http://tinyurl.com/gtvulqq
- http://tinyurl.com/zh8bvyt

**Comment by cboulanger** [comment]
Thanks @schnepe2 for reporting.

**Comment by hkollmann** [comment]
Seems that the build of the playground do not work any longer. The build has Problems with sass in the python toolchain:

>>> Scanning libraries  /home/travis/.rvm/gems/ruby-2.4.1/bin/sass:15:in `<main>': undefined method `b' for "-C":String (NoMethodError)
981
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
982
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
983
/home/travis/.rvm/gems/ruby-2.4.1/bin/sass:15:in `<main>': undefined method `b' for "-C":String (NoMethodError)
984
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
985
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
986
/home/travis/.rvm/gems/ruby-2.4.1/bin/sass:15:in `<main>'Traceback (most recent call last):
987
  File "/home/travis/build/qooxdoo/qooxdoo/tool/bin/generator.py", line 267, in <module>
988
    main()
989

mobileshowcase - which is using sass too - is not build either. 

see https://github.com/qooxdoo/qooxdoo.github.io/tree/master/devel

What shall we do? Link devel/playground to 6.0.0-beta/apps/playground and do not use the python build any longer?

Would be the easiest way...

**Comment by cboulanger** [comment]
Yes, let's transition away from the python buildchain now  - it will be a slow process anyways.

**Comment by hkollmann** [comment]
Setting a link in qooxdoo.github.io/dev do no work.
I changed the 404.html in qooxdoo.github.io to resolve the problem
