### ISSUE TITLE
Update sinon

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9897]
The sinon library included in qx.dev.unit.* is very old and needs to be updated. For example, it suffers from https://github.com/sinonjs/sinon/issues/1709 . See also #9277

**Comment by hkollmann** [comment]
Be careful - i patched the sinon part recently so that it cam work with qooxdoo and node...

**Comment by cboulanger** [comment]
Thanks for letting me know. Can you link to the diff here, so that I don't forget? I don't know when I will have time to revisit the issue. I'll have to upgrade carefully anyways since any incompatibility will break the framework tests.

**Comment by hkollmann** [comment]
https://github.com/qooxdoo/qooxdoo/pull/9870/files
