### ISSUE TITLE
New Website - Launch run-up

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9899]
This issue is to coordinate the steps needed to get the new website up and running. Please feel free to add items to the following To Do list. 

- [x] Decide where website content will be hosted (GitHub repo vs. server Webspace) 
- [x] Decide how to deal with legacy content (continue to use (bloated) repo vs use static copy of current repo content in new repo) 
- [x] #9892 Fix links to playground (and other legacy apps, btw.)
- [ ] 

See also:
- #9709 Design Brief
- #9814 Content for possible Real-World Examples Slider

**Comment by johnspackman** [comment]
> Decide where website content will be hosted (GitHub repo vs. server Webspace)

For the website, it would be easiest to manage if it was a static website that is generated using Nunjucks; but OTOH there will come a time (fairly soon perhaps?) when we want to be able to demo server side code as well, in which case we could decide to have something hosted now.

If there was something server side, I'd implement it using the `qxl.cms` subproject - which is functional enough that I have a few rudimentary websites being built with it, but does not have a user interface at the moment (so you have to hand edit the pages rather than in place edit etc).  

The `qxl.cms` uses Nunjucks internally, so there wouldn't be a great loss or repetition in work if we went for a static site now, and I suspect that a static site would be the route of least distraction from the main goal of creating a new website

**Comment by cboulanger** [comment]
@johnspackman Sounds good - I'd go for the most pragmatic solution that we have. The main question for me is if we stick with the GitHub solution which is free but cannot provide anything dynamic or if one of you with a business provides webspace to which we upload the static stuff. We should decide this rather swiftly and then create a GitHub workflow which deploys the website.

**Comment by johnspackman** [comment]
I'm happy to provide and host a virtual server, so long as it's Linux.  We can run whatever we like on it then :)  We could have some kind of automatic backup to another site, so even if something really bad and unexpected happened to me, the server could be brought up elsewhere with a minimum of fuss

**Comment by oetiker** [comment]
I guess as long as we build everything on this box automatically from what is on git we don't even need a backup :-)

**Comment by oetiker** [comment]
an option is also to host the 'server' part on 'server.qooxdoo.org' and still have the static webpages on github pages ... github pages has the big advantage that lots of traffic is no problem for it :) in case we get really popular :)

**Comment by johnspackman** [comment]
> I guess as long as we build everything on this box automatically from what is on git we don't even need a backup :-)

yes, that's true

> an option is also to host the 'server' part on 'server.qooxdoo.org' 

We could do, it might mean that if we switch to having something server side and that's implemented with `qxl.cms` (which would be a suitable showcase for it) we'd be switching to everything on the server anyway.  Although on the other, *other* hand I have thought that `qxl.cms` might support an on-the-fly export to a static mirror site anyway...

My inclination is to go with github and static generation now and decide how to do a dynamic server later, but it's a pretty close call for me.

**Comment by derrell** [comment]
There will be CORS to consider if the server is not where the pages are hosted.

**Comment by cboulanger** [comment]
Let's go with github but with a *new* repo, and link from there to legacy stuff at https://github.com/qooxdoo/qooxdoo.github.io

**Comment by johnspackman** [comment]
I think we're ok though because with CORS the server would be able to authorise the website to connect with `Access-Control-Allow-Origin: http://www.qooxdoo.org`.  AIUI the static website would not need to do anything for CORS, so if we are unable to modify the headers that's OK

**Comment by oetiker** [comment]
CORS works very well ... no problem

**Comment by cboulanger** [comment]
Update: @johnspackman has uploaded the HTML 
Source code: https://github.com/qooxdoo/website 
www: http://www.qooxdoo.org/website/html/

**Comment by cboulanger** [comment]
@oetiker How is the domain mapping done? Probably through some qooxdoo organization setting?

**Comment by cboulanger** [comment]
We need some redirections so that the legacy links still work.

**Comment by cboulanger** [comment]
I think that the website is good to go now and should be published. This will allow us to fix the remaining bugs and polish it before we launch v6.

**Comment by johnspackman** [comment]
I've just reviewed the website, I agree except that I think we should put the portfolio inside branding, ie keep the header, navigation, and footer?  I can take a look today if you like?

**Comment by oetiker** [comment]
> @oetiker How is the domain mapping done? Probably through some qooxdoo organization setting?

simply by placing the CNAME file into the root of the website ... remove it where it is now and place it into the other repo ... done

**Comment by zaucker** [comment]
I like the new website. A few minor comments to the homepage:
- It seems a bit colorful, but as a hommage at the LGBT-community it's fine ;-)
- I think there is a bit to much vertical "spacing" in the different "sections" (above the actual content)
- The linespacing within the sections seems a bit small, whereas the linespacing in the footer seems a bit large
And yes, this might just be personal taste, I am by no means a design professional.

**Comment by hkollmann** [comment]
Nee Website is up and running
