### ISSUE TITLE
Breaking changes / migration paths

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9909]
This issue is to collect any breaking changes of v6.0.0 and possible migration paths, so that we have a list ready for our release notes.

**Comment by hkollmann** [comment]
Default of rpc has changed from "qx1" to "2.0"

**Comment by schnepe2** [comment]
`qx.ui.splitpane.Splitter` :
- New Property `knobVisible` toggles visibility of the splitter's button.
- Property `visible` toggles visibility of the whole splitter widget (no change from v5.0.x).

**Comment by schnepe2** [comment]
- `qx.bom.client.Css`
Removed obsolete IE-Feature check methods `getFilterGradient` and `getFilterTextShadow`. If used in production code, consider them as being a `false` value.
- `qx.core.Environment`
Removed obsolete IE-Feature keys `"css.gradient.filter"` and `"css.textShadow.filter"`. If used in production code, consider them as being a `false` value.

**Comment by hkollmann** [comment]
framework/source/class/qx/ui/table/cellrenderer/AbstractImage.js: change vertical alignment from top to middle.

**Comment by cboulanger** [comment]
Breaking changes are documented here: https://github.com/qooxdoo/qooxdoo/blob/master/CHANGELOG.md
