### ISSUE TITLE
"qooxdoo - the new era of web development"

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9947]
Should we replace this slogan with a new one in the source file header comments? Doesn't really fit anymore since it's probably from 2006-2008 or so.

**Comment by goldim** [comment]
I think new slogan has to emphasize strong and unique sides comparing to current popular solutions (among them Angular, Vue and etc) which we have at this moment. There is a list of slogans which come to my mind:

- "the strong choice for Web enterprise",
- "the Javascript framework for coders" (this slogan used in gitter)",
- "the solid Javascript framework",
- "desktop-like framework for web",
- "Build desktop applications in/on Web"
- "Build your desktop application in/on Web"
- and so on.
