### ISSUE TITLE
qx.event.message.Bus.unsubscribe: Wrong behavior or wrong documentation

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9955]
The jsdoc of [`qx.event.message.Bus.unsubscribe`](https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/message/Bus.js#L235) incorrectly states that the name of the message "can be truncated by *". Looking at the source code, no such behavior exists. Either implement behavior or change documentation.

**Comment by derrell** [comment]
Both subscriptions and unsubscriptions can have a terminating asterisk, but that asterisk is considered only while dispatching messages. The current behavior is that you can unsubscribe using the same string as you subscribed with. I believe the current behavior is correct. The documentation may just be a bit misleading, based on how you interpret "truncated". My suggestion is that the documentation be updated to state something like, 

```
If a "wildcard" topic was subscribed to with a trailing asterisk, because the subscriber wanted to
receive messages for any topic with the given prefix, that same "wildcard" topic should be used to
unsubscribe. It is not possible to unsubscribe using any topic other than one exactly matching one
that has previously been subscribed to.
```

**Comment by cboulanger** [comment]
Ah ok, you are right. This needs to be made more explicit: the wildcard does not act as a filter for the registered subscriptions, it is part of the subscriber's name filter  which selects on the name of the messages that the subscriber will listen to.  For example, when you subscribe to "foo.bar" and "foo.goo" individually, you cannot unsubscribe from both message names with "foo.*"

**Comment by cboulanger** [comment]
I'll add your documentation bit - thank you!

**Comment by cboulanger** [comment]
This has already [been added](https://github.com/qooxdoo/qooxdoo/blob/ccc494446c1dc306e741753ceb42cb96301aba4d/framework/source/class/qx/event/message/Bus.js#L265). Closing.
