### ISSUE TITLE
Move documentation to its own repo

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9957]
The content of the `docs` folder should be moved into its own repository, which could be named `documentation` and would be accessible at https://qooxdoo.org/documentation

The reason is that a separate repository can have its own workflows and a separate review process, which currently is implemented with some torturous ad-hocery. Also, minor updates would no longer trigger releases. 

The main reason for keeping it with the code so far has been that it was possible to version the documentation. This will be taken care of by a dedicated versioning workflow (#9954) which will create a copy of the state of the documentation for each release and/or create a separate release of the documentation repo. The new repo's HEAD will reflect the HEAD of the qooxdoo framework repo.

**Comment by cboulanger** [comment]
https://github.com/qooxdoo/documentation
http://qooxdoo.org/documentation/#/
Still to do: update website with new links, create redirection

**Comment by hkollmann** [comment]
it's back
