### ISSUE TITLE
Links to "API reference" & "desktop demo" in new documentation transfer to "oops page"

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9970]
From the new doc page(s), the links point to "wrong" URLs.
Tried from here: https://qooxdoo.org/docs/#/desktop/gui/window_management?id=demos-and-api

**Direct links** to specific methods/classes/etc. seem to work however[1].

-- 
[1] ...although I haven't tested them all 😉

**Comment by hkollmann** [comment]
fixed with https://github.com/qooxdoo/qooxdoo/pull/9975
