### ISSUE TITLE
asynchronous ireEventAsync, fireDataEventAsync, and fireNonBubblingEventAsync do not exists

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9981]
The documented methods fireEventAsync, fireDataEventAsync, and fireNonBubblingEventAsync do not exists im MEvent.

Only in qx.event.Registration you found     fireEventAsync : function(target, type, clazz, args).

Should we remove the doc or should we implement the methods?

**Comment by cboulanger** [comment]
Where is it documented?

**Comment by hkollmann** [comment]
here https://qooxdoo.org/docs/#/core/promises?id=firing-asynchronous-events

**Comment by cboulanger** [comment]
We should probably implement them, it seems strange that they aren't. @johnspackman, what's your thoughts?

**Comment by johnspackman** [comment]
fine by me

**Comment by hkollmann** [comment]
@johnspackman could you do this please?
