### ISSUE TITLE
Delete legacy folders

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9984]
Now that we have migrated all of the docs to markdown, the "documentation" folder is no longer needed. We have a [backup of the v5 documentation](https://github.com/qooxdoo/website-archive/tree/master/5.0.2/pages) and it is in the git history, should we ever need to look at the `.rst` source code. The "documentation" folder should therefore be deleted in master.

**Comment by cboulanger** [comment]
We should also delete "application" and "component" folders since they are no longer needed and cannot be supported.

**Comment by hkollmann** [comment]
This will break the build process. Imho we should do this after releasing 6.0 and rework the build process at the same time

**Comment by cboulanger** [comment]
@hkollmann It boils down to whether we want to keep providing the SDK, doesn't it? Because  that's the only place components and applications go since they are no longer needed for the website. I guess you are right that the SDK is still necessary for continued generator use, because how else except via a checkout of the repo would people use it. If that is so, we need some (barebone) documentation on this (at least in the release notes).

**Comment by cboulanger** [comment]
@hkollmann is right. Moving this to until after release.

**Comment by hkollmann** [comment]
done
