### ISSUE TITLE
Reorganize testing architecture

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9985]
The "test" folder has collected some dust. After release of v6 and the merger of the framework and compiler repos, we should reorganize it, maybe like this:
```
api/ (javascript test cases for the api, organized as modules, to be run via `qx test`)
bats/ (CLI tests using bats)
compiler/ (apps that test compilation behavior, including those that address individual compiler bugs)
data/ 
uitests/ (apps that test different ui behaviors and are run with a headless browser)
```

**Comment by johnspackman** [comment]
IMHO we should ditch `bats` completely - debugging support is non-existent, and the tools for validating results are poor.

**Comment by cboulanger** [comment]
Do you know of a better alternative? I guess the single best way to do it is to move everything to node and run the CLI commands through node. This would also eliminate the need to have separate scripts for each OS. This also looks interesting: https://www.npmjs.com/package/shelljs

**Comment by johnspackman** [comment]
Yes, we use node already in https://github.com/qooxdoo/qooxdoo-compiler/blob/master/test/test-commands.js and https://github.com/qooxdoo/qooxdoo-compiler/blob/master/test/test-cli.js

Cross platform is another bats failure, I've re-written tests using node because I couldnt get them to run on OSX, and as you can't even add `echo` debug statements its impossible to figure out whats going on.

**Comment by cboulanger** [comment]
... so that we have a unified testing infrastructure that is called with `qx test` and no longer with `npm test` (which would just call `qx test`).

**Comment by johnspackman** [comment]
:+1: yes, another good reason to ditch bats :)

**Comment by cboulanger** [comment]
I have no problem ditching bats - it seemed the best available tool at the time but obviously isn't. After release, we should create to a `compile.js` in the framework repo and run all test starting from there. Have you looked at shelljs? Might that be a good tool? Interestingly, it seems to run all commands synchrously, which is kind of uncommon these days, but would fit the shell script pattern.

**Comment by johnspackman** [comment]
shelljs looks nice, esp because it's quite obvious what the api is doing (`sjs.ls().forEach...` etc).  it looks like asynchronous is easily done, so a promisified wrapper would be ideal

**Comment by hkollmann** [comment]
I would suggest to put the unit Tests (api) under source/test/… 
This is the qooxdoo standard found in the framework

**Comment by cboulanger** [comment]
@hkollmann Yes, unit tests with a proper `qx.test` namespace which are run using `qx.dev.unit.*` are not to be included here, since they are part of the framework code tree. This is only about external testing, either through the `qx test` pipeline (it should be our goal to move everything into it), or the various other ad-hoc solutions that have piled up in and which we are currently using in our compiler tests...

**Comment by hkollmann** [comment]
done
