### ISSUE TITLE
https://qooxdoo.org/qxl.apiviewer/#qx.dev.unit needs to be updated

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#9987]

**Comment by hkollmann** [comment]
Where is the problem? This is a task for qooxdoo - not apiviewer

**Comment by cboulanger** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9994/commits/a5ffc02a55353dff44b66d0d50b8ec8c0ecb3bce
